HEADERS = [
    "Country",
    "City",
    "University",
    "Tuition (per semester)",
    "Semester Fee (local)",
    "Rent (per month)",
    "Health Insurance (per month)",
    "Living Costs (per month)",
    "Total Yearly",
    "Notes",
]

CITY_COSTS = [
    # Germany
    {
        "country": "Germany",
        "city": "Munich",
        "university": "TUM, LMU",
        "tuition": 0,
        "tuition_currency": "EUR",
        "semester_fee": 152,
        "rent": 600,
        "insurance": 120,
        "living": 1200,
        "blocked_account": 11208,
        "total_yearly_note": "~14,704 EUR (FREE tuition)",
        "notes": "Most expensive city but best universities. Part-time jobs available.",
    },
    {
        "country": "Germany",
        "city": "Berlin",
        "university": "TU Berlin, FU Berlin, HU Berlin",
        "tuition": 0,
        "tuition_currency": "EUR",
        "semester_fee": 330,
        "rent": 500,
        "insurance": 110,
        "living": 1000,
        "blocked_account": 11208,
        "total_yearly_note": "~12,660 EUR (FREE tuition)",
        "notes": "Startup hub. More affordable than Munich. Many English programs.",
    },
    {
        "country": "Germany",
        "city": "Aachen",
        "university": "RWTH Aachen",
        "tuition": 0,
        "tuition_currency": "EUR",
        "semester_fee": 300,
        "rent": 400,
        "insurance": 110,
        "living": 900,
        "blocked_account": 11208,
        "total_yearly_note": "~11,400 EUR (FREE tuition)",
        "notes": "Smaller city, lower cost. Excellent engineering university.",
    },
    {
        "country": "Germany",
        "city": "Bonn",
        "university": "University of Bonn",
        "tuition": 0,
        "tuition_currency": "EUR",
        "semester_fee": 330,
        "rent": 380,
        "insurance": 110,
        "living": 850,
        "blocked_account": 11208,
        "total_yearly_note": "~10,860 EUR (FREE tuition)",
        "notes": "Affordable. Hausdorff Center for Math is world-class.",
    },
    {
        "country": "Germany",
        "city": "Karlsruhe",
        "university": "KIT",
        "tuition": 1500,
        "tuition_currency": "EUR",
        "semester_fee": 190,
        "rent": 420,
        "insurance": 110,
        "living": 900,
        "blocked_account": 11208,
        "total_yearly_note": "~13,800 EUR (3k tuition)",
        "notes": "Non-EU tuition (Baden-Wuerttemberg). Still affordable vs other countries.",
    },
    {
        "country": "Germany",
        "city": "Darmstadt",
        "university": "TU Darmstadt",
        "tuition": 0,
        "tuition_currency": "EUR",
        "semester_fee": 400,
        "rent": 400,
        "insurance": 110,
        "living": 900,
        "blocked_account": 11208,
        "total_yearly_note": "~11,600 EUR (FREE tuition)",
        "notes": "Zero tuition. Good data science program. Moderate living costs.",
    },
    {
        "country": "Germany",
        "city": "Freiburg",
        "university": "University of Freiburg",
        "tuition": 1500,
        "tuition_currency": "EUR",
        "semester_fee": 170,
        "rent": 450,
        "insurance": 110,
        "living": 900,
        "blocked_account": 11208,
        "total_yearly_note": "~13,840 EUR (3k tuition)",
        "notes": "Non-EU tuition (Baden-Wuerttemberg). Beautiful city. Strong AI research.",
    },
    {
        "country": "Germany",
        "city": "Dresden",
        "university": "TU Dresden",
        "tuition": 0,
        "tuition_currency": "EUR",
        "semester_fee": 300,
        "rent": 350,
        "insurance": 100,
        "living": 800,
        "blocked_account": 11208,
        "total_yearly_note": "~10,200 EUR (FREE tuition)",
        "notes": "Most affordable option. Zero tuition. Good research center.",
    },
    {
        "country": "Germany",
        "city": "Goettingen",
        "university": "University of Goettingen",
        "tuition": 0,
        "tuition_currency": "EUR",
        "semester_fee": 400,
        "rent": 370,
        "insurance": 100,
        "living": 800,
        "blocked_account": 11208,
        "total_yearly_note": "~10,400 EUR (FREE tuition)",
        "notes": "Excellent Statistics program. Zero tuition. Very affordable living.",
    },
    {
        "country": "Germany",
        "city": "Hamburg",
        "university": "University of Hamburg",
        "tuition": 0,
        "tuition_currency": "EUR",
        "semester_fee": 335,
        "rent": 500,
        "insurance": 110,
        "living": 950,
        "blocked_account": 11208,
        "total_yearly_note": "~12,070 EUR (FREE tuition)",
        "notes": "Major port city. Zero tuition. Growing AI/Data Science programs.",
    },
    # USA
    {
        "country": "USA",
        "city": "Stanford / Palo Alto",
        "university": "Stanford University",
        "tuition": 28000,
        "tuition_currency": "USD",
        "semester_fee": 500,
        "rent": 1500,
        "insurance": 250,
        "living": 2500,
        "blocked_account": 0,
        "total_yearly_note": "~$83,000 (high, but TA/RA can cover)",
        "notes": "Most expensive; Knight-Hennessy covers FULL cost if awarded",
    },
    {
        "country": "USA",
        "city": "Cambridge / Boston",
        "university": "MIT / Harvard",
        "tuition": 28000,
        "tuition_currency": "USD",
        "semester_fee": 500,
        "rent": 1400,
        "insurance": 250,
        "living": 2400,
        "blocked_account": 0,
        "total_yearly_note": "~$80,000 (without funding)",
        "notes": "Ivy+/MIT; TA/RA can cover tuition + stipend; need strong profile",
    },
    {
        "country": "USA",
        "city": "Pittsburgh",
        "university": "Carnegie Mellon University",
        "tuition": 26000,
        "tuition_currency": "USD",
        "semester_fee": 400,
        "rent": 900,
        "insurance": 200,
        "living": 1700,
        "blocked_account": 0,
        "total_yearly_note": "~$66,000 (some TA/RA available)",
        "notes": "Best ML program globally; TA/RA positions competitive",
    },
    {
        "country": "USA",
        "city": "Berkeley",
        "university": "UC Berkeley",
        "tuition": 12000,
        "tuition_currency": "USD",
        "semester_fee": 800,
        "rent": 1400,
        "insurance": 200,
        "living": 2300,
        "blocked_account": 0,
        "total_yearly_note": "~$54,000 (non-resident tuition)",
        "notes": "Public Ivy; lower tuition than private; good TA/RA opportunities",
    },
    {
        "country": "USA",
        "city": "Atlanta",
        "university": "Georgia Tech",
        "tuition": 8000,
        "tuition_currency": "USD",
        "semester_fee": 600,
        "rent": 900,
        "insurance": 150,
        "living": 1600,
        "blocked_account": 0,
        "total_yearly_note": "~$38,000 (most affordable US option)",
        "notes": "Best value in US; strong data science; good TA/RA availability",
    },
    {
        "country": "USA",
        "city": "Seattle",
        "university": "University of Washington",
        "tuition": 12000,
        "tuition_currency": "USD",
        "semester_fee": 700,
        "rent": 1300,
        "insurance": 200,
        "living": 2200,
        "blocked_account": 0,
        "total_yearly_note": "~$52,000 (non-resident)",
        "notes": "Strong ML research; good TA/RA; Amazon/Microsoft nearby",
    },
    {
        "country": "USA",
        "city": "Ann Arbor",
        "university": "University of Michigan",
        "tuition": 13000,
        "tuition_currency": "USD",
        "semester_fee": 600,
        "rent": 1000,
        "insurance": 180,
        "living": 1800,
        "blocked_account": 0,
        "total_yearly_note": "~$48,000 (non-resident)",
        "notes": "Strong data science; large international community",
    },
    # UK
    {
        "country": "UK",
        "city": "London",
        "university": "Imperial College, UCL, KCL",
        "tuition": 15000,
        "tuition_currency": "GBP",
        "semester_fee": 0,
        "rent": 1000,
        "insurance": 0,
        "living": 1500,
        "blocked_account": 0,
        "total_yearly_note": "~£39,000/yr (Chevening/Commonwealth can cover fully)",
        "notes": "Most expensive UK city. Chevening (£20k+ tuition) & Commonwealth (£25k+ tuition) are full-ride targets.",
    },
    {
        "country": "UK",
        "city": "Oxford",
        "university": "University of Oxford",
        "tuition": 15000,
        "tuition_currency": "GBP",
        "semester_fee": 0,
        "rent": 900,
        "insurance": 0,
        "living": 1300,
        "blocked_account": 0,
        "total_yearly_note": "~£35,000/yr (college fees included in tuition)",
        "notes": "World-class ML/AI research. Commonwealth & Chevening both cover Oxford.",
    },
    {
        "country": "UK",
        "city": "Cambridge",
        "university": "University of Cambridge",
        "tuition": 15000,
        "tuition_currency": "GBP",
        "semester_fee": 0,
        "rent": 900,
        "insurance": 0,
        "living": 1300,
        "blocked_account": 0,
        "total_yearly_note": "~£35,000/yr (college fees included)",
        "notes": "Strong ML/Stats programs. Commonwealth scholarship strongly recommended.",
    },
    {
        "country": "UK",
        "city": "Edinburgh",
        "university": "University of Edinburgh",
        "tuition": 14000,
        "tuition_currency": "GBP",
        "semester_fee": 0,
        "rent": 700,
        "insurance": 0,
        "living": 1100,
        "blocked_account": 0,
        "total_yearly_note": "~£29,000/yr (lower cost of living)",
        "notes": "Cheaper than London. Strong AI/DL research group. Commonwealth eligible.",
    },
    {
        "country": "UK",
        "city": "Manchester",
        "university": "University of Manchester",
        "tuition": 13000,
        "tuition_currency": "GBP",
        "semester_fee": 0,
        "rent": 600,
        "insurance": 0,
        "living": 1000,
        "blocked_account": 0,
        "total_yearly_note": "~£25,000/yr (most affordable UK option)",
        "notes": "Great value. Strong Data Science program. Commonwealth scholarship target.",
    },
    # Canada
    {
        "country": "Canada",
        "city": "Toronto",
        "university": "University of Toronto",
        "tuition": 20000,
        "tuition_currency": "CAD",
        "semester_fee": 500,
        "rent": 1200,
        "insurance": 100,
        "living": 1800,
        "blocked_account": 0,
        "total_yearly_note": "~$56,000 CAD/yr (Vanier covers $50k CAD/yr)",
        "notes": "Top AI research (Vector Institute). Vanier scholarship = full funding target.",
    },
    {
        "country": "Canada",
        "city": "Vancouver",
        "university": "UBC",
        "tuition": 18000,
        "tuition_currency": "CAD",
        "semester_fee": 400,
        "rent": 1300,
        "insurance": 100,
        "living": 1700,
        "blocked_account": 0,
        "total_yearly_note": "~$53,000 CAD/yr (Vanier eligible)",
        "notes": "Strong ML research. Beautiful city. Vanier = $50k/yr. TA/RA also available.",
    },
    {
        "country": "Canada",
        "city": "Montreal",
        "university": "McGill University, MILA",
        "tuition": 16000,
        "tuition_currency": "CAD",
        "semester_fee": 400,
        "rent": 800,
        "insurance": 100,
        "living": 1300,
        "blocked_account": 0,
        "total_yearly_note": "~$40,000 CAD/yr (most affordable Canadian option)",
        "notes": "MILA = world's top DL research hub. Lower living costs. Vanier & Quebec scholarships.",
    },
    {
        "country": "Canada",
        "city": "Waterloo",
        "university": "University of Waterloo",
        "tuition": 15000,
        "tuition_currency": "CAD",
        "semester_fee": 400,
        "rent": 700,
        "insurance": 100,
        "living": 1300,
        "blocked_account": 0,
        "total_yearly_note": "~$38,000 CAD/yr (good value)",
        "notes": "Strong CS/Stats co-op programs. Good TA/RA opportunities. Vector Institute affiliate.",
    },
    # Switzerland
    {
        "country": "Switzerland",
        "city": "Zurich",
        "university": "ETH Zurich, University of Zurich",
        "tuition": 730,
        "tuition_currency": "CHF",
        "semester_fee": 69,
        "rent": 1000,
        "insurance": 150,
        "living": 1800,
        "blocked_account": 0,
        "total_yearly_note": "~22,000 CHF/yr (INCREDIBLE value — tuition is ~1500 CHF/yr)",
        "notes": "ETH = #1 in continental Europe for ML/AI. Extremely low tuition. High living costs but affordable vs quality.",
    },
    {
        "country": "Switzerland",
        "city": "Lausanne",
        "university": "EPFL",
        "tuition": 730,
        "tuition_currency": "CHF",
        "semester_fee": 69,
        "rent": 900,
        "insurance": 150,
        "living": 1700,
        "blocked_account": 0,
        "total_yearly_note": "~20,500 CHF/yr (incredible value)",
        "notes": "EPFL = top 20 globally. Low tuition. Strong ML/AI. Swiss Government Scholarships available.",
    },
    {
        "country": "Switzerland",
        "city": "Geneva",
        "university": "University of Geneva",
        "tuition": 500,
        "tuition_currency": "CHF",
        "semester_fee": 65,
        "rent": 1000,
        "insurance": 150,
        "living": 1700,
        "blocked_account": 0,
        "total_yearly_note": "~19,500 CHF/yr (very low tuition)",
        "notes": "Lowest tuition in Switzerland. Strong Stats program. Swiss Government Scholarship target.",
    },
    # Singapore
    {
        "country": "Singapore",
        "city": "Singapore",
        "university": "NUS, NTU, SMU",
        "tuition": 10000,
        "tuition_currency": "SGD",
        "semester_fee": 300,
        "rent": 800,
        "insurance": 100,
        "living": 1500,
        "blocked_account": 0,
        "total_yearly_note": "~$37,000 SGD/yr (SINGA covers full tuition + $2k/mo stipend)",
        "notes": "SINGA scholarship = full-ride target. NUS/NTU top 20 globally. Low taxes, safe city.",
    },
    {
        "country": "Singapore",
        "city": "Singapore (NTU)",
        "university": "Nanyang Technological University",
        "tuition": 9000,
        "tuition_currency": "SGD",
        "semester_fee": 300,
        "rent": 700,
        "insurance": 100,
        "living": 1400,
        "blocked_account": 0,
        "total_yearly_note": "~$34,000 SGD/yr (SINGA eligible)",
        "notes": "NTU AI/Data Science programs. SINGA covers everything. ASEAN scholarships also available.",
    },
    # Australia
    {
        "country": "Australia",
        "city": "Melbourne",
        "university": "University of Melbourne",
        "tuition": 12000,
        "tuition_currency": "AUD",
        "semester_fee": 500,
        "rent": 900,
        "insurance": 100,
        "living": 1700,
        "blocked_account": 0,
        "total_yearly_note": "~$46,000 AUD/yr (RTP covers $35k/yr + tuition)",
        "notes": "Top Australian university. RTP scholarship = full-ride target. Strong ML research.",
    },
    {
        "country": "Australia",
        "city": "Sydney",
        "university": "University of Sydney, UNSW",
        "tuition": 12000,
        "tuition_currency": "AUD",
        "semester_fee": 500,
        "rent": 1000,
        "insurance": 100,
        "living": 1800,
        "blocked_account": 0,
        "total_yearly_note": "~$48,000 AUD/yr (RTP eligible)",
        "notes": "UNSW has strong AI programs. RTP covers tuition + $35k/yr stipend. Higher living costs.",
    },
    {
        "country": "Australia",
        "city": "Canberra",
        "university": "Australian National University (ANU)",
        "tuition": 11000,
        "tuition_currency": "AUD",
        "semester_fee": 500,
        "rent": 800,
        "insurance": 100,
        "living": 1500,
        "blocked_account": 0,
        "total_yearly_note": "~$41,000 AUD/yr (RTP eligible)",
        "notes": "ANU = top research university. Lower living costs than Sydney/Melbourne. RTP target.",
    },
]


class CostComparison:
    def __init__(self, profile, sheets_client=None, data_dir=None):
        self.profile = profile
        self.sheets = sheets_client

    def show(self):
        countries = sorted(set(c["country"] for c in CITY_COSTS))
        print(f"\n=== COST COMPARISON ({' / '.join(countries)}) ===")
        print(f"  Based on: Single student budget (non-EU/non-US)")
        print()

        for country in countries:
            entries = [c for c in CITY_COSTS if c["country"] == country]
            if not entries:
                continue
            curr = entries[0]["tuition_currency"]
            symbol = {"EUR": "€", "USD": "$", "GBP": "£", "CAD": "$", "CHF": "CHF", "SGD": "$", "AUD": "$"}.get(curr, curr)
            print(f"  === {country.upper()} ({curr}/year) ===")
            print(f"  {'City':<20} {'Tuition/sem':<16} {'Rent':<10} {'Living/mo':<12} {'Total/yr':<20}")
            print(f"  {'-'*76}")
            for c in sorted(entries, key=lambda x: x["living"]):
                tuition_str = "FREE" if c["tuition"] == 0 else f"{symbol}{c['tuition']}/sem"
                total_raw = c["tuition"] * 2 + c["semester_fee"] * 2 + c["living"] * 12
                total_str = f"{symbol}{total_raw:,}"
                print(f"  {c['city']:<20} {tuition_str:<16} {symbol}{c['rent']:<8} {symbol}{c['living']:<9} {total_str:<12} {curr}")
            print()

        print("  === SCHOLARSHIP COVERAGE ===")
        print(f"  • DAAD (€11,208/yr): Covers living at most German cities")
        print(f"  • Erasmus Mundus (~€16,800/yr): Fully covered + savings possible")
        print(f"  • Fulbright (~$50k/yr): Full tuition + living for US programs")
        print(f"  • Chevening (~£25k+/yr): Full tuition + living for UK programs")
        print(f"  • Commonwealth (~£25k+/yr): Full tuition + living for UK programs")
        print(f"  • Vanier ($50k CAD/yr): Full funding for Canadian programs")
        print(f"  • SINGA ($2k+/mo stipend): Full tuition + living for Singapore")
        print(f"  • RTP ($35k AUD/yr + tuition): Full funding for Australia")
        print(f"  • Swiss Government (~CHF 20k/yr): Covers living at low-tuition Swiss unis")
        print()

        return CITY_COSTS
