from agents.base import BaseAgent
from datetime import datetime
import random
import time

HEADERS = [
    "Country",
    "Scholarship Name",
    "Provider",
    "Coverage Type",
    "Coverage Details",
    "Amount (per year)",
    "Currency",
    "Degree Level",
    "Target Fields",
    "Eligibility (Nationality)",
    "Eligibility (Academics)",
    "Eligibility (Experience)",
    "Required Documents",
    "Application Fee",
    "Language of Application",
    "English Test Required",
    "GRE/GMAT Required",
    "Deadline Start",
    "Deadline End",
    "Duration",
    "Interview Required",
    "Success Rate / Competitiveness",
    "Application Portal",
    "Notification Date",
    "Official URL",
    "Match Score",
    "Strategy Notes",
    "Last Updated",
]

CORE_SCHOLARSHIPS = [
    {
        "country": "Germany",
        "name": "DAAD Development-Related Postgraduate Scholarship",
        "provider": "DAAD (German Academic Exchange Service)",
        "coverage_type": "Full-Ride",
        "coverage": "Tuition + 934 EUR/month living + health insurance + travel allowance + rent subsidy + family allowance",
        "amount": "11,208",
        "currency": "EUR",
        "degree": "MSc",
        "fields": "All fields incl. ML, AI, Data Science, Statistics (development-related)",
        "nationality": "Developing countries (Bangladesh eligible)",
        "academics": "Bachelor's degree (2.5+ German grade = ~3.0+ US GPA); less than 6 years since graduation",
        "experience": "2+ years professional experience strongly recommended",
        "documents": "DAAD application form; CV (Europass); Motivation letter; Research proposal (max 5 pages); Letters of recommendation (2); Academic transcripts; Language certificates; Work certificates",
        "fee": "None",
        "lang_app": "English or German",
        "english_test": "TOEFL or IELTS (score varies by program)",
        "gre": "Not required",
        "deadline_start": "June",
        "deadline_end": "August/September (varies by country)",
        "duration": "12-36 months",
        "interview": "Possible (for some programs)",
        "competition": "Very competitive (~10-15% acceptance rate)",
        "portal": "https://www.daad.de/en/study-and-research-in-germany/scholarships/",
        "notification": "~3-5 months after deadline",
        "url": "https://www.daad.de/en/study-and-research-in-germany/scholarships/",
        "match": 95,
        "strategy": "PRIMARY TARGET. Apply through DAAD portal. Strong motivation letter + research proposal critical. Highlight Statistics + ML interest.",
    },
    {
        "country": "Multi (Europe)",
        "name": "Erasmus Mundus Joint Masters (EMJM)",
        "provider": "European Commission",
        "coverage_type": "Full-Ride",
        "coverage": "Full tuition + 1,400 EUR/month living + travel (3,000-4,000 EUR) + installation (1,000 EUR) + health insurance",
        "amount": "16,800 + full tuition",
        "currency": "EUR",
        "degree": "MSc",
        "fields": "Multiple programs incl. Data Science, AI, ML, Statistics (check catalogue)",
        "nationality": "All international (including Bangladesh); no prior Erasmus scholarship",
        "academics": "Bachelor's degree (strong academic record); less than 12 months living in program country",
        "experience": "Not required (fresh graduates eligible)",
        "documents": "Online application; Motivation letter; CV; Letters of recommendation; Academic transcripts; English proficiency; Research proposal (varies by program)",
        "fee": "None (application fee varies by program: 0-90 EUR)",
        "lang_app": "English",
        "english_test": "TOEFL 80+ / IELTS 6.5+ (varies by program)",
        "gre": "Not required (some programs may ask)",
        "deadline_start": "October",
        "deadline_end": "February (varies by program; some earlier)",
        "duration": "12-24 months (study at 2+ European universities)",
        "interview": "Possible (for shortlisted candidates)",
        "competition": "Very competitive (~5-10% acceptance rate for top programs)",
        "portal": "https://erasmus-plus.ec.europa.eu/opportunities/opportunities-for-individuals/students/erasmus-mundus-joint-masters",
        "notification": "March-April",
        "url": "https://erasmus-plus.ec.europa.eu/opportunities/opportunities-for-individuals/students/erasmus-mundus-joint-masters",
        "match": 98,
        "strategy": "PRIMARY TARGET. Find 3 EMJM programs in Data Science/AI. Apply before Feb. Study at 2+ European universities = amazing experience.",
    },
    {
        "country": "Germany",
        "name": "Heinrich Boll Foundation Scholarship",
        "provider": "Heinrich Boll Foundation (Green party affiliated)",
        "coverage_type": "Partial to Full",
        "coverage": "934 EUR/month + health insurance + tuition (if applicable) + research cost allowance + family allowance",
        "amount": "11,208 + tuition",
        "currency": "EUR",
        "degree": "MSc",
        "fields": "All fields (preference: ecology, sustainability, democracy, human rights)",
        "nationality": "International students (incl. Bangladesh); enrolled at German university",
        "academics": "Excellent academic record (top 20% of class)",
        "experience": "Social/environmental engagement highly valued",
        "documents": "Online application; CV; Motivation letter; Academic records; Letters of recommendation; Proof of social engagement; Interview",
        "fee": "None",
        "lang_app": "English or German",
        "english_test": "Depends on program language",
        "gre": "Not required",
        "deadline_start": "March 1",
        "deadline_end": "September 1",
        "duration": "Standard study period (up to 24 months for MSc)",
        "interview": "Yes (for shortlisted candidates)",
        "competition": "Competitive (~10-15%)",
        "portal": "https://www.boell.de/en/scholarships",
        "notification": "~2-3 months after deadline",
        "url": "https://www.boell.de/en/scholarships",
        "match": 70,
        "strategy": "GOOD FIT. Your Volunteer for Bangladesh work supports the social engagement requirement. Apply to both deadlines.",
    },
    {
        "country": "Germany",
        "name": "KAAD Scholarship for Developing Countries",
        "provider": "Catholic Academic Exchange Service (KAAD)",
        "coverage_type": "Partial to Full",
        "coverage": "934 EUR/month + health insurance + travel + tuition + family allowance",
        "amount": "11,208 + tuition",
        "currency": "EUR",
        "degree": "MSc/PhD",
        "fields": "All fields",
        "nationality": "Developing countries (Bangladesh specifically eligible); Catholic connection helpful but not mandatory",
        "academics": "Bachelor's/Master's with above-average grades",
        "experience": "2+ years professional experience preferred",
        "documents": "Application form; CV; Academic records; Letters of recommendation; Language cert; Research plan",
        "fee": "None",
        "lang_app": "English or German",
        "english_test": "TOEFL or IELTS (varies)",
        "gre": "Not required",
        "deadline_start": "January",
        "deadline_end": "June 30 (for following academic year; applications accepted year-round)",
        "duration": "Standard study period",
        "interview": "Yes (in person or video)",
        "competition": "Moderate (less competitive than DAAD)",
        "portal": "https://www.kaad.de/",
        "notification": "~2-3 months after application",
        "url": "https://www.kaad.de/",
        "match": 78,
        "strategy": "GOOD FIT. Bangladesh is a target country. Requires personal interview. Prepare social/community involvement stories.",
    },
    {
        "country": "Germany",
        "name": "Konrad Adenauer Foundation Scholarship",
        "provider": "Konrad Adenauer Foundation (CDU affiliated)",
        "coverage_type": "Partial to Full",
        "coverage": "934 EUR/month + health insurance + family allowance + tuition support",
        "amount": "11,208",
        "currency": "EUR",
        "degree": "MSc",
        "fields": "All fields",
        "nationality": "International students (incl. Bangladesh); enrolled at German university",
        "academics": "Above-average academic record",
        "experience": "Political/social engagement; alignment with Christian Democratic values",
        "documents": "Application; CV; Motivation letter; Academic records; Letters of recommendation; Interview",
        "fee": "None",
        "lang_app": "German or English (German preferred)",
        "english_test": "Depends on program",
        "gre": "Not required",
        "deadline_start": "January 15",
        "deadline_end": "July 15",
        "duration": "Standard study period",
        "interview": "Yes",
        "competition": "Competitive",
        "portal": "https://www.kas.de/en/scholarships",
        "notification": "~2-3 months",
        "url": "https://www.kas.de/en/scholarships",
        "match": 65,
        "strategy": "CONSIDER. Political engagement focus. Your Math Olympiad + Volunteer work may help offset.",
    },
    {
        "country": "Germany",
        "name": "Friedrich Ebert Foundation Scholarship",
        "provider": "Friedrich Ebert Foundation (SPD affiliated)",
        "coverage_type": "Partial to Full",
        "coverage": "934 EUR/month + health insurance + family allowance",
        "amount": "11,208",
        "currency": "EUR",
        "degree": "MSc",
        "fields": "All fields",
        "nationality": "International students (incl. Bangladesh); enrolled at German university",
        "academics": "Above-average academic record",
        "experience": "Social/political engagement; solidarity with social democracy values",
        "documents": "Application; CV; Motivation letter; Academic records; References; Interview",
        "fee": "None",
        "lang_app": "German or English",
        "english_test": "Depends on program",
        "gre": "Not required",
        "deadline_start": "January",
        "deadline_end": "May 31 (for upcoming winter semester; international applicants)",
        "duration": "Standard study period",
        "interview": "Yes",
        "competition": "Competitive",
        "portal": "https://www.fes.de/en/studienwerk/scholarships/",
        "notification": "~2-3 months",
        "url": "https://www.fes.de/en/studienwerk/scholarships/",
        "match": 62,
        "strategy": "CONSIDER. Social justice focus. Your Social Business idea could be relevant.",
    },
    {
        "country": "Germany",
        "name": "Deutschlandstipendium (Germany Scholarship)",
        "provider": "German Government (via universities)",
        "coverage_type": "Partial",
        "coverage": "300 EUR/month (half from private sponsors, half from government)",
        "amount": "3,600",
        "currency": "EUR",
        "degree": "BSc/MSc",
        "fields": "All fields",
        "nationality": "International students enrolled at German university",
        "academics": "Outstanding academic achievement; extracurricular/social engagement",
        "experience": "Not required",
        "documents": "Application per university; Academic records; CV; Motivation letter; Proof of engagement",
        "fee": "None",
        "lang_app": "German or English (university dependent)",
        "english_test": "Depends on program",
        "gre": "Not required",
        "deadline_start": "August (per university)",
        "deadline_end": "October (per university)",
        "duration": "Minimum 2 semesters, renewable up to graduation",
        "interview": "Sometimes",
        "competition": "Moderate (good supplement scholarship)",
        "portal": "https://www.deutschlandstipendium.de/",
        "notification": "~1 month after application",
        "url": "https://www.deutschlandstipendium.de/",
        "match": 60,
        "strategy": "APPLY AFTER ADMISSION. Needs enrollment at German university first. Good supplemental funding.",
    },
    {
        "country": "USA",
        "name": "Fulbright Foreign Student Program (Bangladesh)",
        "provider": "US Department of State",
        "coverage_type": "Full-Ride",
        "coverage": "Full tuition + living stipend + health insurance + airfare + books + professional development",
        "amount": "40,000-60,000",
        "currency": "USD",
        "degree": "MSc/PhD",
        "fields": "All fields incl. ML, AI, Data Science, Statistics",
        "nationality": "Bangladeshi citizens only; reside in Bangladesh; return to Bangladesh after program",
        "academics": "Strong academic record (GPA 3.0+/4.0); Bachelor's degree completed",
        "experience": "Leadership potential; community involvement; clear career goals for Bangladesh",
        "documents": "Online application; TOEFL/IELTS; GRE (recommended); SOP; CV; Letters of recommendation (3); Research proposal; Interview",
        "fee": "None (application fee waived for Fulbright)",
        "lang_app": "English",
        "english_test": "TOEFL 90+ / IELTS 6.5+ (higher for competitive programs)",
        "gre": "Strongly recommended (most US universities require)",
        "deadline_start": "February",
        "deadline_end": "May (varies; check US Embassy Dhaka)",
        "duration": "12-36 months",
        "interview": "Yes (with US Embassy committee)",
        "competition": "Very competitive (Bangladesh: ~20-30 grants/year)",
        "portal": "https://bd.usembassy.gov/education/fulbright/",
        "notification": "~4-6 months after deadline",
        "url": "https://bd.usembassy.gov/education/fulbright/",
        "match": 92,
        "strategy": "USA #1 TARGET. Bangladesh-specific Fulbright program. Your Stats background + Bangladesh citizenship = eligible. Apply through US Embassy Dhaka.",
    },
    {
        "country": "USA",
        "name": "US Graduate Assistantships (TA/RA) — University-Specific",
        "provider": "Individual US Universities",
        "coverage_type": "Full-Ride (via assistantship)",
        "coverage": "Full tuition waiver + monthly stipend ($1,500-2,500) + health insurance per university",
        "amount": "30,000-60,000",
        "currency": "USD",
        "degree": "MSc/PhD",
        "fields": "ML, AI, Data Science, Statistics, CS",
        "nationality": "All international students (admitted to program)",
        "academics": "Strong academic record; department approval",
        "experience": "Teaching/research potential; relevant skills",
        "documents": "University application; SOP; CV; Recommendations; Proof of English; Sometimes separate TA/RA application",
        "fee": "Application fee: $50-150 per university (waivers sometimes available)",
        "lang_app": "English",
        "english_test": "TOEFL 95+/IELTS 7.0+",
        "gre": "Required by most universities (aim for 320+ overall, 165+ quant)",
        "deadline_start": "October",
        "deadline_end": "February (varies by university; Fall intake)",
        "duration": "1-2 years (renewable based on performance)",
        "interview": "Sometimes (department dependent)",
        "competition": "Varies by university (Georgia Tech more attainable than MIT)",
        "portal": "https://www.gatech.edu/academics/graduate",
        "notification": "March-April",
        "url": "https://grad.ucla.edu/funding/",
        "match": 75,
        "strategy": "BACKUP PLAN: Research assistantships at public R1 universities. Georgia Tech ML (@gt_computing), UCLA CS (@UCLA_CSD), UW CSE (@uwcse), UIUC CS (@cs_illinois) all fund MSCS students through TA/RA. Apply directly to their MSc programs and indicate interest in funding.",
    },
    {
        "country": "USA",
        "name": "Knight-Hennessy Scholars (Stanford)",
        "provider": "Stanford University",
        "coverage_type": "Full-Ride",
        "coverage": "Full tuition + living stipend ($~45,000) + travel + books + academic expenses",
        "amount": "90,000+",
        "currency": "USD",
        "degree": "MSc/PhD",
        "fields": "All fields at Stanford University",
        "nationality": "All international (including Bangladesh)",
        "academics": "Admitted to Stanford graduate program; exceptional academic record",
        "experience": "Leadership potential; independent thinking; civic orientation",
        "documents": "Knight-Hennessy application + Stanford program application; SOP; CV; Video essay; Letters of recommendation; Transcripts",
        "fee": "Stanford application fee: $125",
        "lang_app": "English",
        "english_test": "TOEFL 100+ / IELTS 7.0+",
        "gre": "Required by most Stanford programs",
        "deadline_start": "October 1",
        "deadline_end": "October 12 (KH), December (Stanford programs)",
        "duration": "Up to 3 years",
        "interview": "Yes (finalists invited to Stanford)",
        "competition": "Extremely competitive (~3-4% acceptance rate)",
        "portal": "https://knight-hennessy.stanford.edu/",
        "notification": "April",
        "url": "https://knight-hennessy.stanford.edu/",
        "match": 70,
        "strategy": "REACH. Only if you apply to Stanford. Leadership-heavy selection. Prepare video essay + leadership stories. Low probability but life-changing if awarded.",
    },
    {
        "country": "UK",
        "name": "Chevening Scholarships",
        "provider": "Foreign, Commonwealth & Development Office (FCDO)",
        "coverage_type": "Full-Ride",
        "coverage": "Full tuition fees + monthly stipend + round-trip flights + visa cost + arrival/departure allowance",
        "amount": "20,000+ tuition",
        "currency": "GBP",
        "degree": "MSc",
        "fields": "All fields including AI, ML, Deep Learning, and Data Science",
        "nationality": "Chevening-eligible countries (Bangladesh included)",
        "academics": "Upper second-class 2:1 honours degree or equivalent (typically GPA 3.0+/4.0)",
        "experience": "Minimum 2 years of work experience (equivalent to 2,800 hours of professional work)",
        "documents": "Four essays (Leadership, Networking, Study in UK, Career plans); 2 reference letters; university offers",
        "fee": "None for scholarship; varies by UK university application",
        "lang_app": "English",
        "english_test": "Determined by host university (typically IELTS 6.5+ / TOEFL 90+)",
        "gre": "Not required",
        "deadline_start": "August",
        "deadline_end": "November 3",
        "duration": "12 months (1-year taught masters)",
        "interview": "Yes (interviews conducted at British High Commission)",
        "competition": "Highly competitive (~2-3% selection rate)",
        "portal": "https://www.chevening.org/apply/",
        "notification": "June (following year)",
        "url": "https://www.chevening.org/",
        "match": 85,
        "strategy": "PRIMARY TARGET. Work experience requirement is met. Tailor essays to show leadership and networking potential. Select top CS programs (Oxford, UCL, Edinburgh, Imperial).",
    },
    {
        "country": "UK",
        "name": "Commonwealth Masters Scholarships",
        "provider": "Commonwealth Scholarship Commission (CSC)",
        "coverage_type": "Full-Ride",
        "coverage": "Full tuition fees + monthly stipend (£1,347 / £1,652 in London) + round-trip flights + warm clothing allowance",
        "amount": "25,000+ tuition",
        "currency": "GBP",
        "degree": "MSc",
        "fields": "Science and technology for development (includes AI, ML, DL, CS)",
        "nationality": "Eligible Commonwealth countries (Bangladesh included)",
        "academics": "First class degree or upper second class (2:1) bachelor's degree",
        "experience": "Not strictly required; fresh graduates eligible",
        "documents": "References; university admission offers; academic transcripts; development impact statement",
        "fee": "None",
        "lang_app": "English",
        "english_test": "Determined by host university",
        "gre": "Not required",
        "deadline_start": "September",
        "deadline_end": "December",
        "duration": "12 months",
        "interview": "None (selection based on written application)",
        "competition": "Very competitive (~5% selection rate)",
        "portal": "https://cscuk.fcdo.gov.uk/scholarships/commonwealth-masters-scholarships/",
        "notification": "July (following year)",
        "url": "https://cscuk.fcdo.gov.uk/",
        "match": 82,
        "strategy": "STRONG RECOMMENDATION. Very generous scholarship. Focus heavily on how study in UK will help Bangladesh's technological advancement.",
    },
    {
        "country": "Canada",
        "name": "Vanier Canada Graduate Scholarships",
        "provider": "Government of Canada",
        "coverage_type": "Full-Ride",
        "coverage": "Stipend of $50,000 CAD per year (covers tuition + living costs)",
        "amount": "50,000",
        "currency": "CAD",
        "degree": "PhD",
        "fields": "Computer Science, AI, Machine Learning, Data Science, Statistics, Mathematics",
        "nationality": "Canadian and international students",
        "academics": "First-class average (e.g. GPA 3.7+/4.0) in each of the last two years of full-time study",
        "experience": "Strong research potential, academic excellence, and demonstrated leadership skills",
        "documents": "Nomination by university; Research proposal; CCV (Canadian Common CV); 2 reference letters; transcripts",
        "fee": "None for scholarship; university app fee applies",
        "lang_app": "English or French",
        "english_test": "Determined by host university (typically IELTS 7.0+ / TOEFL 100+)",
        "gre": "Varies by university (recommended for CS/ML)",
        "deadline_start": "July",
        "deadline_end": "November 1",
        "duration": "36 months (3 years)",
        "interview": "None",
        "competition": "Extremely competitive (international research elite)",
        "portal": "https://vanier.gc.ca/en/home-accueil.html",
        "notification": "April (following year)",
        "url": "https://vanier.gc.ca/",
        "match": 60,
        "strategy": "REACH. Must be nominated by a Canadian university (e.g. Toronto, Montreal, UBC). Secure a supervisor and apply early. Very high research focus.",
    },
    {
        "country": "Switzerland",
        "name": "Swiss Government Excellence Scholarships",
        "provider": "Swiss Confederation (FCS)",
        "coverage_type": "Full-Ride",
        "coverage": "Tuition waiver (usually) + monthly stipend of 1,920 CHF + health insurance + airfare",
        "amount": "23,040",
        "currency": "CHF",
        "degree": "PhD",
        "fields": "All fields of research (outstanding fit for CS/ML/DL at ETH Zurich or EPFL)",
        "nationality": "International students from selected countries (Bangladesh included)",
        "academics": "Excellent Master's degree or equivalent academic credentials",
        "experience": "Research background and peer-reviewed publications are highly preferred",
        "documents": "Scholarship application form; CV; Research proposal (max 5 pages); 2 recommendation letters; supervisor support letter",
        "fee": "None",
        "lang_app": "English, German, French, or Italian",
        "english_test": "IELTS 7.0+ or TOEFL 100+ (for English-taught PhDs)",
        "gre": "Highly recommended for ETH Zurich/EPFL",
        "deadline_start": "August",
        "deadline_end": "November",
        "duration": "12 to 36 months",
        "interview": "None (selection based on dossier)",
        "competition": "Extremely competitive (~5% acceptance)",
        "portal": "https://www.sbfi.admin.ch/sbfi/en/home/education/scholarships-and-grants/swiss-government-excellence-scholarships.html",
        "notification": "May (following year)",
        "url": "https://www.sbfi.admin.ch/sbfi/en/home/education/scholarships-and-grants/swiss-government-excellence-scholarships.html",
        "match": 68,
        "strategy": "STRONG OPPORTUNITY. You MUST contact and secure a host professor at ETH Zurich, EPFL, or Uni Zurich first. If they agree to supervise you, your chance of winning is high.",
    },
    {
        "country": "Singapore",
        "name": "Singapore International Graduate Award (SINGA)",
        "provider": "A*STAR, NUS, NTU, SUTD",
        "coverage_type": "Full-Ride",
        "coverage": "Full tuition fees + monthly stipend (SGD 2,700, increases to SGD 3,200 after qualifying exam) + airfare (SGD 1,500) + settling-in allowance (SGD 1,000)",
        "amount": "32,400 - 38,400",
        "currency": "SGD",
        "degree": "PhD",
        "fields": "Computer and Information Sciences (AI, ML, Deep Learning, Data Science)",
        "nationality": "All international graduates with passion for research",
        "academics": "Excellent bachelor's or master's degree results",
        "experience": "Strong research interest and prior project work (papers or thesis)",
        "documents": "Transcripts; Recommendation letters (2); Research proposal / interests; Passport",
        "fee": "None",
        "lang_app": "English",
        "english_test": "Optional but recommended if instruction was not in English",
        "gre": "Optional but recommended for NTU/NUS CS applications",
        "deadline_start": "June (for January intake) / December (for August intake)",
        "deadline_end": "June 1 (Jan intake) / December 1 (Aug intake)",
        "duration": "Up to 4 years",
        "interview": "Yes (technical interview with panel)",
        "competition": "Very competitive (~5% selection)",
        "portal": "https://www.a-star.edu.sg/Scholarships/for-graduate-studies/singapore-international-graduate-award-singa",
        "notification": "3 months after deadline",
        "url": "https://www.a-star.edu.sg/",
        "match": 80,
        "strategy": "HIGH VALUE. Singapore is a world leader in AI. NTU and NUS are top 15 globally. Apply before December for the August intake. Focus on research interests.",
    },
    {
        "country": "Australia",
        "name": "Australian Government Research Training Program (RTP)",
        "provider": "Australian Government / Host Universities",
        "coverage_type": "Full-Ride",
        "coverage": "Tuition fee offset + living allowance (stipend ~$35,000 AUD per year) + Overseas Student Health Cover (OSHC) + relocation allowance",
        "amount": "35,000",
        "currency": "AUD",
        "degree": "MSc (Research) / PhD",
        "fields": "All research fields (strong fit for Data Science & Machine Learning)",
        "nationality": "International students",
        "academics": "Outstanding academic record, equivalent to H1 (First Class Honours, GPA 3.7+/4.0)",
        "experience": "Prior research experience, thesis, or peer-reviewed publications",
        "documents": "Direct application to host university; CV; Research proposal; Referee reports; Supervisor agreement",
        "fee": "None",
        "lang_app": "English",
        "english_test": "IELTS 6.5+ / TOEFL 90+ (required)",
        "gre": "Not required",
        "deadline_start": "April",
        "deadline_end": "August/September (varies by university)",
        "duration": "2 years (MSc Research) / 3-4 years (PhD)",
        "interview": "None",
        "competition": "Highly competitive",
        "portal": "Varies by host university portal (e.g. University of Melbourne, University of Sydney)",
        "notification": "October-November",
        "url": "https://www.education.gov.au/research-block-grants/research-training-program",
        "match": 75,
        "strategy": "GREAT FIT. Seek out research supervisors at Melbourne, Sydney, ANU, or UNSW. Publications are heavily weighted in Australian admissions.",
    },
    {
        "country": "France",
        "name": "Eiffel Excellence Scholarship",
        "provider": "French Ministry for Europe and Foreign Affairs",
        "coverage_type": "Full-Ride",
        "coverage": "€1,031/month living + international airfare + housing allowance + health insurance + cultural activities",
        "amount": "12,372",
        "currency": "EUR",
        "degree": "MSc",
        "fields": "ML, AI, Data Science, Statistics, Engineering, Sciences",
        "nationality": "International non-French students (Bangladesh eligible)",
        "academics": "Bachelor's degree with strong academic record",
        "experience": "Not required (fresh graduates eligible)",
        "documents": "Application through French university; CV; Academic transcripts; Motivation letter; Letters of recommendation; Research proposal; Language certificates",
        "fee": "None (varies by university)",
        "lang_app": "English or French",
        "english_test": "TOEFL or IELTS (varies by program)",
        "gre": "Not required",
        "deadline_start": "January",
        "deadline_end": "January (single deadline per year)",
        "duration": "12-24 months",
        "interview": "Possible (for shortlisted candidates)",
        "competition": "Very competitive (~10-15% acceptance)",
        "portal": "https://www.campusfrance.org/en/the-eiffel-scholarship-program",
        "notification": "April",
        "url": "https://www.campusfrance.org/en/the-eiffel-scholarship-program",
        "match": 82,
        "strategy": "PRIMARY TARGET. France's most prestigious scholarship for international students. Covers full living costs at low-tuition French universities (€200-3,000/yr tuition). Apply through French universities (Paris-Saclay, Sorbonne, IP Paris). Deadline: January.",
    },
    {
        "country": "France",
        "name": "French Government Scholarship (BGF)",
        "provider": "Campus France",
        "coverage_type": "Partial to Full",
        "coverage": "Tuition waiver + monthly stipend €700-1,000 + health insurance",
        "amount": "8,400-12,000",
        "currency": "EUR",
        "degree": "MSc",
        "fields": "ML, AI, Data Science, Statistics, All fields",
        "nationality": "International students (Bangladesh eligible via French Embassy)",
        "academics": "Bachelor's degree; strong academic record",
        "experience": "Varies by program",
        "documents": "Application via local French Embassy; CV; Transcripts; Motivation letter; Recommendation letters; Language certificates",
        "fee": "None",
        "lang_app": "English or French",
        "english_test": "TOEFL or IELTS (varies)",
        "gre": "Not required",
        "deadline_start": "March",
        "deadline_end": "May (varies by embassy)",
        "duration": "12-24 months",
        "interview": "Possible",
        "competition": "Moderate to competitive",
        "portal": "https://www.campusfrance.org/en/french-government-scholarships",
        "notification": "~2-3 months after deadline",
        "url": "https://www.campusfrance.org/en/french-government-scholarships",
        "match": 75,
        "strategy": "GOOD FIT. Campus France manages scholarships via local French Embassy in Bangladesh. Apply through Campus France Bangladesh.",
    },
    {
        "country": "Italy",
        "name": "Italian Government Scholarships (MAECI)",
        "provider": "Italian Ministry of Foreign Affairs",
        "coverage_type": "Full-Ride",
        "coverage": "€900/month stipend + health insurance + tuition fee waiver",
        "amount": "10,800",
        "currency": "EUR",
        "degree": "MSc",
        "fields": "ML, AI, Data Science, Statistics, Engineering, All fields",
        "nationality": "International students (Bangladesh eligible)",
        "academics": "Bachelor's degree; strong academic record",
        "experience": "Not required (fresh graduates eligible)",
        "documents": "Online application; CV; Academic transcripts; Motivation letter; Letters of recommendation; Language certificates; Research proposal (if required)",
        "fee": "None",
        "lang_app": "English or Italian",
        "english_test": "TOEFL or IELTS (varies by program)",
        "gre": "Not required",
        "deadline_start": "March",
        "deadline_end": "April (each year)",
        "duration": "6-12 months (renewable)",
        "interview": "Possible",
        "competition": "Competitive",
        "portal": "https://www.esteri.it/en/opportunita/borse-di-studio/",
        "notification": "~3 months after deadline",
        "url": "https://www.esteri.it/en/opportunita/borse-di-studio/",
        "match": 80,
        "strategy": "PRIMARY TARGET. Fully funded. Study at Politecnico di Milano, Bologna, Trento in English. ML/AI programs available. Deadline: March-April each year.",
    },
    {
        "country": "Italy",
        "name": "EDISU / DSU Regional Scholarships",
        "provider": "Regional authorities (varies by university)",
        "coverage_type": "Partial to Full",
        "coverage": "Tuition waiver based on income + stipend €5,000-7,000/yr + free housing + meals",
        "amount": "5,000-7,000 + tuition waiver",
        "currency": "EUR",
        "degree": "MSc",
        "fields": "All fields",
        "nationality": "All students enrolled at Italian public universities",
        "academics": "Enrolled at Italian public university; income-based eligibility",
        "experience": "Not required",
        "documents": "Income declaration (ISEE equivalent); University enrollment; Academic records; Residency documents",
        "fee": "None",
        "lang_app": "Italian or English (university dependent)",
        "english_test": "Depends on program",
        "gre": "Not required",
        "deadline_start": "July",
        "deadline_end": "October (varies by region)",
        "duration": "1 academic year (renewable)",
        "interview": "None",
        "competition": "Income-based (not competitive; need-based)",
        "portal": "Varies by university/region (e.g. EDISU Piemonte, DSU Toscana)",
        "notification": "~2 months after application",
        "url": "https://www.edisu.it/",
        "match": 72,
        "strategy": "GOOD FIT. Income-based scholarship for all students at Italian public universities. If family income is below threshold, tuition is waived + get living stipend.",
    },
    {
        "country": "Austria",
        "name": "OeAD Scholarships",
        "provider": "OeAD (Austrian Agency for International Education)",
        "coverage_type": "Partial to Full",
        "coverage": "€1,050/month stipend + health insurance + travel allowance",
        "amount": "12,600",
        "currency": "EUR",
        "degree": "MSc",
        "fields": "ML, AI, Data Science, Statistics, All fields",
        "nationality": "International students (Bangladesh eligible)",
        "academics": "Bachelor's degree with above-average grades",
        "experience": "Not required for all programs",
        "documents": "Online application; CV; Motivation letter; Academic transcripts; Letters of recommendation; Language certificates",
        "fee": "None",
        "lang_app": "English or German",
        "english_test": "TOEFL or IELTS (varies by program)",
        "gre": "Not required",
        "deadline_start": "March",
        "deadline_end": "September (varies by program)",
        "duration": "4-10 months (renewable)",
        "interview": "Possible",
        "competition": "Moderate to competitive",
        "portal": "https://oead.at/en/",
        "notification": "~2-3 months after deadline",
        "url": "https://oead.at/en/",
        "match": 78,
        "strategy": "STRONG OPPORTUNITY. Low tuition Austria (~€750/semester). TU Wien has strong Data Science programs. Apply through OeAD scholarship database.",
    },
    {
        "country": "Belgium",
        "name": "ARES Scholarships",
        "provider": "ARES (Académie de Recherche et d'Enseignement Supérieur)",
        "coverage_type": "Full-Ride",
        "coverage": "€1,150/month stipend + tuition fees + travel + insurance + visa",
        "amount": "13,800 + full tuition",
        "currency": "EUR",
        "degree": "MSc",
        "fields": "ML, AI, Data Science, Statistics, Development-related fields",
        "nationality": "Developing countries (Bangladesh eligible)",
        "academics": "Bachelor's degree; strong academic record; less than 10 years since graduation",
        "experience": "2+ years professional experience preferred",
        "documents": "Online application; CV; Motivation letter; Academic transcripts; Letters of recommendation; Detailed study plan",
        "fee": "None",
        "lang_app": "French (most programs)",
        "english_test": "Depends on program language",
        "gre": "Not required",
        "deadline_start": "February",
        "deadline_end": "February (single deadline per year)",
        "duration": "12-24 months",
        "interview": "Possible",
        "competition": "Competitive",
        "portal": "https://www.ares-ac.be/en/scholarships",
        "notification": "May-June",
        "url": "https://www.ares-ac.be/en/scholarships",
        "match": 76,
        "strategy": "GOOD FIT. For students from developing countries (Bangladesh eligible). Covers full costs. French-speaking universities (ULB, ULiège). Deadline: February.",
    },
    {
        "country": "Belgium",
        "name": "VLIR-UOS Scholarships",
        "provider": "VLIR-UOS (Flemish universities)",
        "coverage_type": "Full-Ride",
        "coverage": "€1,165/month stipend + tuition + travel + insurance + housing",
        "amount": "13,980 + full tuition",
        "currency": "EUR",
        "degree": "MSc",
        "fields": "Data Science, AI, Statistics, Development-related fields",
        "nationality": "Developing countries (Bangladesh eligible)",
        "academics": "Bachelor's degree; strong academic record",
        "experience": "2+ years professional experience preferred",
        "documents": "Online application; CV; Motivation letter; Academic transcripts; Letters of recommendation; Language certificates",
        "fee": "None",
        "lang_app": "English",
        "english_test": "TOEFL or IELTS (varies by program)",
        "gre": "Not required",
        "deadline_start": "February",
        "deadline_end": "February (single deadline per year)",
        "duration": "12-24 months",
        "interview": "Possible",
        "competition": "Competitive",
        "portal": "https://www.vliruos.be/en/scholarships/",
        "notification": "May-June",
        "url": "https://www.vliruos.be/en/scholarships/",
        "match": 74,
        "strategy": "GOOD FIT. For students from developing countries. English-taught programs at Flemish universities (KU Leuven, UGent, UAntwerp). Deadline: February.",
    },
    {
        "country": "Belgium",
        "name": "Master Mind Scholarships",
        "provider": "Government of Flanders",
        "coverage_type": "Partial",
        "coverage": "€10,000 tuition fee reduction + accommodation assistance",
        "amount": "10,000",
        "currency": "EUR",
        "degree": "MSc",
        "fields": "ML, AI, Data Science, Statistics, All fields",
        "nationality": "International non-EEA students (check if Bangladesh eligible)",
        "academics": "Bachelor's degree with strong academic record (top tier)",
        "experience": "Not required",
        "documents": "University application; Motivation letter; CV; Academic transcripts; Letters of recommendation; Language certificates",
        "fee": "Varies by university",
        "lang_app": "English",
        "english_test": "TOEFL or IELTS (varies by program)",
        "gre": "Not required",
        "deadline_start": "February",
        "deadline_end": "April (varies by university)",
        "duration": "1-2 years",
        "interview": "Possible",
        "competition": "Moderate to competitive",
        "portal": "https://www.studyinflanders.be/en/scholarships/master-mind/",
        "notification": "~2 months after deadline",
        "url": "https://www.studyinflanders.be/en/scholarships/master-mind/",
        "match": 70,
        "strategy": "CONSIDER. Significant tuition reduction at KU Leuven, UAntwerp, UHasselt. Combined with low Belgian tuition, very affordable.",
    },
    {
        "country": "Norway",
        "name": "Norwegian Quota Scheme / Free Tuition at Public Universities",
        "provider": "Norwegian Government (HK-dir / Sammen)",
        "coverage_type": "Full-Ride",
        "coverage": "Free tuition at all public universities (NTNU, UiO, UiB, UiT) + NOK 13,000-15,000/month living through part-time work/TA",
        "amount": "156,000-180,000",
        "currency": "NOK",
        "degree": "MSc",
        "fields": "ML, AI, Data Science, Statistics, CS, Engineering",
        "nationality": "International students (all nationalities eligible for free tuition)",
        "academics": "Bachelor's degree with strong academic record (GPA 3.0+/4.0 equivalent)",
        "experience": "Not required",
        "documents": "University application; CV; Transcripts; Motivation letter; Recommendation letters; Language certificates",
        "fee": "None (free tuition at all public universities in Norway)",
        "lang_app": "English",
        "english_test": "TOEFL 90+ / IELTS 6.5+",
        "gre": "Not required",
        "deadline_start": "December 1",
        "deadline_end": "March 1 (NTNU) / varies by university",
        "duration": "2 years",
        "interview": "None",
        "competition": "Moderate to competitive",
        "portal": "https://www.ntnu.edu/studies/masters",
        "notification": "March-April",
        "url": "https://www.sikkerhverdag.no/en/",
        "match": 78,
        "strategy": "STRONG OPPORTUNITY. Norway charges zero tuition at all public universities for ALL international students — even outside the Quota Scheme. NTNU MSc in CS/AI and UiO MSc in Data Science are strong fits. Living costs ~NOK 14,000/month (Oslo) to ~NOK 11,000/month (Trondheim). Fund through part-time work (20 hrs/week allowed).",
    },
    {
        "country": "Netherlands",
        "name": "Holland Scholarship",
        "provider": "Dutch Ministry of Education",
        "coverage_type": "Partial",
        "coverage": "€5,000 first year tuition reduction",
        "amount": "5,000",
        "currency": "EUR",
        "degree": "MSc",
        "fields": "ML, AI, Data Science, Statistics, All fields",
        "nationality": "Non-EEA international students (Bangladesh eligible)",
        "academics": "Bachelor's degree; admitted to participating Dutch university",
        "experience": "Not required",
        "documents": "University application; Motivation letter; CV; Academic transcripts; Language certificates",
        "fee": "University application fee (varies)",
        "lang_app": "English",
        "english_test": "TOEFL 90+ / IELTS 6.5+",
        "gre": "Not required",
        "deadline_start": "February",
        "deadline_end": "May (varies by university)",
        "duration": "1 year (one-time payment)",
        "interview": "None",
        "competition": "Moderate",
        "portal": "https://www.studyinholland.nl/scholarships/holland-scholarship",
        "notification": "~2 months after deadline",
        "url": "https://www.studyinholland.nl/scholarships/holland-scholarship",
        "match": 68,
        "strategy": "CONSIDER. One-time scholarship for non-EU students at Dutch universities. TU Delft and UvA have world-class AI programs.",
    },
    {
        "country": "Netherlands",
        "name": "Orange Tulip Scholarship (OTS)",
        "provider": "Nuffic Neso",
        "coverage_type": "Partial to Full",
        "coverage": "Tuition reduction €5,000-15,000 or full tuition (varies by participating university)",
        "amount": "5,000-15,000",
        "currency": "EUR",
        "degree": "MSc",
        "fields": "ML, AI, Data Science, Statistics, All fields",
        "nationality": "Specific eligible countries (check if Bangladesh included)",
        "academics": "Bachelor's degree; strong academic record",
        "experience": "Not required",
        "documents": "University application; Motivation letter; CV; Academic transcripts; Letters of recommendation; Language certificates",
        "fee": "University application fee (varies)",
        "lang_app": "English",
        "english_test": "TOEFL 90+ / IELTS 6.5+",
        "gre": "Not required",
        "deadline_start": "February",
        "deadline_end": "May (varies by university)",
        "duration": "1-2 years",
        "interview": "Possible",
        "competition": "Moderate",
        "portal": "https://www.studyinholland.nl/scholarships/orange-tulip-scholarship-programme",
        "notification": "~2 months after deadline",
        "url": "https://www.studyinholland.nl/scholarships/orange-tulip-scholarship-programme",
        "match": 65,
        "strategy": "CONSIDER. Check if Bangladesh is eligible for OTS. Can significantly reduce Dutch tuition at participating universities (TU Delft, UvA, Erasmus).",
    },
    {
        "country": "Sweden",
        "name": "Swedish Institute Scholarships for Global Professionals (SISGP)",
        "provider": "Swedish Institute",
        "coverage_type": "Full-Ride",
        "coverage": "SEK 12,000/month living + full tuition + travel grant + insurance",
        "amount": "144,000 + full tuition",
        "currency": "SEK",
        "degree": "MSc",
        "fields": "ML, AI, Data Science, Statistics, All fields",
        "nationality": "International students from eligible countries (Bangladesh eligible)",
        "academics": "Bachelor's degree; strong academic record; admitted to eligible Swedish master's program",
        "experience": "Work experience preferred but not required",
        "documents": "SI application form; CV; Motivation letter; Letters of recommendation; Academic transcripts; Proof of admission",
        "fee": "None",
        "lang_app": "English",
        "english_test": "TOEFL 90+ / IELTS 6.5+",
        "gre": "Not required",
        "deadline_start": "February",
        "deadline_end": "February (single deadline per year)",
        "duration": "1-2 years",
        "interview": "Possible",
        "competition": "Very competitive",
        "portal": "https://si.se/en/apply/scholarships/swedish-institute-scholarships-for-global-professionals/",
        "notification": "April",
        "url": "https://si.se/en/apply/scholarships/swedish-institute-scholarships-for-global-professionals/",
        "match": 80,
        "strategy": "PRIMARY TARGET. Covers full costs at Swedish universities. KTH MSc ML is a top program. Apply through Swedish Institute. Deadline: February.",
    },
    {
        "country": "Denmark",
        "name": "Danish Government Scholarships (at DTU, KU, AU)",
        "provider": "Danish Ministry of Higher Education",
        "coverage_type": "Partial to Full",
        "coverage": "Full or partial tuition waiver + monthly stipend ~DKK 6,000-7,000",
        "amount": "72,000-84,000 + tuition waiver",
        "currency": "DKK",
        "degree": "MSc",
        "fields": "ML, AI, Data Science, Statistics, Engineering",
        "nationality": "Non-EEA international students (Bangladesh eligible)",
        "academics": "Bachelor's degree; strong academic record",
        "experience": "Not required",
        "documents": "University application; CV; Motivation letter; Academic transcripts; Letters of recommendation; Language certificates",
        "fee": "University application fee (varies)",
        "lang_app": "English",
        "english_test": "TOEFL 88+ / IELTS 6.5+",
        "gre": "Not required",
        "deadline_start": "January",
        "deadline_end": "March (varies by university; Fall intake)",
        "duration": "2 years",
        "interview": "Possible",
        "competition": "Competitive",
        "portal": "https://diku.dk/english/",
        "notification": "March-May",
        "url": "https://www.dtu.dk/english/education/msc",
        "match": 72,
        "strategy": "GOOD FIT. DTU MSc in Data Science (@DTUtweet) and KU MSc in Computer Science (@KU_SCIENCE) offer Danish Government Scholarships for non-EEA students. Each university administers its own quota. Apply directly to the university by March 1 (DTU) / January 15 (KU).",
    },
    {
        "country": "Finland",
        "name": "Finland Scholarship",
        "provider": "Finnish Government (via universities)",
        "coverage_type": "Partial to Full",
        "coverage": "€5,000 tuition waiver first year + €5,000 relocation grant",
        "amount": "10,000",
        "currency": "EUR",
        "degree": "MSc",
        "fields": "ML, AI, Data Science, Statistics, Engineering, All fields",
        "nationality": "Non-EEA international students (Bangladesh eligible)",
        "academics": "Bachelor's degree; strong academic record",
        "experience": "Not required",
        "documents": "University application; CV; Motivation letter; Academic transcripts; Letters of recommendation; Language certificates",
        "fee": "University application fee (varies)",
        "lang_app": "English",
        "english_test": "TOEFL 92+ / IELTS 6.5+",
        "gre": "Not required",
        "deadline_start": "January",
        "deadline_end": "March (varies by university)",
        "duration": "2 years",
        "interview": "Possible",
        "competition": "Competitive",
        "portal": "https://www.studyinfinland.fi/scholarships",
        "notification": "March-April",
        "url": "https://www.studyinfinland.fi/scholarships",
        "match": 65,
        "strategy": "CONSIDER. Aalto University has top ML programs. First-year tuition waiver + relocation support. Subsequent years need partial funding.",
    },
    {
        "country": "China",
        "name": "CSC Scholarship (Chinese Government Scholarship)",
        "provider": "China Scholarship Council",
        "coverage_type": "Full-Ride",
        "coverage": "Free tuition + accommodation + monthly stipend CNY 3,000 + health insurance",
        "amount": "36,000 + full tuition",
        "currency": "CNY",
        "degree": "MSc",
        "fields": "ML, AI, Data Science, Statistics, Engineering, All fields",
        "nationality": "International students (Bangladesh eligible)",
        "academics": "Bachelor's degree; strong academic record; under 35 years",
        "experience": "Not required",
        "documents": "Application form; CV; Academic transcripts; Study plan; Letters of recommendation; Language certificates; Physical exam form",
        "fee": "None",
        "lang_app": "English or Chinese",
        "english_test": "TOEFL or IELTS (for English-taught programs)",
        "gre": "Not required",
        "deadline_start": "January",
        "deadline_end": "April (varies; apply through Chinese Embassy in Dhaka)",
        "duration": "2-3 years",
        "interview": "Possible",
        "competition": "Competitive",
        "portal": "https://www.campuschina.org/",
        "notification": "June-August",
        "url": "https://www.campuschina.org/",
        "match": 75,
        "strategy": "STRONG OPPORTUNITY. Fully funded at Tsinghua, PKU, Zhejiang. World-class ML/AI programs. English-taught MSc available. Apply through Chinese Embassy in Dhaka.",
    },
    {
        "country": "Japan",
        "name": "MEXT (Ministry of Education) Scholarship",
        "provider": "Japanese Government (MEXT)",
        "coverage_type": "Full-Ride",
        "coverage": "Free tuition + JPY 144,000/month + travel + no application fee",
        "amount": "1,728,000 + full tuition",
        "currency": "JPY",
        "degree": "MSc",
        "fields": "ML, AI, Data Science, Statistics, Engineering, All fields",
        "nationality": "International students (Bangladesh eligible via Embassy recommendation)",
        "academics": "Bachelor's degree; strong academic record; under 35 years",
        "experience": "Not required",
        "documents": "Application form; CV; Academic transcripts; Research plan; Letters of recommendation; Language certificates; Photo",
        "fee": "None",
        "lang_app": "English or Japanese",
        "english_test": "TOEFL or IELTS (for English-taught programs)",
        "gre": "Not required",
        "deadline_start": "April",
        "deadline_end": "May (varies; Embassy recommendation route)",
        "duration": "2 years",
        "interview": "Yes (document screening + interview)",
        "competition": "Very competitive",
        "portal": "https://www.mext.go.jp/en/",
        "notification": "~6 months after application",
        "url": "https://www.mext.go.jp/en/",
        "match": 78,
        "strategy": "STRONG OPPORTUNITY. Fully funded at University of Tokyo, Kyoto, Tokyo Tech. Research-focused. Embassy recommendation route for Bangladesh.",
    },
]

DISCOVERY_QUERIES = {
    "Germany": [
        "DAAD scholarship 2026 MSc machine learning data science Germany deadline",
        "Erasmus Mundus joint masters artificial intelligence data science 2026 2027",
        "fully funded scholarship Germany MSc international students 2026 English",
        "German government scholarship developing countries MSc 2026",
        "scholarship Bangladeshi students Germany MSc 2026",
        "Deutschlandstipendium international students 2026",
        "Bayer foundation scholarship Germany MSc 2026",
    ],
    "USA": [
        "Fulbright scholarship Bangladeshi students USA 2026 2027 deadline",
        "fully funded masters USA data science machine learning international students 2026",
        "TA RA graduate assistantship masters computer science USA international 2026",
        "scholarship international masters students USA statistics data science 2026",
        "Knight Hennessy scholarship Stanford 2026 international deadline",
    ],
    "Canada": [
        "Vanier Graduate Scholarship computer science machine learning Canada 2026",
        "fully funded masters computer science artificial intelligence Canada 2026",
        "MSc data science scholarship Canada international students 2026",
    ],
    "UK": [
        "Chevening scholarship machine learning data science UK 2026 deadline",
        "Commonwealth scholarship computer science masters UK fully funded 2026",
        "fully funded artificial intelligence MSc Oxford Cambridge UCL scholarship",
    ],
    "Switzerland": [
        "Swiss Government Excellence Scholarship MSc PhD computer science 2026",
        "ETH Zurich MSc computer science scholarship international students 2026",
        "EPFL masters scholarship artificial intelligence machine learning 2026",
    ],
    "Singapore": [
        "SINGA scholarship Singapore PhD MSc artificial intelligence machine learning 2026",
        "NUS research scholarship computer science data science 2026",
        "NTU fully funded master scholarship artificial intelligence Singapore",
    ],
    "Australia": [
        "RTP scholarship Australia international masters data science 2026",
        "fully funded master machine learning artificial intelligence Australia 2026",
    ]
}


CURATED_SCHOLARSHIP_SITES = [
    ("site:daad.de scholarship MSc 2026 international", "DAAD"),
    ("site:daad.de \"fully funded\" scholarship developing countries", "DAAD"),
    ("site:daad.de postgraduate scholarship 2026", "DAAD"),
    ("site:erasmus-plus.ec.europa.eu \"Erasmus Mundus\" masters 2026", "Erasmus Mundus"),
    ("site:erasmusmundus.com scholarship 2026", "Erasmus Mundus"),
    ("site:eacea.ec.europa.eu erasmus mundus call application", "Erasmus Mundus"),
    ("site:scholarshipportal.com scholarship MSc 2026 international", "ScholarshipPortal"),
    ("site:scholarshipportal.com \"fully funded\" masters scholarship", "ScholarshipPortal"),
    ("site:globalscholarships.com scholarship masters 2026", "Global Scholarships"),
    ("site:globalscholarships.com \"fully funded\" 2026 deadline", "Global Scholarships"),
    ("site:profellow.com fellowship masters 2026 international", "ProFellow"),
    ("site:profellow.com \"fully funded\" graduate fellowship 2026", "ProFellow"),
    ("site:opportunitiescircle.com scholarship 2026 deadline", "Opportunities Circle"),
    ("site:opportunitiescircle.com \"fully funded\" masters 2026", "Opportunities Circle"),
    ("site:youthop.com scholarship 2026 international", "Youth Opportunities"),
    ("site:youthop.com \"fully funded\" masters deadline 2026", "Youth Opportunities"),
    ("site:scholars4dev.com scholarship 2026 deadline", "Scholars4Dev"),
    ("site:scholars4dev.com \"fully funded\" masters 2026", "Scholars4Dev"),
    ("site:studyinkorea.go.kr GKS scholarship 2026 undergraduate graduate", "GKS"),
    ("site:gks.go.kr \"Global Korea Scholarship\" 2026", "GKS"),
    ("site:studyinkorea.go.kr \"Korean Government\" scholarship 2026", "GKS"),
    ("site:mext.go.jp scholarship 2026 international student", "MEXT"),
    ("site:studyinjapan.go.jp MEXT scholarship 2026", "MEXT"),
    ("site:mext.go.jp \"Japanese Government\" scholarship application", "MEXT"),
    ("site:opportunitiesforyouth.org scholarship masters 2026 fully funded", "Youth Opportunities"),
    ("site:afterschoolafrica.com scholarship 2026 masters", "AfterSchoolAfrica"),
    ("site:scholarah.com fully funded scholarship 2026 masters", "ScholarAh"),
    ("site:funding4s.com scholarship 2026 masters international", "Funding4s"),
    ("site:gov.br CAPES scholarship 2026 masters international", "CAPES"),
    ("site:conacyt.mx scholarship 2026 masters international", "CONACYT"),
    ("site:topuniversities.com scholarship 2026 masters international", "TopUni"),
    ("site:mastersportal.com scholarship 2026 deadline", "MastersPortal"),
    ("site:findamasters.com scholarship 2026 international", "FindAMasters"),
    ("site:daad.de \"postgraduate\" \"development\" scholarship 2026 2027", "DAAD"),
    ("site:erasmus-plus.ec.europa.eu masters scholarship 2027", "Erasmus+"),
    ("site:chevening.org apply scholarship 2027 bangladesh", "Chevening"),
    ("site:commonwealthscholarships.org application 2027 bangladesh", "Commonwealth"),
    ("site:scholarshipscorner.website scholarship 2026 2027 masters", "ScholarshipsCorner"),
    ("site:universityscholarships.org scholarship 2026 masters international", "UniScholarships"),
    ("site:scholarship-positions.com \"fully funded\" masters 2026", "ScholarshipPositions"),
    ("site:studyinsweden.se scholarship 2026 masters international", "StudyInSweden"),
    ("site:studiare-in-italia.it \"Italian Government\" scholarship 2026", "StudyInItaly"),
    ("site:campusfrance.org \"Eiffel\" scholarship 2026", "CampusFrance"),
]


class ScholarshipAgent(BaseAgent):
    def __init__(self, sheets_client=None, interactive=True):
        super().__init__("ScholarshipAgent", sheets_client, interactive)

    def _add_scholarship(self, scholarships, country, title, url, snippet, provider):
        from agents.target import DEADLINE_RE
        deadline = "Check website"
        if snippet:
            m = DEADLINE_RE.search(snippet)
            if m:
                deadline = (m.group(1) or m.group(2) or "").strip()
        scholarships.append({
            "country": country,
            "name": title,
            "provider": provider,
            "coverage_type": "Check website",
            "coverage": snippet[:200] if snippet else "Check link",
            "amount": "Check website",
            "currency": "Check",
            "degree": "MSc/PhD",
            "fields": "ML, AI, Data Science, Statistics (verify)",
            "nationality": "Check eligibility",
            "academics": "Check requirements",
            "experience": "Check requirements",
            "documents": "Check link for details",
            "fee": "Unknown",
            "lang_app": "English (likely)",
            "english_test": "Likely required",
            "gre": "Varies",
            "deadline_start": deadline,
            "deadline_end": deadline,
            "duration": "Check website",
            "interview": "Unknown",
            "competition": "Unknown",
            "portal": url,
            "notification": "Check website",
            "url": url,
            "match": 50,
            "strategy": "Auto-discovered. Verify details on website before applying.",
        })
        self.log(f"    Added: {title[:60]}...")

    def scrape_curated_scholarship_sites(self):
        self.log(f"Scraping 10 curated scholarship websites for live opportunities...")
        results = []
        seen_urls = set()
        for query, source in CURATED_SCHOLARSHIP_SITES:
            try:
                hits = self.search_web(query, num_results=6)
            except Exception:
                hits = []
            for r in hits:
                url = r.get("url", "")
                if url and url not in seen_urls:
                    seen_urls.add(url)
                    results.append(r)
            self.log(f"  {source}: {len(hits)} results")
            time.sleep(0.15)
        self.log(f"  Total unique leads from 10 curated sites: {len(results)}")
        return results

    def run(self, country_filter=None):
        print("\n=== SCHOLARSHIP RESEARCH AGENT ===")
        print("Target: Global CS/AI Universities | Full-ride | ML/AI/Data Science/Statistics")

        if not self.ask_user("Start scholarship research? (Will scrape live websites + search)"):
            print("Skipped.")
            return []

        self.log("Loading core scholarship database...")
        scholarships = [s for s in CORE_SCHOLARSHIPS
                       if not country_filter or s["country"].lower() == country_filter.lower()]

        # ── Country-based web discovery ──
        self.log("Searching live scholarship data from multiple sources...")
        self.log("Targeting: DAAD, Erasmus Mundus, Fulbright, Chevening, Vanier, RTP, SINGA...")

        targets = list(DISCOVERY_QUERIES.keys()) if not country_filter else [country_filter]
        for country in targets:
            queries = DISCOVERY_QUERIES.get(country, [])
            if queries:
                queries = random.sample(queries, min(1, len(queries)))
            results = self.multi_search(queries, max_per_query=4)
            self.log(f"  Found {len(results)} new leads for {country}")

            for r in results:
                title = r.get("title", "")
                url = r.get("url", "")
                snippet = r.get("snippet", "")
                if not title or not url:
                    continue
                if any(kw in title.lower() for kw in ["scholarship", "fellowship", "funding", "grant", "financial aid", "daad", "erasmus", "fulbright"]):
                    self._add_scholarship(scholarships, country, title, url, snippet, "Web Discovery")

        # ── 10 curated scholarship website search (always runs) ──
        self.log("Scraping 10 dedicated scholarship portals for live opportunities...")
        curated_results = self.scrape_curated_scholarship_sites()
        for r in curated_results:
            title = r.get("title", "")
            url = r.get("url", "")
            snippet = r.get("snippet", "")
            if not title or not url:
                continue
            country = "Multiple"
            url_lower = url.lower()
            if "daad" in url_lower or "germany" in url_lower:
                country = "Germany"
            elif "erasmus" in url_lower or "europa" in url_lower:
                country = "Multi (Europe)"
            elif "korea" in url_lower or "gks" in url_lower:
                country = "South Korea"
            elif "mext" in url_lower or "japan" in url_lower:
                country = "Japan"
            self._add_scholarship(scholarships, country, title, url, snippet, "Curated Portal")

        headers = HEADERS
        KEY_MAP = {
            "Country": "country",
            "Scholarship Name": "name",
            "Provider": "provider",
            "Coverage Type": "coverage_type",
            "Coverage Details": "coverage",
            "Amount (per year)": "amount",
            "Currency": "currency",
            "Degree Level": "degree",
            "Target Fields": "fields",
            "Eligibility (Nationality)": "nationality",
            "Eligibility (Academics)": "academics",
            "Eligibility (Experience)": "experience",
            "Required Documents": "documents",
            "Application Fee": "fee",
            "Language of Application": "lang_app",
            "English Test Required": "english_test",
            "GRE/GMAT Required": "gre",
            "Deadline Start": "deadline_start",
            "Deadline End": "deadline_end",
            "Duration": "duration",
            "Interview Required": "interview",
            "Success Rate / Competitiveness": "competition",
            "Application Portal": "portal",
            "Notification Date": "notification",
            "Official URL": "url",
            "Match Score": "match",
            "Strategy Notes": "strategy",
            "Last Updated": None,
        }
        rows = []
        seen = set()
        for s in scholarships:
            key = s["name"].lower()[:60]
            if key in seen:
                continue
            seen.add(key)
            row = self.make_row(s, headers, KEY_MAP)
            rows.append(row)

        self.log(f"Total scholarships collected: {len(rows)}")

        if self.ask_user(f"Save {len(rows)} scholarships to storage?"):
            self.save_to_sheets("Scholarships", headers, rows)

        top = [s for s in scholarships if s.get("match", 0) and s["match"] >= 80]
        if top:
            print(f"\n  TOP RECOMMENDATIONS (match >= 80%):")
            for s in sorted(top, key=lambda x: x["match"], reverse=True):
                print(f"    [{s['match']}%] {s['name']} ({s['country']})")
            print(f"\n  Strategy: Germany #1 (DAAD + Erasmus = 0 tuition + full funding)")
            print(f"  USA #2 (Fulbright = full funding, TA/RA = tuition waiver)")

        return scholarships
