from agents.base import BaseAgent
import random

HEADERS = [
    "Country",
    "University Name",
    "Location",
    "University Type",
    "QS World Ranking 2025",
    "THE World Ranking 2025",
    "Program Name",
    "Degree",
    "Field / Specialization",
    "Teaching Language",
    "Tuition (per semester)",
    "Currency",
    "Semester Fee / Contribution",
    "Application Fee",
    "Application Deadline (Winter)",
    "Application Deadline (Summer)",
    "Admission Requirements",
    "English Test Requirement",
    "GRE/GMAT Required",
    "Minimum GPA Required",
    "Program Duration (semesters)",
    "ECTS Credits",
    "Scholarship Availability",
    "Application Portal / Platform",
    "Department / Faculty URL",
    "Research Strengths",
    "Student Population",
    "International Student %",
    "Cost of Living (monthly EUR/USD)",
    "Strategy Notes",
    "Last Updated",
]

GERMAN_UNIVERSITIES = [
    {
        "country": "Germany",
        "name": "Technical University of Munich (TUM)",
        "location": "Munich, Bavaria",
        "type": "TU9 / Technical University",
        "qs_rank": "28",
        "the_rank": "26",
        "program": "MSc Data Science",
        "degree": "MSc",
        "field": "Data Science, ML, AI, Statistics",
        "language": "English",
        "tuition": "0",
        "currency": "EUR",
        "semester_fee": "152",
        "app_fee": "75 (uni-assist)",
        "deadline_winter": "May 31",
        "deadline_summer": "November 30",
        "requirements": "Bachelor's in CS/Stats/Math/related; CV; SOP; Letters of recommendation; Transcripts; GRE recommended",
        "english": "TOEFL 88 / IELTS 6.5",
        "gre": "Recommended (not mandatory)",
        "min_gpa": "2.5 German (approx 3.0 US)",
        "duration": "4 semesters",
        "ects": "120",
        "scholarships": "DAAD, Deutschlandstipendium, TUM scholarship",
        "portal": "https://www.tum.de/en/studies/degree-programs",
        "dept_url": "https://www.in.tum.de/en/",
        "research": "AI, Computer Vision (Cremers), Graph ML (Gunnemann), 3D Vision (Niessner)",
        "students": "~50,000",
        "intl_pct": "~35%",
        "living_cost": "1,200 EUR",
        "strategy": "TOP CHOICE. Apply by May 31 for Winter. GRE helps. Data Science program is world-class.",
    },
    {
        "country": "Germany",
        "name": "Technical University of Munich (TUM)",
        "location": "Munich, Bavaria",
        "type": "TU9 / Technical University",
        "qs_rank": "28",
        "the_rank": "26",
        "program": "MSc Informatics (AI/ML track)",
        "degree": "MSc",
        "field": "Computer Science, AI, ML",
        "language": "English",
        "tuition": "0",
        "currency": "EUR",
        "semester_fee": "152",
        "app_fee": "75 (uni-assist)",
        "deadline_winter": "May 31",
        "deadline_summer": "November 30",
        "requirements": "Bachelor's in CS/related; GRE recommended; CV; SOP; Letters of recommendation; Transcripts",
        "english": "TOEFL 88 / IELTS 6.5",
        "gre": "Recommended",
        "min_gpa": "2.5 German",
        "duration": "4 semesters",
        "ects": "120",
        "scholarships": "DAAD, Deutschlandstipendium",
        "portal": "https://www.tum.de/en/studies/degree-programs",
        "dept_url": "https://www.in.tum.de/en/",
        "research": "AI/ML research groups: Prof. Cremers (Vision), Gunnemann (Graph ML), Niessner (3D)",
        "students": "~50,000",
        "intl_pct": "~35%",
        "living_cost": "1,200 EUR",
        "strategy": "TOP CHOICE. AI/ML track at Germany's #1 university. Research-fit with multiple ML professors.",
    },
    {
        "country": "Germany",
        "name": "LMU Munich",
        "location": "Munich, Bavaria",
        "type": "Research University (Elite)",
        "qs_rank": "54",
        "the_rank": "33",
        "program": "MSc Statistics (Data Science track)",
        "degree": "MSc",
        "field": "Statistics, Data Science",
        "language": "English",
        "tuition": "0",
        "currency": "EUR",
        "semester_fee": "150",
        "app_fee": "None (direct application)",
        "deadline_winter": "July 15",
        "deadline_summer": "January 15",
        "requirements": "Bachelor's in Statistics/Math; strong quantitative background; CV; Academic records",
        "english": "TOEFL 80 / IELTS 6.0",
        "gre": "Not required",
        "min_gpa": "2.5 German (approx 3.0 US)",
        "duration": "4 semesters",
        "ects": "120",
        "scholarships": "DAAD, Deutschlandstipendium",
        "portal": "https://www.lmu.de/en/study/degree-programs/",
        "dept_url": "https://www.statistik.uni-muenchen.de/",
        "research": "Statistical Learning, Computational Statistics, Data Science Education",
        "students": "~52,000",
        "intl_pct": "~17%",
        "living_cost": "1,200 EUR",
        "strategy": "NATURAL FIT. Your Statistics background is a perfect match. Prof. Christian Heumann is the contact.",
    },
    {
        "country": "Germany",
        "name": "RWTH Aachen University",
        "location": "Aachen, NRW",
        "type": "TU9 / Technical University",
        "qs_rank": "99",
        "the_rank": "108",
        "program": "MSc Data Science",
        "degree": "MSc",
        "field": "Data Science",
        "language": "English",
        "tuition": "0",
        "currency": "EUR",
        "semester_fee": "300",
        "app_fee": "None (direct via RWTH portal)",
        "deadline_winter": "July 15",
        "deadline_summer": "January 15",
        "requirements": "Bachelor's (GPA 2.5+); CV; SOP; Academic records; Language certificate",
        "english": "TOEFL 90 / IELTS 6.5",
        "gre": "Not required",
        "min_gpa": "2.5 German",
        "duration": "4 semesters",
        "ects": "120",
        "scholarships": "DAAD, RWTH scholarships",
        "portal": "https://www.rwth-aachen.de/go/id/a/?lidx=1",
        "dept_url": "https://www.cs.rwth-aachen.de/",
        "research": "Computer Vision (Leibe), Data Science, ML Engineering",
        "students": "~47,000",
        "intl_pct": "~25%",
        "living_cost": "900 EUR",
        "strategy": "STRONG CHOICE. TU9 member. Good Data Science program. Lower living cost than Munich.",
    },
    {
        "country": "Germany",
        "name": "University of Goettingen",
        "location": "Goettingen, Lower Saxony",
        "type": "Research University",
        "qs_rank": "178",
        "the_rank": "119",
        "program": "MSc Applied Statistics",
        "degree": "MSc",
        "field": "Statistics, Data Science",
        "language": "English",
        "tuition": "0",
        "currency": "EUR",
        "semester_fee": "400",
        "app_fee": "None",
        "deadline_winter": "April 15 - July 15",
        "deadline_summer": "None (winter only)",
        "requirements": "Bachelor's in Statistics/Math; strong quantitative background; CV; Academic records",
        "english": "TOEFL 90 / IELTS 6.5",
        "gre": "Not required",
        "min_gpa": "No strict cutoff (competitive)",
        "duration": "4 semesters",
        "ects": "120",
        "scholarships": "DAAD",
        "portal": "https://www.uni-goettingen.de/en/",
        "dept_url": "https://www.uni-goettingen.de/en/statistics/",
        "research": "Applied Statistics, Biostatistics, Statistical Consulting",
        "students": "~31,000",
        "intl_pct": "~13%",
        "living_cost": "800 EUR",
        "strategy": "NATURAL FIT. One of the best Statistics programs in Germany. Very affordable living costs.",
    },
    {
        "country": "Germany",
        "name": "TU Berlin",
        "location": "Berlin",
        "type": "TU9 / Technical University",
        "qs_rank": "140",
        "the_rank": "136",
        "program": "MSc Computer Science (ML/AI track)",
        "degree": "MSc",
        "field": "CS, ML, AI",
        "language": "English",
        "tuition": "0",
        "currency": "EUR",
        "semester_fee": "330",
        "app_fee": "None (direct via TU Berlin portal)",
        "deadline_winter": "May 15 - June 15",
        "deadline_summer": "November 15 - December 15",
        "requirements": "Bachelor's in CS; CV; Motivation letter; Academic records",
        "english": "TOEFL 87 / IELTS 6.5",
        "gre": "Not required",
        "min_gpa": "2.5 German (approx 3.0 US)",
        "duration": "4 semesters",
        "ects": "120",
        "scholarships": "DAAD, Deutschlandstipendium",
        "portal": "https://www.tu.berlin/en/studies/degree-programs/",
        "dept_url": "https://www.ml.tu-berlin.de/",
        "research": "ML (Klaus-Robert Mueller), Brain-Computer Interfaces, Statistical ML (Opper)",
        "students": "~35,000",
        "intl_pct": "~25%",
        "living_cost": "1,000 EUR",
        "strategy": "GOOD CHOICE. Berlin is a tech hub. Strong ML research. Many English programs.",
    },
    {
        "country": "Germany",
        "name": "TU Darmstadt",
        "location": "Darmstadt, Hesse",
        "type": "TU9 / Technical University",
        "qs_rank": "246",
        "the_rank": "251-300",
        "program": "MSc Data Science",
        "degree": "MSc",
        "field": "Data Science",
        "language": "English",
        "tuition": "0",
        "currency": "EUR",
        "semester_fee": "400",
        "app_fee": "None",
        "deadline_winter": "August 31",
        "deadline_summer": "March 15",
        "requirements": "Bachelor's in CS/Stats/Math; CV; Motivation letter",
        "english": "TOEFL 95 / IELTS 7.0",
        "gre": "Not required",
        "min_gpa": "No strict cutoff (competitive)",
        "duration": "4 semesters",
        "ects": "120",
        "scholarships": "DAAD",
        "portal": "https://www.tu-darmstadt.de/studieren/",
        "dept_url": "https://www.informatik.tu-darmstadt.de/",
        "research": "Computer Vision (Roth), Probabilistic ML",
        "students": "~25,000",
        "intl_pct": "~20%",
        "living_cost": "900 EUR",
        "strategy": "STRONG CHOICE. One of the best Data Science programs in Germany. Late deadline (Aug 31).",
    },
    {
        "country": "Germany",
        "name": "University of Freiburg",
        "location": "Freiburg, Baden-Wuerttemberg",
        "type": "Research University",
        "qs_rank": "113",
        "the_rank": "128",
        "program": "MSc Data Science / AI",
        "degree": "MSc",
        "field": "Data Science, AI, ML",
        "language": "English",
        "tuition": "1,500",
        "currency": "EUR",
        "semester_fee": "170",
        "app_fee": "None",
        "deadline_winter": "May 15",
        "deadline_summer": "November 15",
        "requirements": "Bachelor's in CS/Math/Stats; CV; Motivation letter; GRE optional",
        "english": "TOEFL 90 / IELTS 6.5",
        "gre": "Optional",
        "min_gpa": "2.5 German",
        "duration": "4 semesters",
        "ects": "120",
        "scholarships": "DAAD",
        "portal": "https://www.uni-freiburg.de/en/studies/",
        "dept_url": "https://www.ml.uni-freiburg.de/",
        "research": "AutoML (Hutter), Bayesian Optimization, Deep Learning",
        "students": "~24,000",
        "intl_pct": "~20%",
        "living_cost": "900 EUR",
        "strategy": "GOOD CHOICE. Prof. Frank Hutter is world-renowned in AutoML. Non-EU tuition: 3,000 EUR/yr.",
    },
    {
        "country": "Germany",
        "name": "University of Bonn",
        "location": "Bonn, NRW",
        "type": "Research University",
        "qs_rank": "121",
        "the_rank": "89",
        "program": "MSc Mathematics (Data Science specialization)",
        "degree": "MSc",
        "field": "Mathematics, Data Science, ML",
        "language": "English",
        "tuition": "0",
        "currency": "EUR",
        "semester_fee": "330",
        "app_fee": "None",
        "deadline_winter": "July 15",
        "deadline_summer": "January 15",
        "requirements": "Bachelor's in Math/Stats/CS; strong math background; CV; Motivation letter",
        "english": "TOEFL 80 / IELTS 6.0",
        "gre": "Not required",
        "min_gpa": "2.5 German",
        "duration": "4 semesters",
        "ects": "120",
        "scholarships": "DAAD",
        "portal": "https://www.uni-bonn.de/en/study",
        "dept_url": "https://www.mathematics.uni-bonn.de/",
        "research": "Hausdorff Center for Mathematics (world-class), Data Science, Statistical Learning",
        "students": "~38,000",
        "intl_pct": "~15%",
        "living_cost": "850 EUR",
        "strategy": "EXCELLENT FIT. Hausdorff Center = world top for math. Good for Statistics background.",
    },
    {
        "country": "Germany",
        "name": "TU Dresden",
        "location": "Dresden, Saxony",
        "type": "TU9 / Technical University",
        "qs_rank": "229",
        "the_rank": "161",
        "program": "MSc Computational Modeling and Simulation (Data Science)",
        "degree": "MSc",
        "field": "Data Science, Computational Science",
        "language": "English",
        "tuition": "0",
        "currency": "EUR",
        "semester_fee": "300",
        "app_fee": "None",
        "deadline_winter": "July 15",
        "deadline_summer": "January 15",
        "requirements": "Bachelor's in related field; CV; Motivation letter",
        "english": "TOEFL 87 / IELTS 6.5",
        "gre": "Not required",
        "min_gpa": "No strict cutoff",
        "duration": "4 semesters",
        "ects": "120",
        "scholarships": "DAAD",
        "portal": "https://tu-dresden.de/studium",
        "dept_url": "https://tu-dresden.de/ing/informatik",
        "research": "Computational Science, Data Science, AI applications",
        "students": "~32,000",
        "intl_pct": "~18%",
        "living_cost": "800 EUR",
        "strategy": "BEST VALUE. Zero tuition + lowest living costs in Germany (800 EUR/month). Good program.",
    },
    {
        "country": "Germany",
        "name": "KIT (Karlsruhe Institute of Technology)",
        "location": "Karlsruhe, Baden-Wuerttemberg",
        "type": "TU9 / Technical University",
        "qs_rank": "119",
        "the_rank": "102",
        "program": "MSc Informatics (ML track)",
        "degree": "MSc",
        "field": "Informatics, ML, AI",
        "language": "English",
        "tuition": "1,500",
        "currency": "EUR",
        "semester_fee": "190",
        "app_fee": "None",
        "deadline_winter": "June 15 - July 15",
        "deadline_summer": "December 15 - January 15",
        "requirements": "Bachelor's in Informatics/CS; CV; Academic records",
        "english": "TOEFL 90 / IELTS 6.5",
        "gre": "Not required",
        "min_gpa": "2.5 German",
        "duration": "4 semesters",
        "ects": "120",
        "scholarships": "DAAD",
        "portal": "https://www.kit.edu/studieren/",
        "dept_url": "https://www.informatik.kit.edu/",
        "research": "ML for Autonomous Systems (Zollner), AI, Robotics",
        "students": "~22,000",
        "intl_pct": "~18%",
        "living_cost": "900 EUR",
        "strategy": "CONSIDER. Non-EU tuition (3,000 EUR/yr). Still much cheaper than US. Strong engineering focus.",
    },
]

USA_UNIVERSITIES = [
    {
        "country": "USA",
        "name": "Stanford University",
        "location": "Stanford, California",
        "type": "Private (Ivy+)",
        "qs_rank": "3",
        "the_rank": "2",
        "program": "MSc Statistics (Data Science track)",
        "degree": "MSc",
        "field": "Statistics, Data Science, ML",
        "language": "English",
        "tuition": "28,000",
        "currency": "USD",
        "semester_fee": "500 (estimated)",
        "app_fee": "125",
        "deadline_winter": "December 3",
        "deadline_summer": "N/A (Fall only)",
        "requirements": "Bachelor's in Stats/Math/CS; GRE; SOP; 3 Letters of recommendation; CV; Transcripts",
        "english": "TOEFL 100 / IELTS 7.0",
        "gre": "Required (aim for 165+ quant)",
        "min_gpa": "No strict cutoff (avg ~3.8/4.0 admitted)",
        "duration": "6 quarters (2 years)",
        "ects": "N/A (US credits: ~45)",
        "scholarships": "Knight-Hennessy, TA/RA, Department funding",
        "portal": "https://www.stanford.edu/",
        "dept_url": "https://statistics.stanford.edu/",
        "research": "Statistical Learning (Hastie, Tibshirani), ML (Ng, Fei-Fei Li)",
        "students": "~17,000",
        "intl_pct": "~22%",
        "living_cost": "2,500 USD",
        "strategy": "TOP REACH. Knight-Hennessy = full funding. Statistics faculty are the best in the world. Natural fit for your background.",
    },
    {
        "country": "USA",
        "name": "Stanford University",
        "location": "Stanford, California",
        "type": "Private (Ivy+)",
        "qs_rank": "3",
        "the_rank": "2",
        "program": "MSc Computer Science (AI/ML specialization)",
        "degree": "MSc",
        "field": "CS, AI, ML",
        "language": "English",
        "tuition": "28,000",
        "currency": "USD",
        "semester_fee": "500 (estimated)",
        "app_fee": "125",
        "deadline_winter": "December 3",
        "deadline_summer": "N/A (Fall only)",
        "requirements": "Bachelor's in CS/related; GRE; SOP; 3 Letters of recommendation; CV",
        "english": "TOEFL 100 / IELTS 7.0",
        "gre": "Required",
        "min_gpa": "No strict cutoff",
        "duration": "4-6 quarters",
        "ects": "N/A",
        "scholarships": "Knight-Hennessy, TA/RA",
        "portal": "https://www.stanford.edu/",
        "dept_url": "https://cs.stanford.edu/",
        "research": "AI, ML, Vision (Fei-Fei Li, Andrew Ng, etc.)",
        "students": "~17,000",
        "intl_pct": "~22%",
        "living_cost": "2,500 USD",
        "strategy": "REACH. Computer Science is very competitive. Consider applying to Statistics instead (higher acceptance).",
    },
    {
        "country": "USA",
        "name": "Carnegie Mellon University (CMU)",
        "location": "Pittsburgh, Pennsylvania",
        "type": "Private",
        "qs_rank": "52",
        "the_rank": "28",
        "program": "MSc Machine Learning",
        "degree": "MSc",
        "field": "Machine Learning, AI",
        "language": "English",
        "tuition": "26,000",
        "currency": "USD",
        "semester_fee": "400 (estimated)",
        "app_fee": "100",
        "deadline_winter": "November 30 (early) / December 15 (regular)",
        "deadline_summer": "N/A (Fall only)",
        "requirements": "Bachelor's in CS/Stats/Math; strong quantitative; GRE; SOP; 3 Recommendations; CV",
        "english": "TOEFL 100 / IELTS 7.0",
        "gre": "Required (quant 168+ recommended)",
        "min_gpa": "No strict cutoff (avg ~3.7+ admitted)",
        "duration": "4 semesters",
        "ects": "N/A",
        "scholarships": "TA/RA, CMU fellowships",
        "portal": "https://www.cmu.edu/",
        "dept_url": "https://www.ml.cmu.edu/",
        "research": "ML (Kolter), Robustness, Optimization, AI Safety",
        "students": "~15,000",
        "intl_pct": "~45%",
        "living_cost": "1,700 USD",
        "strategy": "BEST ML PROGRAM GLOBALLY. Very competitive. TA/RA available. Prof. Zico Kolter is leading AI safety research.",
    },
    {
        "country": "USA",
        "name": "Carnegie Mellon University (CMU)",
        "location": "Pittsburgh, Pennsylvania",
        "type": "Private",
        "qs_rank": "52",
        "the_rank": "28",
        "program": "MSc Data Science / Computational Data Science",
        "degree": "MSc",
        "field": "Data Science, ML",
        "language": "English",
        "tuition": "26,000",
        "currency": "USD",
        "semester_fee": "400 (estimated)",
        "app_fee": "100",
        "deadline_winter": "December 1",
        "deadline_summer": "N/A (Fall only)",
        "requirements": "Bachelor's in CS/Stats/Math; GRE; SOP; Recommendations",
        "english": "TOEFL 100 / IELTS 7.0",
        "gre": "Required",
        "min_gpa": "No strict cutoff",
        "duration": "4 semesters",
        "ects": "N/A",
        "scholarships": "TA/RA",
        "portal": "https://www.cmu.edu/",
        "dept_url": "https://www.datascience.cmu.edu/",
        "research": "Data Science, ML, Statistics (Prof. Aarti Singh)",
        "students": "~15,000",
        "intl_pct": "~45%",
        "living_cost": "1,700 USD",
        "strategy": "TOP CHOICE (US). Data Science at CMU is world-class. Good fit for your Stats background.",
    },
    {
        "country": "USA",
        "name": "University of California, Berkeley",
        "location": "Berkeley, California",
        "type": "Public (Top Public)",
        "qs_rank": "10",
        "the_rank": "8",
        "program": "MA Statistics",
        "degree": "MA",
        "field": "Statistics, Data Science, ML",
        "language": "English",
        "tuition": "12,000",
        "currency": "USD",
        "semester_fee": "800 (estimated)",
        "app_fee": "140",
        "deadline_winter": "January 6",
        "deadline_summer": "N/A (Fall only)",
        "requirements": "Bachelor's in Stats/Math/CS; strong quantitative; GRE; SOP; 3 Recommendations",
        "english": "TOEFL 90 / IELTS 7.0",
        "gre": "Required",
        "min_gpa": "3.0+ (avg ~3.6+ admitted)",
        "duration": "4 semesters",
        "ects": "N/A",
        "scholarships": "TA/RA, Berkeley fellowships",
        "portal": "https://www.berkeley.edu/",
        "dept_url": "https://statistics.berkeley.edu/",
        "research": "Statistical Learning (Michael I. Jordan), Bayes, ML Theory",
        "students": "~45,000",
        "intl_pct": "~17%",
        "living_cost": "2,300 USD",
        "strategy": "EXCELLENT STATS PROGRAM. Home of Prof. Michael Jordan (ML pioneer). Natural fit for Stats background.",
    },
    {
        "country": "USA",
        "name": "Georgia Institute of Technology",
        "location": "Atlanta, Georgia",
        "type": "Public (Top Public)",
        "qs_rank": "97",
        "the_rank": "80",
        "program": "MSc Data Science (Analytics)",
        "degree": "MSc",
        "field": "Data Science, ML, Statistics",
        "language": "English",
        "tuition": "8,000",
        "currency": "USD",
        "semester_fee": "600 (estimated)",
        "app_fee": "85",
        "deadline_winter": "February 1",
        "deadline_summer": "N/A (Fall only)",
        "requirements": "Bachelor's; GRE; SOP; Recommendations; CV",
        "english": "TOEFL 90 / IELTS 6.5",
        "gre": "Required",
        "min_gpa": "3.0+",
        "duration": "4 semesters",
        "ects": "N/A",
        "scholarships": "TA/RA (GRA/GTA positions commonly available)",
        "portal": "https://www.gatech.edu/",
        "dept_url": "https://www.cc.gatech.edu/",
        "research": "ML (Le Song), Data Science, AI",
        "students": "~45,000",
        "intl_pct": "~35%",
        "living_cost": "1,600 USD",
        "strategy": "BEST VALUE USA. Most affordable top US university for data science. Good TA/RA availability.",
    },
    {
        "country": "USA",
        "name": "University of Washington",
        "location": "Seattle, Washington",
        "type": "Public (Top Public)",
        "qs_rank": "63",
        "the_rank": "26",
        "program": "MSc Data Science",
        "degree": "MSc",
        "field": "Data Science, ML, AI",
        "language": "English",
        "tuition": "12,000",
        "currency": "USD",
        "semester_fee": "700 (estimated)",
        "app_fee": "90",
        "deadline_winter": "December 1",
        "deadline_summer": "N/A",
        "requirements": "Bachelor's in CS/Stats; GRE; SOP; Recommendations; CV",
        "english": "TOEFL 92 / IELTS 7.0",
        "gre": "Required",
        "min_gpa": "3.0+",
        "duration": "4 semesters",
        "ects": "N/A",
        "scholarships": "TA/RA, UW fellowships",
        "portal": "https://www.washington.edu/",
        "dept_url": "https://www.datascience.washington.edu/",
        "research": "ML (Emily Fox - Bayesian), Data Science, AI",
        "students": "~48,000",
        "intl_pct": "~16%",
        "living_cost": "2,200 USD",
        "strategy": "GOOD CHOICE. Strong ML research. Amazon/Microsoft nearby for internships.",
    },
    {
        "country": "USA",
        "name": "University of Illinois Urbana-Champaign (UIUC)",
        "location": "Urbana-Champaign, Illinois",
        "type": "Public (Top Public)",
        "qs_rank": "64",
        "the_rank": "46",
        "program": "MSc Statistics (Data Science track)",
        "degree": "MSc",
        "field": "Statistics, Data Science, ML",
        "language": "English",
        "tuition": "10,000",
        "currency": "USD",
        "semester_fee": "600 (estimated)",
        "app_fee": "90",
        "deadline_winter": "February 1",
        "deadline_summer": "October 15 (Spring)",
        "requirements": "Bachelor's in Stats/Math/CS; GRE; SOP; Recommendations",
        "english": "TOEFL 96 / IELTS 6.5",
        "gre": "Required",
        "min_gpa": "3.0+",
        "duration": "4 semesters",
        "ects": "N/A",
        "scholarships": "TA/RA, UIUC fellowships",
        "portal": "https://illinois.edu/",
        "dept_url": "https://stat.illinois.edu/",
        "research": "Statistics, Data Science, ML (David Forsyth - Vision)",
        "students": "~56,000",
        "intl_pct": "~25%",
        "living_cost": "1,400 USD",
        "strategy": "GOOD FIT. Excellent Statistics department. TA/RA funding available. Affordable living.",
    },
    {
        "country": "USA",
        "name": "University of Michigan, Ann Arbor",
        "location": "Ann Arbor, Michigan",
        "type": "Public (Top Public)",
        "qs_rank": "25",
        "the_rank": "23",
        "program": "MSc Data Science",
        "degree": "MSc",
        "field": "Data Science, ML, AI",
        "language": "English",
        "tuition": "13,000",
        "currency": "USD",
        "semester_fee": "600 (estimated)",
        "app_fee": "90",
        "deadline_winter": "January 15",
        "deadline_summer": "N/A",
        "requirements": "Bachelor's in CS/Stats/Math; GRE; SOP; Recommendations; CV",
        "english": "TOEFL 100 / IELTS 7.0",
        "gre": "Required",
        "min_gpa": "3.0+",
        "duration": "4 semesters",
        "ects": "N/A",
        "scholarships": "TA/RA, Rackham fellowships",
        "portal": "https://umich.edu/",
        "dept_url": "https://www.midata.umich.edu/",
        "research": "ML, AI, Data Science, Large international community",
        "students": "~51,000",
        "intl_pct": "~17%",
        "living_cost": "1,800 USD",
        "strategy": "GOOD CHOICE. Strong data science program. Large international community helps integration.",
    },
    {
        "country": "USA",
        "name": "University of California, Los Angeles (UCLA)",
        "location": "Los Angeles, California",
        "type": "Public (Top Public)",
        "qs_rank": "29",
        "the_rank": "18",
        "program": "MSc Statistics",
        "degree": "MSc",
        "field": "Statistics, Data Science, ML",
        "language": "English",
        "tuition": "12,000",
        "currency": "USD",
        "semester_fee": "800 (estimated)",
        "app_fee": "140",
        "deadline_winter": "December 15",
        "deadline_summer": "N/A (Fall only)",
        "requirements": "Bachelor's in Stats/Math/CS; GRE; SOP; Recommendations",
        "english": "TOEFL 87 / IELTS 7.0",
        "gre": "Required",
        "min_gpa": "3.0+",
        "duration": "4 semesters",
        "ects": "N/A",
        "scholarships": "TA/RA",
        "portal": "https://www.ucla.edu/",
        "dept_url": "https://statistics.ucla.edu/",
        "research": "Statistics, ML theory, Data Science",
        "students": "~46,000",
        "intl_pct": "~15%",
        "living_cost": "2,200 USD",
        "strategy": "GOOD FIT. Your Statistics background matches. Lower TOEFL requirement (87).",
    },
    {
        "country": "USA",
        "name": "Princeton University",
        "location": "Princeton, New Jersey",
        "type": "Ivy League",
        "qs_rank": "17",
        "the_rank": "6",
        "program": "MSc Operations Research & Financial Engineering (ML/Stats track)",
        "degree": "MSc",
        "field": "ORFE, ML, Statistics",
        "language": "English",
        "tuition": "28,000",
        "currency": "USD",
        "semester_fee": "500 (estimated)",
        "app_fee": "90",
        "deadline_winter": "December 15",
        "deadline_summer": "N/A (Fall only)",
        "requirements": "Bachelor's in Math/Stats/CS/Engineering; GRE; SOP; 3 Recommendations",
        "english": "TOEFL 100 / IELTS 7.0",
        "gre": "Required",
        "min_gpa": "No strict cutoff",
        "duration": "4 semesters",
        "ects": "N/A",
        "scholarships": "Princeton fellowships, TA/RA",
        "portal": "https://www.princeton.edu/",
        "dept_url": "https://orfe.princeton.edu/",
        "research": "ML theory, Operations Research, Statistics",
        "students": "~8,500",
        "intl_pct": "~23%",
        "living_cost": "1,800 USD",
        "strategy": "REACH. Ivy League. Strong math/stats. Generous funding for students admitted.",
    },
    {
        "country": "Switzerland",
        "name": "ETH Zurich (Swiss Federal Institute of Technology)",
        "location": "Zurich, Switzerland",
        "type": "Public Research",
        "qs_rank": "7",
        "the_rank": "11",
        "program": "Master in Computer Science / Data Science",
        "degree": "MSc",
        "field": "Computer Science / Data Science / ML",
        "language": "English",
        "tuition": "730",
        "currency": "CHF",
        "semester_fee": "730",
        "app_fee": "150 CHF",
        "deadline_winter": "Dec 15",
        "deadline_summer": "N/A",
        "requirements": "Bachelor in CS or related with excellent academic record; strong mathematical/theory foundations",
        "english": "TOEFL 100+ / IELTS 7.0+",
        "gre": "Highly recommended (mandatory for non-Bologna degrees)",
        "min_gpa": "3.7+ (highly competitive)",
        "duration": "4",
        "ects": "120 ECTS",
        "scholarships": "Excellence Scholarship & Opportunity Programme (ESOP); Swiss Govt Excellence Scholarships",
        "portal": "https://ethz.ch/en/studies/master/application.html",
        "dept_url": "https://inf.ethz.ch/",
        "research": "AI, Machine Learning, Systems, Theory, Visual Computing",
        "students": "~22,000",
        "intl_pct": "~40%",
        "living_cost": "2,000 CHF",
        "strategy": "HIGH RECOMMENDATION. Extremely low tuition fee (under $1000/sem) for world-class education. Focus heavily on math/theory background in SOP.",
    },
    {
        "country": "Canada",
        "name": "University of Toronto",
        "location": "Toronto, Canada",
        "type": "Public Research",
        "qs_rank": "25",
        "the_rank": "21",
        "program": "MSc in Computer Science (focus on Machine Learning)",
        "degree": "MSc",
        "field": "Machine Learning / AI",
        "language": "English",
        "tuition": "16000",
        "currency": "CAD",
        "semester_fee": "1000",
        "app_fee": "125 CAD",
        "deadline_winter": "Dec 1 (Fall intake)",
        "deadline_summer": "N/A",
        "requirements": "Bachelor in CS or related; strong research interest; 3 LORs; CV; SOP",
        "english": "TOEFL 93+ / IELTS 7.0+",
        "gre": "Recommended",
        "min_gpa": "3.3+ (but 3.7+ competitive)",
        "duration": "3",
        "ects": "N/A",
        "scholarships": "Fully funded research masters (covers tuition + living stipend for admitted students)",
        "portal": "https://web.cs.toronto.edu/graduate/admissions",
        "dept_url": "https://web.cs.toronto.edu/",
        "research": "Machine Learning (Vector Institute), Neural Networks, Computer Vision, NLP",
        "students": "~90,000",
        "intl_pct": "~30%",
        "living_cost": "1,800 CAD",
        "strategy": "PRIMARY TARGET. Research masters are fully funded. Excellent research group (Geoffrey Hinton's home turf). Secure a supervisor support first.",
    },
    {
        "country": "Singapore",
        "name": "National University of Singapore (NUS)",
        "location": "Singapore",
        "type": "Public Research",
        "qs_rank": "8",
        "the_rank": "19",
        "program": "Master of Computing (Artificial Intelligence)",
        "degree": "MComp",
        "field": "Artificial Intelligence / CS",
        "language": "English",
        "tuition": "25000",
        "currency": "SGD",
        "semester_fee": "500",
        "app_fee": "100 SGD",
        "deadline_winter": "Feb 28 (August intake)",
        "deadline_summer": "Aug 31 (January intake)",
        "requirements": "Honours degree in CS/IT or related field; GRE required; SOP; 2 LORs",
        "english": "TOEFL 90+ / IELTS 6.0+",
        "gre": "Required (320+ recommended)",
        "min_gpa": "3.5+ (highly competitive)",
        "duration": "3",
        "ects": "N/A (40 MCs)",
        "scholarships": "SINGA PhD Award; NUS Graduate Assistantships",
        "portal": "https://www.comp.nus.edu.sg/programmes/pg/mcomp/",
        "dept_url": "https://www.comp.nus.edu.sg/",
        "research": "AI, ML, Robotics, Database Systems, Security",
        "students": "~40,000",
        "intl_pct": "~35%",
        "living_cost": "1,500 SGD",
        "strategy": "STRONG RECOMMENDATION. Premier university in Asia. Target GRE score of 320+ to remain competitive. Apply early.",
    },
    {
        "country": "UK",
        "name": "University of Oxford",
        "location": "Oxford, United Kingdom",
        "type": "Public Research",
        "qs_rank": "3",
        "the_rank": "1",
        "program": "MSc in Advanced Computer Science",
        "degree": "MSc",
        "field": "Computer Science / ML / AI",
        "language": "English",
        "tuition": "38000",
        "currency": "GBP",
        "semester_fee": "1500",
        "app_fee": "75 GBP",
        "deadline_winter": "Jan 8 (Fall intake)",
        "deadline_summer": "N/A",
        "requirements": "First-class degree in CS or Mathematics; strong reference letters; outstanding academic records",
        "english": "IELTS 7.5 (min 7.0 each) / TOEFL 110+",
        "gre": "Not required",
        "min_gpa": "3.8+ (out of 4.0)",
        "duration": "3",
        "ects": "N/A",
        "scholarships": "Oxford Clarendon Scholarship; Commonwealth Scholarship; Chevening",
        "portal": "https://www.ox.ac.uk/admissions/graduate/courses/msc-advanced-computer-science",
        "dept_url": "https://www.cs.ox.ac.uk/",
        "research": "Theoretical CS, Artificial Intelligence, Machine Learning, Automated Verification",
        "students": "~26,000",
        "intl_pct": "~45%",
        "living_cost": "1,600 GBP",
        "strategy": "REACH. Highly prestigious. Needs absolute top GPA. Apply by January deadline to be automatically considered for Oxford scholarships.",
    },
    {
        "country": "USA",
        "name": "Massachusetts Institute of Technology (MIT)",
        "location": "Cambridge, Massachusetts",
        "type": "Private",
        "qs_rank": "1",
        "the_rank": "3",
        "program": "MSc Data Science / ML",
        "degree": "MSc",
        "field": "Data Science, ML, AI",
        "language": "English",
        "tuition": "28,600",
        "currency": "USD",
        "semester_fee": "400 (estimated)",
        "app_fee": "90",
        "deadline_winter": "December 1",
        "deadline_summer": "N/A (Fall only)",
        "requirements": "Bachelor's in CS/Stats/Math; GRE; SOP; 3 Letters of recommendation; CV; Transcripts",
        "english": "TOEFL 100 / IELTS 7.0",
        "gre": "Required (quant 165+ recommended)",
        "min_gpa": "No strict cutoff (avg ~3.8+ admitted)",
        "duration": "4 semesters",
        "ects": "N/A",
        "scholarships": "MIT fellowships, TA/RA, MIT Presidential Fellowship",
        "portal": "https://www.mit.edu/",
        "dept_url": "https://www.eecs.mit.edu/",
        "research": "ML (Tenenbaum, Jaakkola), AI, Data Science Systems",
        "students": "~12,000",
        "intl_pct": "~30%",
        "living_cost": "2,200 USD",
        "strategy": "TOP REACH. #1 globally. Strong funding packages available for PhD-bound MSc students.",
    },
    {
        "country": "USA",
        "name": "Harvard University",
        "location": "Cambridge, Massachusetts",
        "type": "Ivy League",
        "qs_rank": "4",
        "the_rank": "4",
        "program": "MSc Data Science",
        "degree": "MSc",
        "field": "Data Science, Statistics, ML",
        "language": "English",
        "tuition": "26,000",
        "currency": "USD",
        "semester_fee": "500 (estimated)",
        "app_fee": "105",
        "deadline_winter": "December 1",
        "deadline_summer": "N/A (Fall only)",
        "requirements": "Bachelor's in CS/Stats/Math; strong quantitative; GRE; SOP; 3 Letters of recommendation",
        "english": "TOEFL 104 / IELTS 7.5",
        "gre": "Required (quant 165+ recommended)",
        "min_gpa": "No strict cutoff (avg ~3.8+ admitted)",
        "duration": "4 semesters",
        "ects": "N/A",
        "scholarships": "Harvard GSAS fellowships, TA/RA",
        "portal": "https://www.harvard.edu/",
        "dept_url": "https://www.seas.harvard.edu/",
        "research": "Statistical Learning, ML theory, AI, Computational Science",
        "students": "~22,000",
        "intl_pct": "~25%",
        "living_cost": "2,300 USD",
        "strategy": "REACH. Harvard Data Science is jointly run by Stats + CS departments. Strong brand.",
    },
    {
        "country": "USA",
        "name": "Cornell University",
        "location": "Ithaca, New York",
        "type": "Ivy League",
        "qs_rank": "13",
        "the_rank": "12",
        "program": "MSc Computer Science (ML/AI)",
        "degree": "MSc",
        "field": "CS, ML, AI",
        "language": "English",
        "tuition": "20,000",
        "currency": "USD",
        "semester_fee": "400 (estimated)",
        "app_fee": "95",
        "deadline_winter": "December 15",
        "deadline_summer": "N/A (Fall only)",
        "requirements": "Bachelor's in CS/related; GRE; SOP; 3 Recommendations; CV",
        "english": "TOEFL 100 / IELTS 7.0",
        "gre": "Required",
        "min_gpa": "No strict cutoff (avg ~3.7+ admitted)",
        "duration": "4 semesters",
        "ects": "N/A",
        "scholarships": "TA/RA, Cornell fellowships",
        "portal": "https://www.cornell.edu/",
        "dept_url": "https://www.cs.cornell.edu/",
        "research": "AI (Bart Selman), ML, NLP, Computer Vision",
        "students": "~25,000",
        "intl_pct": "~21%",
        "living_cost": "1,700 USD",
        "strategy": "REACH. Strong CS department. Ithaca has lower living cost. Good TA/RA opportunities.",
    },
    {
        "country": "USA",
        "name": "University of Texas at Austin (UT Austin)",
        "location": "Austin, Texas",
        "type": "Public (Top Public)",
        "qs_rank": "38",
        "the_rank": "29",
        "program": "MSc Data Science and AI",
        "degree": "MSc",
        "field": "Data Science, ML, AI",
        "language": "English",
        "tuition": "10,000",
        "currency": "USD",
        "semester_fee": "600 (estimated)",
        "app_fee": "90",
        "deadline_winter": "January 15",
        "deadline_summer": "N/A (Fall only)",
        "requirements": "Bachelor's in CS/Stats/Math; GRE; SOP; Recommendations; CV",
        "english": "TOEFL 90 / IELTS 6.5",
        "gre": "Required",
        "min_gpa": "3.0+",
        "duration": "4 semesters",
        "ects": "N/A",
        "scholarships": "TA/RA, UT Austin fellowships",
        "portal": "https://www.utexas.edu/",
        "dept_url": "https://www.cs.utexas.edu/",
        "research": "ML (Inderjit Dhillon, Alex Dimakis), NLP, AI",
        "students": "~52,000",
        "intl_pct": "~10%",
        "living_cost": "1,500 USD",
        "strategy": "STRONG CHOICE. Excellent value for public university. Strong ML research. Austin tech hub.",
    },
    {
        "country": "USA",
        "name": "University of Chicago",
        "location": "Chicago, Illinois",
        "type": "Private",
        "qs_rank": "10",
        "the_rank": "10",
        "program": "MSc Data Science",
        "degree": "MSc",
        "field": "Data Science, ML, Statistics",
        "language": "English",
        "tuition": "20,000",
        "currency": "USD",
        "semester_fee": "500 (estimated)",
        "app_fee": "95",
        "deadline_winter": "January 4",
        "deadline_summer": "N/A (Fall only)",
        "requirements": "Bachelor's in CS/Math/Stats; GRE optional; SOP; 3 Recommendations; CV",
        "english": "TOEFL 100 / IELTS 7.0",
        "gre": "Optional",
        "min_gpa": "3.0+",
        "duration": "5 quarters",
        "ects": "N/A",
        "scholarships": "Merit scholarships, TA/RA",
        "portal": "https://www.uchicago.edu/",
        "dept_url": "https://datascience.uchicago.edu/",
        "research": "Data Science, Computational Statistics, ML for Science",
        "students": "~18,000",
        "intl_pct": "~28%",
        "living_cost": "2,000 USD",
        "strategy": "GOOD CHOICE. UChicago Data Science Institute is well-funded. GRE optional reduces barriers.",
    },
    {
        "country": "USA",
        "name": "New York University (NYU)",
        "location": "New York City, New York",
        "type": "Private",
        "qs_rank": "26",
        "the_rank": "27",
        "program": "MSc Data Science / CS",
        "degree": "MSc",
        "field": "Data Science, ML, CS",
        "language": "English",
        "tuition": "22,000",
        "currency": "USD",
        "semester_fee": "500 (estimated)",
        "app_fee": "100",
        "deadline_winter": "December 15",
        "deadline_summer": "October 1 (Spring)",
        "requirements": "Bachelor's in CS/Math/Stats; GRE optional; SOP; 3 Recommendations; CV",
        "english": "TOEFL 100 / IELTS 7.0",
        "gre": "Optional",
        "min_gpa": "3.0+",
        "duration": "4 semesters",
        "ects": "N/A",
        "scholarships": "NYU scholarships, TA/RA",
        "portal": "https://www.nyu.edu/",
        "dept_url": "https://cds.nyu.edu/",
        "research": "ML (Yann LeCun, Kyunghyun Cho), Data Science, NLP, AI",
        "students": "~60,000",
        "intl_pct": "~28%",
        "living_cost": "2,500 USD",
        "strategy": "GOOD CHOICE. CDS (Center for Data Science) is top-notch. Yann LeCun's group. GRE optional. NYC living is expensive.",
    },
    {
        "country": "USA",
        "name": "University of California, San Diego (UCSD)",
        "location": "San Diego, California",
        "type": "Public (Top Public)",
        "qs_rank": "35",
        "the_rank": "32",
        "program": "MSc Data Science",
        "degree": "MSc",
        "field": "Data Science, ML, AI",
        "language": "English",
        "tuition": "12,000",
        "currency": "USD",
        "semester_fee": "700 (estimated)",
        "app_fee": "140",
        "deadline_winter": "January 6",
        "deadline_summer": "N/A (Fall only)",
        "requirements": "Bachelor's in CS/Stats/Math; GRE; SOP; 3 Recommendations; CV",
        "english": "TOEFL 85 / IELTS 7.0",
        "gre": "Required",
        "min_gpa": "3.0+",
        "duration": "4 semesters",
        "ects": "N/A",
        "scholarships": "TA/RA, UCSD fellowships",
        "portal": "https://ucsd.edu/",
        "dept_url": "https://datascience.ucsd.edu/",
        "research": "ML (Sculley), Data Science, AI, Statistics",
        "students": "~42,000",
        "intl_pct": "~23%",
        "living_cost": "2,100 USD",
        "strategy": "GOOD CHOICE. Strong data science program. San Diego location. Halicioglu Data Science Institute.",
    },
]

# === NEW REGION LISTS ===

UK_UNIVERSITIES = [
    {
        "country": "UK",
        "name": "University of Cambridge",
        "location": "Cambridge, United Kingdom",
        "type": "Public Research",
        "qs_rank": "2",
        "the_rank": "5",
        "program": "MSc in Machine Learning and Machine Intelligence",
        "degree": "MSc",
        "field": "Machine Learning, AI",
        "language": "English",
        "tuition": "37,000",
        "currency": "GBP",
        "semester_fee": "1,500",
        "app_fee": "70 GBP",
        "deadline_winter": "December 5",
        "deadline_summer": "N/A (Fall only)",
        "requirements": "First-class degree in CS/Math/Engineering; strong technical background; 3 LORs; CV; SOP",
        "english": "IELTS 7.5 (min 7.0 each) / TOEFL 107+",
        "gre": "Not required",
        "min_gpa": "3.8+ (out of 4.0)",
        "duration": "3",
        "ects": "N/A",
        "scholarships": "Cambridge Trust Scholarship; Gates Cambridge; Chevening; Commonwealth",
        "portal": "https://www.cam.ac.uk/",
        "dept_url": "https://www.cst.cam.ac.uk/",
        "research": "ML (Zoubin Ghahramani), Machine Intelligence, NLP, Computer Vision",
        "students": "~24,000",
        "intl_pct": "~40%",
        "living_cost": "1,500 GBP",
        "strategy": "REACH. World-leading ML program. Gates Cambridge covers full costs. Apply by early Dec.",
    },
    {
        "country": "UK",
        "name": "Imperial College London",
        "location": "London, United Kingdom",
        "type": "Public Research",
        "qs_rank": "6",
        "the_rank": "9",
        "program": "MSc Artificial Intelligence",
        "degree": "MSc",
        "field": "Artificial Intelligence, ML",
        "language": "English",
        "tuition": "38,000",
        "currency": "GBP",
        "semester_fee": "1,500",
        "app_fee": "80 GBP",
        "deadline_winter": "January 31",
        "deadline_summer": "N/A (Fall only)",
        "requirements": "First-class degree in CS/related; strong math background; 2 LORs; CV; SOP",
        "english": "IELTS 7.0 (min 6.5 each) / TOEFL 100+",
        "gre": "Not required",
        "min_gpa": "3.6+ (out of 4.0)",
        "duration": "3",
        "ects": "N/A",
        "scholarships": "Imperial President's Scholarship; Chevening; Commonwealth; GREAT Scholarship",
        "portal": "https://www.imperial.ac.uk/",
        "dept_url": "https://www.imperial.ac.uk/computing/",
        "research": "AI, ML (Aldo Faisal), Robotics, Computer Vision, NLP",
        "students": "~20,000",
        "intl_pct": "~50%",
        "living_cost": "1,800 GBP",
        "strategy": "REACH. Top-tier AI program in London. Strong industry connections. Apply early for scholarship consideration.",
    },
    {
        "country": "UK",
        "name": "UCL (University College London)",
        "location": "London, United Kingdom",
        "type": "Public Research",
        "qs_rank": "8",
        "the_rank": "14",
        "program": "MSc Data Science and Machine Learning",
        "degree": "MSc",
        "field": "Data Science, Machine Learning, AI",
        "language": "English",
        "tuition": "34,000",
        "currency": "GBP",
        "semester_fee": "1,300",
        "app_fee": "75 GBP",
        "deadline_winter": "March 15 (rolling)",
        "deadline_summer": "N/A (Fall only)",
        "requirements": "Bachelor's in CS/Stats/Math; strong quantitative background; 2 LORs; CV; SOP",
        "english": "IELTS 7.0 (min 6.5 each) / TOEFL 100+",
        "gre": "Not required",
        "min_gpa": "3.5+ (out of 4.0)",
        "duration": "3",
        "ects": "N/A",
        "scholarships": "UCL Graduate Scholarships; Chevening; Commonwealth; GREAT Scholarship",
        "portal": "https://www.ucl.ac.uk/",
        "dept_url": "https://www.ucl.ac.uk/computer-science/",
        "research": "ML, Data Science, AI (incl. David Barber), Computational Statistics",
        "students": "~43,000",
        "intl_pct": "~50%",
        "living_cost": "1,800 GBP",
        "strategy": "STRONG CHOICE. Top program at leading UK university. Rolling admissions so apply early.",
    },
    {
        "country": "UK",
        "name": "University of Edinburgh",
        "location": "Edinburgh, Scotland",
        "type": "Public Research",
        "qs_rank": "22",
        "the_rank": "30",
        "program": "MSc Artificial Intelligence",
        "degree": "MSc",
        "field": "Artificial Intelligence, ML, Cognitive Science",
        "language": "English",
        "tuition": "32,000",
        "currency": "GBP",
        "semester_fee": "1,200",
        "app_fee": "65 GBP",
        "deadline_winter": "March 31",
        "deadline_summer": "N/A (Fall only)",
        "requirements": "Bachelor's in CS/Math/related; 2 LORs; CV; SOP; Academic transcripts",
        "english": "IELTS 7.0 (min 6.0 each) / TOEFL 95+",
        "gre": "Not required",
        "min_gpa": "3.4+ (out of 4.0)",
        "duration": "3",
        "ects": "N/A",
        "scholarships": "Edinburgh Global Scholarships; Chevening; Commonwealth",
        "portal": "https://www.ed.ac.uk/",
        "dept_url": "https://www.ed.ac.uk/informatics/",
        "research": "AI (one of Europe's largest AI groups), ML, NLP, Robotics, Cognitive Science",
        "students": "~41,000",
        "intl_pct": "~40%",
        "living_cost": "1,200 GBP",
        "strategy": "STRONG CHOICE. Legendary AI department. Lower living cost than London. Late deadline helps.",
    },
]

SWITZERLAND_UNIVERSITIES = [
    {
        "country": "Switzerland",
        "name": "EPFL (Ecole Polytechnique Federale de Lausanne)",
        "location": "Lausanne, Switzerland",
        "type": "Public Research",
        "qs_rank": "36",
        "the_rank": "34",
        "program": "MSc Data Science",
        "degree": "MSc",
        "field": "Data Science, ML, AI",
        "language": "English",
        "tuition": "780",
        "currency": "CHF",
        "semester_fee": "780",
        "app_fee": "150 CHF",
        "deadline_winter": "Dec 15 (early) / Jan 15 (regular)",
        "deadline_summer": "N/A",
        "requirements": "Bachelor's in CS/Math/Stats; excellent academic record; CV; SOP; 2-3 LORs; Transcripts",
        "english": "TOEFL 100+ / IELTS 7.0+",
        "gre": "Not required (recommended for non-EPFL)",
        "min_gpa": "3.5+ (highly competitive)",
        "duration": "4",
        "ects": "120 ECTS",
        "scholarships": "EPFL Excellence Fellowship; Swiss Government Excellence Scholarships",
        "portal": "https://www.epfl.ch/education/master/",
        "dept_url": "https://www.epfl.ch/schools/ic/",
        "research": "ML, Data Science, AI, NLP (Jaggi), Computer Vision (Fua)",
        "students": "~16,000",
        "intl_pct": "~55%",
        "living_cost": "1,800 CHF",
        "strategy": "TOP CHOICE. Extremely affordable tuition (CHF 780/sem). World-class CS school. Multilingual environment.",
    },
    {
        "country": "Switzerland",
        "name": "EPFL (Ecole Polytechnique Federale de Lausanne)",
        "location": "Lausanne, Switzerland",
        "type": "Public Research",
        "qs_rank": "36",
        "the_rank": "34",
        "program": "MSc Computer Science (AI/ML track)",
        "degree": "MSc",
        "field": "Computer Science, AI, ML",
        "language": "English",
        "tuition": "780",
        "currency": "CHF",
        "semester_fee": "780",
        "app_fee": "150 CHF",
        "deadline_winter": "Dec 15 (early) / Jan 15 (regular)",
        "deadline_summer": "N/A",
        "requirements": "Bachelor's in CS/related; excellent academic record; CV; SOP; 2-3 LORs; Transcripts",
        "english": "TOEFL 100+ / IELTS 7.0+",
        "gre": "Not required (recommended for non-EPFL)",
        "min_gpa": "3.5+ (highly competitive)",
        "duration": "4",
        "ects": "120 ECTS",
        "scholarships": "EPFL Excellence Fellowship; Swiss Government Excellence Scholarships",
        "portal": "https://www.epfl.ch/education/master/",
        "dept_url": "https://www.epfl.ch/schools/ic/",
        "research": "ML, AI, Theory, Systems, Vision, Robotics (Mondada, Fua, Jaggi)",
        "students": "~16,000",
        "intl_pct": "~55%",
        "living_cost": "1,800 CHF",
        "strategy": "TOP CHOICE. Same low tuition as Data Science program. Excellent CS faculty. Apply early Dec.",
    },
]

FRANCE_UNIVERSITIES = [
    {
        "country": "France",
        "name": "Universite Paris-Saclay",
        "location": "Paris-Saclay, France",
        "type": "Public Research",
        "qs_rank": "71",
        "the_rank": "58",
        "program": "MSc Data Science and AI",
        "degree": "MSc",
        "field": "Data Science, AI, ML",
        "language": "English",
        "tuition": "3,000",
        "currency": "EUR",
        "semester_fee": "200",
        "app_fee": "None (via Etudes en France)",
        "deadline_winter": "April 1 (via Campus France) / May 15 (direct)",
        "deadline_summer": "October 15",
        "requirements": "Bachelor's in CS/Math/Stats; strong academic record; CV; SOP; 2 LORs",
        "english": "TOEFL 90 / IELTS 6.5",
        "gre": "Not required",
        "min_gpa": "3.3+",
        "duration": "4",
        "ects": "120 ECTS",
        "scholarships": "Eiffel Excellence Scholarship; Campus France grants; Erasmus+",
        "portal": "https://www.universite-paris-saclay.fr/en/",
        "dept_url": "https://www.universite-paris-saclay.fr/en/education/masters",
        "research": "Data Science, ML, AI, Operations Research, Statistics (INRIA joint lab)",
        "students": "~48,000",
        "intl_pct": "~20%",
        "living_cost": "1,000 EUR",
        "strategy": "EXCELLENT VALUE. Very affordable tuition (3,000 EUR/yr). Strong ties with INRIA research. Eiffel scholarship potential.",
    },
    {
        "country": "France",
        "name": "Sorbonne Universite",
        "location": "Paris, France",
        "type": "Public Research",
        "qs_rank": "83",
        "the_rank": "65",
        "program": "MSc Computer Science (ML track)",
        "degree": "MSc",
        "field": "Computer Science, ML, AI",
        "language": "English / French",
        "tuition": "3,000",
        "currency": "EUR",
        "semester_fee": "200",
        "app_fee": "None (via Etudes en France)",
        "deadline_winter": "April 15 (via Campus France)",
        "deadline_summer": "October 30",
        "requirements": "Bachelor's in CS/Math; CV; SOP; Academic transcripts; 2 LORs",
        "english": "TOEFL 85 / IELTS 6.5",
        "gre": "Not required",
        "min_gpa": "3.0+",
        "duration": "4",
        "ects": "120 ECTS",
        "scholarships": "Eiffel Scholarship; Campus France; Sorbonne Amicale scholarships",
        "portal": "https://www.sorbonne-universite.fr/en",
        "dept_url": "https://www.sorbonne-universite.fr/en/education/degrees",
        "research": "ML, AI, Computational Science, Robotics",
        "students": "~55,000",
        "intl_pct": "~18%",
        "living_cost": "1,000 EUR",
        "strategy": "GOOD VALUE. Low tuition. Strong historical university. Some programs may require French.",
    },
    {
        "country": "France",
        "name": "Institut Polytechnique de Paris",
        "location": "Palaiseau, France",
        "type": "Public Research (Grande Ecole)",
        "qs_rank": "46",
        "the_rank": "48",
        "program": "MSc Data Science and AI",
        "degree": "MSc",
        "field": "Data Science, AI, ML",
        "language": "English",
        "tuition": "2,500",
        "currency": "EUR",
        "semester_fee": "300",
        "app_fee": "None",
        "deadline_winter": "April 30",
        "deadline_summer": "October 15",
        "requirements": "Bachelor's in CS/Math/Engineering; CV; SOP; Academic records; 2 LORs",
        "english": "TOEFL 90 / IELTS 6.5",
        "gre": "Not required",
        "min_gpa": "3.3+",
        "duration": "4",
        "ects": "120 ECTS",
        "scholarships": "Eiffel Scholarship; IP Paris Scholarships; Fondation de l'X",
        "portal": "https://www.ip-paris.fr/en",
        "dept_url": "https://www.ip-paris.fr/en/education/masters",
        "research": "AI, Data Science, ML, Operations Research (Ecole Polytechnique heritage)",
        "students": "~10,000",
        "intl_pct": "~40%",
        "living_cost": "1,000 EUR",
        "strategy": "STRONG CHOICE. Prestigious Grande Ecole brand. Low tuition. Strong math foundation. Eiffel scholarship target.",
    },
]

ITALY_UNIVERSITIES = [
    {
        "country": "Italy",
        "name": "Politecnico di Milano",
        "location": "Milan, Italy",
        "type": "Public Technical University",
        "qs_rank": "123",
        "the_rank": "137",
        "program": "MSc Data Science and AI",
        "degree": "MSc",
        "field": "Data Science, AI, ML",
        "language": "English",
        "tuition": "1,500",
        "currency": "EUR",
        "semester_fee": "200",
        "app_fee": "None",
        "deadline_winter": "February 15 (early) / April 15 (regular)",
        "deadline_summer": "September 15",
        "requirements": "Bachelor's in CS/Math/Engineering; CV; SOP; Academic transcripts; 2 LORs",
        "english": "TOEFL 78 / IELTS 6.0",
        "gre": "Not required",
        "min_gpa": "3.0+ (competitive)",
        "duration": "4",
        "ects": "120 ECTS",
        "scholarships": "Polimi Merit Scholarship; Italian Government Scholarships; Lombardy Region grants",
        "portal": "https://www.polimi.it/en/",
        "dept_url": "https://www.deib.polimi.it/",
        "research": "Data Science, AI, ML, Computer Vision, NLP",
        "students": "~42,000",
        "intl_pct": "~15%",
        "living_cost": "1,000 EUR",
        "strategy": "STRONG CHOICE. Best technical university in Italy. Low income-based tuition. Strong engineering focus.",
    },
    {
        "country": "Italy",
        "name": "University of Bologna",
        "location": "Bologna, Italy",
        "type": "Public Research",
        "qs_rank": "196",
        "the_rank": "161",
        "program": "MSc Artificial Intelligence",
        "degree": "MSc",
        "field": "Artificial Intelligence, ML, Data Science",
        "language": "English",
        "tuition": "1,200",
        "currency": "EUR",
        "semester_fee": "200",
        "app_fee": "None",
        "deadline_winter": "April 30",
        "deadline_summer": "September 30",
        "requirements": "Bachelor's in CS/Math/related; CV; SOP; Academic records; 2 LORs",
        "english": "TOEFL 80 / IELTS 6.0",
        "gre": "Not required",
        "min_gpa": "3.0+",
        "duration": "4",
        "ects": "120 ECTS",
        "scholarships": "Bologna University Scholarships; Italian Government; Erasmus+",
        "portal": "https://www.unibo.it/en",
        "dept_url": "https://www.unibo.it/en/teaching/degree-programmes",
        "research": "AI, ML, Data Science, Robotics, Knowledge Representation",
        "students": "~85,000",
        "intl_pct": "~8%",
        "living_cost": "850 EUR",
        "strategy": "GOOD VALUE. Oldest university in the world. Low tuition. Bologna is a classic student city.",
    },
    {
        "country": "Italy",
        "name": "University of Trento",
        "location": "Trento, Italy",
        "type": "Public Research",
        "qs_rank": "408",
        "the_rank": "251-300",
        "program": "MSc Data Science",
        "degree": "MSc",
        "field": "Data Science, ML, Statistics",
        "language": "English",
        "tuition": "1,000",
        "currency": "EUR",
        "semester_fee": "150",
        "app_fee": "None",
        "deadline_winter": "March 15",
        "deadline_summer": "September 15",
        "requirements": "Bachelor's in CS/Stats/Math; CV; SOP; Academic records; 2 LORs",
        "english": "TOEFL 80 / IELTS 6.0",
        "gre": "Not required",
        "min_gpa": "3.0+",
        "duration": "4",
        "ects": "120 ECTS",
        "scholarships": "Trento University Scholarships; Opera Universitaria (merit + income-based grants)",
        "portal": "https://www.unitn.it/en",
        "dept_url": "https://www.unitn.it/datascience",
        "research": "Data Science, ML, Statistics, AI in Healthcare",
        "students": "~16,000",
        "intl_pct": "~10%",
        "living_cost": "800 EUR",
        "strategy": "VALUE CHOICE. Very affordable. Good Data Science program. Lower living cost in Trento. Income-based tuition.",
    },
]

AUSTRIA_UNIVERSITIES = [
    {
        "country": "Austria",
        "name": "TU Wien (Vienna University of Technology)",
        "location": "Vienna, Austria",
        "type": "Public Technical University",
        "qs_rank": "224",
        "the_rank": "201-250",
        "program": "MSc Data Science",
        "degree": "MSc",
        "field": "Data Science, ML, AI",
        "language": "English",
        "tuition": "750",
        "currency": "EUR",
        "semester_fee": "750",
        "app_fee": "None",
        "deadline_winter": "September 5",
        "deadline_summer": "February 5",
        "requirements": "Bachelor's in CS/Math/Stats; CV; SOP; Academic transcripts",
        "english": "TOEFL 87 / IELTS 6.5",
        "gre": "Not required",
        "min_gpa": "No strict cutoff",
        "duration": "4",
        "ects": "120 ECTS",
        "scholarships": "Austrian Government Scholarships; OeAD grants",
        "portal": "https://www.tuwien.at/en/",
        "dept_url": "https://www.tuwien.at/en/studies/degree-programmes",
        "research": "Data Science, ML, AI, Computer Vision, Business Informatics",
        "students": "~28,000",
        "intl_pct": "~30%",
        "living_cost": "1,000 EUR",
        "strategy": "STRONG CHOICE. Very low tuition (~750 EUR/sem). Vienna = #1 most liveable city. Late deadlines.",
    },
    {
        "country": "Austria",
        "name": "University of Vienna",
        "location": "Vienna, Austria",
        "type": "Public Research",
        "qs_rank": "152",
        "the_rank": "137",
        "program": "MSc Computer Science (Data Science)",
        "degree": "MSc",
        "field": "CS, Data Science, ML",
        "language": "English",
        "tuition": "750",
        "currency": "EUR",
        "semester_fee": "750",
        "app_fee": "None",
        "deadline_winter": "September 5",
        "deadline_summer": "February 5",
        "requirements": "Bachelor's in CS/related; CV; SOP; Academic records",
        "english": "TOEFL 87 / IELTS 6.5",
        "gre": "Not required",
        "min_gpa": "No strict cutoff",
        "duration": "4",
        "ects": "120 ECTS",
        "scholarships": "Austrian Government Scholarships; OeAD",
        "portal": "https://www.univie.ac.at/en/",
        "dept_url": "https://www.informatik.univie.ac.at/",
        "research": "Data Science, ML, Computational Science, Algorithms",
        "students": "~90,000",
        "intl_pct": "~25%",
        "living_cost": "1,000 EUR",
        "strategy": "GOOD CHOICE. Very low tuition. Large university with diverse CS offerings. Vienna location is a plus.",
    },
]

BELGIUM_UNIVERSITIES = [
    {
        "country": "Belgium",
        "name": "KU Leuven",
        "location": "Leuven, Belgium",
        "type": "Public Research",
        "qs_rank": "61",
        "the_rank": "45",
        "program": "MSc Statistics and Data Science",
        "degree": "MSc",
        "field": "Statistics, Data Science, ML",
        "language": "English",
        "tuition": "4,000",
        "currency": "EUR",
        "semester_fee": "200",
        "app_fee": "None",
        "deadline_winter": "May 15 (non-EEA) / August 15 (EEA)",
        "deadline_summer": "N/A (winter only)",
        "requirements": "Bachelor's in Stats/Math/CS/Engineering; strong quantitative; CV; SOP; 2 LORs",
        "english": "TOEFL 94 / IELTS 7.0",
        "gre": "Not required",
        "min_gpa": "3.3+",
        "duration": "4",
        "ects": "120 ECTS",
        "scholarships": "KU Leuven Master Mind Scholarship; VLIR-UOS; Belgian Government",
        "portal": "https://www.kuleuven.be/english/",
        "dept_url": "https://www.kuleuven.be/english/education/statistics",
        "research": "Statistics, Data Science, Biostatistics, Econometrics",
        "students": "~60,000",
        "intl_pct": "~17%",
        "living_cost": "900 EUR",
        "strategy": "STRONG CHOICE. Top-ranked in Belgium. Excellent statistics program. Natural fit for your background.",
    },
    {
        "country": "Belgium",
        "name": "Ghent University",
        "location": "Ghent, Belgium",
        "type": "Public Research",
        "qs_rank": "128",
        "the_rank": "107",
        "program": "MSc Computer Science (AI)",
        "degree": "MSc",
        "field": "CS, AI, ML",
        "language": "English",
        "tuition": "3,000",
        "currency": "EUR",
        "semester_fee": "200",
        "app_fee": "None",
        "deadline_winter": "April 1 (non-EEA) / August 1 (EEA)",
        "deadline_summer": "October 1 (EEA only)",
        "requirements": "Bachelor's in CS/related; CV; SOP; Academic records; 2 LORs",
        "english": "TOEFL 90 / IELTS 6.5",
        "gre": "Not required",
        "min_gpa": "3.0+",
        "duration": "4",
        "ects": "120 ECTS",
        "scholarships": "Ghent University Top-up Grants; VLIR-UOS; Master Mind",
        "portal": "https://www.ugent.be/en",
        "dept_url": "https://www.ugent.be/ea/en",
        "research": "AI, ML, Data Mining, NLP, Computer Vision",
        "students": "~44,000",
        "intl_pct": "~12%",
        "living_cost": "850 EUR",
        "strategy": "GOOD VALUE. Affordable tuition. Ghent is a beautiful student city. Good AI program.",
    },
]

NORWAY_UNIVERSITIES = [
    {
        "country": "Norway",
        "name": "NTNU (Norwegian University of Science and Technology)",
        "location": "Trondheim, Norway",
        "type": "Public Technical University",
        "qs_rank": "301",
        "the_rank": "201-250",
        "program": "MSc Computer Science (ML/AI)",
        "degree": "MSc",
        "field": "CS, ML, AI",
        "language": "English",
        "tuition": "0",
        "currency": "NOK",
        "semester_fee": "600",
        "app_fee": "None",
        "deadline_winter": "April 15",
        "deadline_summer": "October 15",
        "requirements": "Bachelor's in CS/Math; CV; SOP; Academic transcripts; 2 LORs",
        "english": "TOEFL 90 / IELTS 6.5",
        "gre": "Not required",
        "min_gpa": "No strict cutoff",
        "duration": "4",
        "ects": "120 ECTS",
        "scholarships": "Norwegian Government Scholarships (Quota Scheme); Erasmus+",
        "portal": "https://www.ntnu.edu/",
        "dept_url": "https://www.ntnu.edu/studies/msc",
        "research": "ML, AI, Data Science, NLP, Robotics",
        "students": "~42,000",
        "intl_pct": "~10%",
        "living_cost": "1,200 EUR",
        "strategy": "FREE TUITION. Norway's premier technical university. Zero tuition even for international students.",
    },
    {
        "country": "Norway",
        "name": "University of Oslo",
        "location": "Oslo, Norway",
        "type": "Public Research",
        "qs_rank": "119",
        "the_rank": "119",
        "program": "MSc Data Science",
        "degree": "MSc",
        "field": "Data Science, ML, Statistics",
        "language": "English",
        "tuition": "0",
        "currency": "NOK",
        "semester_fee": "600",
        "app_fee": "None",
        "deadline_winter": "April 15",
        "deadline_summer": "October 15",
        "requirements": "Bachelor's in CS/Stats/Math; CV; SOP; Academic records; 2 LORs",
        "english": "TOEFL 90 / IELTS 6.5",
        "gre": "Not required",
        "min_gpa": "3.0+",
        "duration": "4",
        "ects": "120 ECTS",
        "scholarships": "Norwegian Government; Quota Scheme; Erasmus+",
        "portal": "https://www.uio.no/english/",
        "dept_url": "https://www.uio.no/english/studies/programmes/",
        "research": "Data Science, ML, Computational Science, Statistics",
        "students": "~28,000",
        "intl_pct": "~12%",
        "living_cost": "1,300 EUR",
        "strategy": "FREE TUITION. Norway's highest-ranked university. Zero tuition. Higher living cost in Oslo.",
    },
]

NETHERLANDS_UNIVERSITIES = [
    {
        "country": "Netherlands",
        "name": "TU Delft",
        "location": "Delft, Netherlands",
        "type": "Public Technical University",
        "qs_rank": "47",
        "the_rank": "70",
        "program": "MSc Computer Science (AI/ML track)",
        "degree": "MSc",
        "field": "CS, AI, ML",
        "language": "English",
        "tuition": "18,000",
        "currency": "EUR",
        "semester_fee": "200",
        "app_fee": "100 EUR",
        "deadline_winter": "January 15 (non-EEA) / May 1 (EEA)",
        "deadline_summer": "N/A (winter only)",
        "requirements": "Bachelor's in CS/related; strong academic record; CV; SOP; 2 LORs",
        "english": "TOEFL 100 / IELTS 7.0",
        "gre": "Required (non-EEA)",
        "min_gpa": "3.5+ (competitive)",
        "duration": "4",
        "ects": "120 ECTS",
        "scholarships": "TU Delft Excellence Scholarship; Holland Scholarship; Orange Tulip; Erasmus+",
        "portal": "https://www.tudelft.nl/en/",
        "dept_url": "https://www.tudelft.nl/en/ewi/",
        "research": "AI, ML, Robotics, Computer Vision, NLP",
        "students": "~25,000",
        "intl_pct": "~30%",
        "living_cost": "1,200 EUR",
        "strategy": "STRONG CHOICE. Top Dutch technical university. Many scholarships available. GRE required for non-EEA.",
    },
    {
        "country": "Netherlands",
        "name": "University of Amsterdam (UvA)",
        "location": "Amsterdam, Netherlands",
        "type": "Public Research",
        "qs_rank": "53",
        "the_rank": "61",
        "program": "MSc Artificial Intelligence",
        "degree": "MSc",
        "field": "AI, ML, Data Science",
        "language": "English",
        "tuition": "17,500",
        "currency": "EUR",
        "semester_fee": "200",
        "app_fee": "100 EUR",
        "deadline_winter": "January 31 (non-EEA) / May 1 (EEA)",
        "deadline_summer": "N/A (winter only)",
        "requirements": "Bachelor's in AI/CS/related; CV; SOP; 2 LORs; Academic records",
        "english": "TOEFL 100 / IELTS 7.0",
        "gre": "Not required",
        "min_gpa": "3.3+",
        "duration": "4",
        "ects": "120 ECTS",
        "scholarships": "UvA Amsterdam Merit Scholarship; Holland Scholarship; Orange Tulip",
        "portal": "https://www.uva.nl/en",
        "dept_url": "https://www.uva.nl/en/programmes/masters/artificial-intelligence/artificial-intelligence.html",
        "research": "AI, ML, NLP, Computational Social Science, Multi-agent Systems",
        "students": "~31,000",
        "intl_pct": "~25%",
        "living_cost": "1,300 EUR",
        "strategy": "GOOD CHOICE. Strong AI program. Amsterdam is a tech hub. Many scholarship opportunities.",
    },
]

SWEDEN_UNIVERSITIES = [
    {
        "country": "Sweden",
        "name": "KTH Royal Institute of Technology",
        "location": "Stockholm, Sweden",
        "type": "Public Technical University",
        "qs_rank": "89",
        "the_rank": "97",
        "program": "MSc Machine Learning",
        "degree": "MSc",
        "field": "Machine Learning, AI, Data Science",
        "language": "English",
        "tuition": "18,000",
        "currency": "EUR",
        "semester_fee": "200",
        "app_fee": "900 SEK",
        "deadline_winter": "January 15",
        "deadline_summer": "N/A (winter only)",
        "requirements": "Bachelor's in CS/Math/related; CV; SOP; 2 LORs; Academic transcripts",
        "english": "TOEFL 90 / IELTS 6.5",
        "gre": "Not required",
        "min_gpa": "3.3+",
        "duration": "4",
        "ects": "120 ECTS",
        "scholarships": "KTH Scholarship; Swedish Institute Scholarships; Erasmus+",
        "portal": "https://www.kth.se/en",
        "dept_url": "https://www.kth.se/en/studies/master/machine-learning",
        "research": "ML, AI, Data Science, Speech Recognition, NLP",
        "students": "~17,000",
        "intl_pct": "~20%",
        "living_cost": "1,000 EUR",
        "strategy": "STRONG CHOICE. Sweden's top technical university. Dedicated ML MSc program. KTH Scholarship covers tuition.",
    },
]

DENMARK_UNIVERSITIES = [
    {
        "country": "Denmark",
        "name": "DTU (Technical University of Denmark)",
        "location": "Kongens Lyngby, Denmark",
        "type": "Public Technical University",
        "qs_rank": "104",
        "the_rank": "97",
        "program": "MSc Data Science",
        "degree": "MSc",
        "field": "Data Science, ML, AI",
        "language": "English",
        "tuition": "15,000",
        "currency": "EUR",
        "semester_fee": "200",
        "app_fee": "100 EUR",
        "deadline_winter": "January 15 (non-EU) / March 1 (EU)",
        "deadline_summer": "N/A (winter only)",
        "requirements": "Bachelor's in CS/Math/Stats/Engineering; CV; SOP; 2 LORs; Academic transcripts",
        "english": "TOEFL 85 / IELTS 6.5",
        "gre": "Not required",
        "min_gpa": "3.3+",
        "duration": "4",
        "ects": "120 ECTS",
        "scholarships": "DTU Scholarship; Danish Government Scholarships; Erasmus+",
        "portal": "https://www.dtu.dk/english",
        "dept_url": "https://www.dtu.dk/english/education/msc/data-science",
        "research": "Data Science, ML, AI, Computational Science, Statistics",
        "students": "~12,000",
        "intl_pct": "~25%",
        "living_cost": "1,400 EUR",
        "strategy": "GOOD CHOICE. Strong technical university. Good data science program. Higher living cost in Denmark.",
    },
]

FINLAND_UNIVERSITIES = [
    {
        "country": "Finland",
        "name": "Aalto University",
        "location": "Espoo/Helsinki, Finland",
        "type": "Public Research",
        "qs_rank": "116",
        "the_rank": "101",
        "program": "MSc Machine Learning, Data Science and AI",
        "degree": "MSc",
        "field": "ML, Data Science, AI",
        "language": "English",
        "tuition": "12,000",
        "currency": "EUR",
        "semester_fee": "200",
        "app_fee": "None",
        "deadline_winter": "January 2 (non-EU/EEA) / March 15 (EU/EEA)",
        "deadline_summer": "N/A (winter only)",
        "requirements": "Bachelor's in CS/Math/Stats; CV; Motivation letter; 2 LORs; Academic records",
        "english": "TOEFL 92 / IELTS 6.5",
        "gre": "Not required",
        "min_gpa": "3.3+",
        "duration": "4",
        "ects": "120 ECTS",
        "scholarships": "Aalto University Scholarship; Finnish Government Scholarship; Erasmus+",
        "portal": "https://www.aalto.fi/en",
        "dept_url": "https://www.aalto.fi/en/study-options/machine-learning-data-science-and-artificial-intelligence-master-of-science-technology",
        "research": "ML, Data Science, AI, Computational Statistics, NLP",
        "students": "~17,000",
        "intl_pct": "~20%",
        "living_cost": "1,200 EUR",
        "strategy": "STRONG CHOICE. Top Finnish university. Dedicated ML/DS/AI program. Aalto Scholarship covers full tuition.",
    },
]

ASIA_UNIVERSITIES = [
    {
        "country": "China",
        "name": "Tsinghua University",
        "location": "Beijing, China",
        "type": "Public Research",
        "qs_rank": "15",
        "the_rank": "16",
        "program": "MSc Computer Science (AI/ML)",
        "degree": "MSc",
        "field": "CS, AI, ML",
        "language": "English / Chinese",
        "tuition": "3,000",
        "currency": "USD",
        "semester_fee": "200",
        "app_fee": "800 CNY",
        "deadline_winter": "December 15 (early) / March 1 (regular)",
        "deadline_summer": "N/A (Fall only)",
        "requirements": "Bachelor's in CS/Math; CV; Research proposal; 2 LORs; Academic transcripts",
        "english": "TOEFL 90 / IELTS 6.5 (for English-taught)",
        "gre": "Not required",
        "min_gpa": "3.5+",
        "duration": "4",
        "ects": "N/A",
        "scholarships": "Chinese Government Scholarship (CSC); Tsinghua Scholarship; Belt & Road",
        "portal": "https://www.tsinghua.edu.cn/en/",
        "dept_url": "https://www.cs.tsinghua.edu.cn/",
        "research": "AI, ML, Computer Vision, NLP, Robotics (world-class)",
        "students": "~36,000",
        "intl_pct": "~10%",
        "living_cost": "800 USD",
        "strategy": "REACH. China's #1 university. Highly competitive. CSC scholarship covers full costs.",
    },
    {
        "country": "Singapore",
        "name": "Nanyang Technological University (NTU)",
        "location": "Singapore",
        "type": "Public Research",
        "qs_rank": "19",
        "the_rank": "40",
        "program": "MSc Artificial Intelligence / Data Science",
        "degree": "MSc",
        "field": "AI, Data Science, ML",
        "language": "English",
        "tuition": "25,000",
        "currency": "SGD",
        "semester_fee": "500",
        "app_fee": "100 SGD",
        "deadline_winter": "February 28 (August intake)",
        "deadline_summer": "August 31 (January intake)",
        "requirements": "Honours degree in CS/related; strong academic record; SOP; 2 LORs; CV",
        "english": "TOEFL 90+ / IELTS 6.5+",
        "gre": "Required (320+ recommended)",
        "min_gpa": "3.5+",
        "duration": "3",
        "ects": "N/A (30 AU)",
        "scholarships": "NTU Research Scholarship; SINGA; ASEAN scholarships",
        "portal": "https://www.ntu.edu.sg/",
        "dept_url": "https://www.ntu.edu.sg/computing",
        "research": "AI, ML, Data Science, NLP, Computer Vision",
        "students": "~33,000",
        "intl_pct": "~25%",
        "living_cost": "1,500 SGD",
        "strategy": "STRONG CHOICE. Top Asian university. Singapore hub for tech. GRE needed.",
    },
    {
        "country": "China",
        "name": "Peking University",
        "location": "Beijing, China",
        "type": "Public Research",
        "qs_rank": "17",
        "the_rank": "14",
        "program": "MSc Computer Science (AI)",
        "degree": "MSc",
        "field": "CS, AI, ML",
        "language": "English / Chinese",
        "tuition": "3,000",
        "currency": "USD",
        "semester_fee": "200",
        "app_fee": "800 CNY",
        "deadline_winter": "December 31 (early) / March 15 (regular)",
        "deadline_summer": "N/A (Fall only)",
        "requirements": "Bachelor's in CS/Math; CV; Research proposal; 2 LORs; Transcripts",
        "english": "TOEFL 90 / IELTS 6.5 (for English-taught)",
        "gre": "Not required",
        "min_gpa": "3.5+",
        "duration": "4",
        "ects": "N/A",
        "scholarships": "Chinese Government Scholarship (CSC); PKU Scholarship",
        "portal": "https://www.pku.edu.cn/",
        "dept_url": "https://www.eecs.pku.edu.cn/",
        "research": "AI, ML, Computational Science, Computer Vision",
        "students": "~44,000",
        "intl_pct": "~10%",
        "living_cost": "800 USD",
        "strategy": "REACH. Top Chinese university. Good CS program. CSC scholarships available.",
    },
    {
        "country": "China",
        "name": "Zhejiang University",
        "location": "Hangzhou, China",
        "type": "Public Research",
        "qs_rank": "47",
        "the_rank": "55",
        "program": "MSc Computer Science (AI)",
        "degree": "MSc",
        "field": "CS, AI, ML",
        "language": "English / Chinese",
        "tuition": "3,000",
        "currency": "USD",
        "semester_fee": "200",
        "app_fee": "800 CNY",
        "deadline_winter": "December 31 (early) / March 31 (regular)",
        "deadline_summer": "N/A (Fall only)",
        "requirements": "Bachelor's in CS/Math/related; CV; SOP; 2 LORs; Academic records",
        "english": "TOEFL 85 / IELTS 6.0 (for English-taught)",
        "gre": "Not required",
        "min_gpa": "3.3+",
        "duration": "4",
        "ects": "N/A",
        "scholarships": "Chinese Government Scholarship (CSC); ZJU Scholarship; Belt & Road",
        "portal": "https://www.zju.edu.cn/english/",
        "dept_url": "https://www.cs.zju.edu.cn/",
        "research": "AI, ML, Data Science, Computer Graphics, NLP",
        "students": "~44,000",
        "intl_pct": "~15%",
        "living_cost": "700 USD",
        "strategy": "GOOD VALUE. Strong CS program. Hangzhou is a tech hub (Alibaba). CSC scholarships.",
    },
    {
        "country": "Japan",
        "name": "University of Tokyo",
        "location": "Tokyo, Japan",
        "type": "Public Research",
        "qs_rank": "23",
        "the_rank": "29",
        "program": "MSc Computer Science (AI/ML)",
        "degree": "MSc",
        "field": "CS, AI, ML",
        "language": "English (WISE / GSC programs)",
        "tuition": "2,500",
        "currency": "USD",
        "semester_fee": "300",
        "app_fee": "10,000 JPY",
        "deadline_winter": "December 1 (WISE) / January 15 (regular)",
        "deadline_summer": "N/A (Fall only)",
        "requirements": "Bachelor's in CS/Math/related; strong academic record; CV; Research proposal; 2 LORs",
        "english": "TOEFL 95 / IELTS 7.0",
        "gre": "Recommended",
        "min_gpa": "3.5+",
        "duration": "4",
        "ects": "N/A",
        "scholarships": "MEXT Scholarship; UTokyo Fellowship; JASSO; ADB Scholarship",
        "portal": "https://www.u-tokyo.ac.jp/en/",
        "dept_url": "https://www.i.u-tokyo.ac.jp/",
        "research": "AI, ML, Robotics, Computer Vision, NLP (world-class research)",
        "students": "~28,000",
        "intl_pct": "~12%",
        "living_cost": "1,500 USD",
        "strategy": "REACH. Japan's #1 university. MEXT scholarship covers full costs. WISE program is English-taught.",
    },
    {
        "country": "Taiwan",
        "name": "National Taiwan University (NTU)",
        "location": "Taipei, Taiwan",
        "type": "Public Research",
        "qs_rank": "68",
        "the_rank": "69",
        "program": "MSc Computer Science (Data Science)",
        "degree": "MSc",
        "field": "CS, Data Science, ML",
        "language": "English / Chinese",
        "tuition": "2,000",
        "currency": "USD",
        "semester_fee": "150",
        "app_fee": "1,500 TWD",
        "deadline_winter": "January 31 (early) / March 15 (regular)",
        "deadline_summer": "September 30 (Spring)",
        "requirements": "Bachelor's in CS/Math/related; CV; SOP; 2 LORs; Academic transcripts",
        "english": "TOEFL 80 / IELTS 6.0 (for English-taught)",
        "gre": "Not required",
        "min_gpa": "3.3+",
        "duration": "4",
        "ects": "N/A",
        "scholarships": "Taiwan Government Scholarship; NTU Scholarship; ICDF",
        "portal": "https://www.ntu.edu.tw/english/",
        "dept_url": "https://www.csie.ntu.edu.tw/",
        "research": "Data Science, ML, AI, NLP, Computer Vision",
        "students": "~32,000",
        "intl_pct": "~8%",
        "living_cost": "700 USD",
        "strategy": "VALUE CHOICE. Taiwan's #1 university. Very affordable tuition. Good data science program.",
    },
]

AUSTRALIA_UNIVERSITIES = [
    {
        "country": "Australia",
        "name": "University of Sydney",
        "location": "Sydney, Australia",
        "type": "Public Research",
        "qs_rank": "40",
        "the_rank": "54",
        "program": "MSc Data Science",
        "degree": "MSc",
        "field": "Data Science, ML, AI",
        "language": "English",
        "tuition": "27,000",
        "currency": "AUD",
        "semester_fee": "500",
        "app_fee": "125 AUD",
        "deadline_winter": "January 31 (Sem 1) / June 30 (Sem 2)",
        "deadline_summer": "N/A",
        "requirements": "Bachelor's in CS/Stats/Math; CV; SOP; 2 LORs; Academic transcripts",
        "english": "TOEFL 96 / IELTS 7.0 (min 6.0 each)",
        "gre": "Not required",
        "min_gpa": "3.3+",
        "duration": "4",
        "ects": "N/A",
        "scholarships": "Sydney Scholars Award; Destination Australia; International Student Scholarships",
        "portal": "https://www.sydney.edu.au/",
        "dept_url": "https://www.sydney.edu.au/engineering/",
        "research": "Data Science, ML, AI, Computational Science",
        "students": "~65,000",
        "intl_pct": "~35%",
        "living_cost": "2,000 AUD",
        "strategy": "GOOD CHOICE. Top Australian university. Good data science program. Scholarships available.",
    },
    {
        "country": "Australia",
        "name": "University of Technology Sydney (UTS)",
        "location": "Sydney, Australia",
        "type": "Public Research",
        "qs_rank": "137",
        "the_rank": "148",
        "program": "MSc Data Science",
        "degree": "MSc",
        "field": "Data Science, ML, AI",
        "language": "English",
        "tuition": "22,000",
        "currency": "AUD",
        "semester_fee": "500",
        "app_fee": "None",
        "deadline_winter": "February 15 (Autumn) / July 15 (Spring)",
        "deadline_summer": "N/A",
        "requirements": "Bachelor's in related field; CV; SOP; Academic records",
        "english": "TOEFL 89 / IELTS 6.5",
        "gre": "Not required",
        "min_gpa": "3.0+",
        "duration": "4",
        "ects": "N/A",
        "scholarships": "UTS International Scholarships; Destination Australia",
        "portal": "https://www.uts.edu.au/",
        "dept_url": "https://www.uts.edu.au/future-students/degree-finder",
        "research": "Data Science, AI, ML, Applied Analytics",
        "students": "~45,000",
        "intl_pct": "~30%",
        "living_cost": "2,000 AUD",
        "strategy": "GOOD CHOICE. Strong industry connections. Sydney location. More practical/professional focus.",
    },
    {
        "country": "Australia",
        "name": "UNSW Sydney",
        "location": "Sydney, Australia",
        "type": "Public Research",
        "qs_rank": "43",
        "the_rank": "60",
        "program": "MSc Artificial Intelligence / Data Science",
        "degree": "MSc",
        "field": "AI, Data Science, ML",
        "language": "English",
        "tuition": "26,000",
        "currency": "AUD",
        "semester_fee": "500",
        "app_fee": "125 AUD",
        "deadline_winter": "January 31 (Term 1) / May 31 (Term 2) / August 31 (Term 3)",
        "deadline_summer": "N/A",
        "requirements": "Bachelor's in CS/Math/Engineering; CV; SOP; 2 LORs; Academic transcripts",
        "english": "TOEFL 94 / IELTS 7.0 (min 6.0 each)",
        "gre": "Not required",
        "min_gpa": "3.3+",
        "duration": "4",
        "ects": "N/A",
        "scholarships": "UNSW International Scholarships; Destination Australia; Scientia",
        "portal": "https://www.unsw.edu.au/",
        "dept_url": "https://www.unsw.edu.au/engineering/",
        "research": "AI, ML, Data Science, Computer Vision, Robotics",
        "students": "~64,000",
        "intl_pct": "~40%",
        "living_cost": "2,000 AUD",
        "strategy": "GOOD CHOICE. Strong AI/data science program. 3 terms per year offers flexibility.",
    },
]

CANADA_UNIVERSITIES = [
    {
        "country": "Canada",
        "name": "University of Alberta",
        "location": "Edmonton, Alberta, Canada",
        "type": "Public Research",
        "qs_rank": "110",
        "the_rank": "125",
        "program": "MSc Computer Science (AI/ML)",
        "degree": "MSc",
        "field": "CS, AI, ML",
        "language": "English",
        "tuition": "8,000",
        "currency": "CAD",
        "semester_fee": "1,000",
        "app_fee": "125 CAD",
        "deadline_winter": "December 1 (Fall intake)",
        "deadline_summer": "N/A",
        "requirements": "Bachelor's in CS/related; strong research background; CV; Research statement; 3 LORs",
        "english": "TOEFL 95+ / IELTS 7.0+",
        "gre": "Not required",
        "min_gpa": "3.3+ (competitive 3.5+)",
        "duration": "4",
        "ects": "N/A",
        "scholarships": "University of Alberta Graduate Assistantships; NSERC; Alberta Innovates",
        "portal": "https://www.ualberta.ca/",
        "dept_url": "https://www.ualberta.ca/computing-science/",
        "research": "AI, ML, Reinforcement Learning (Richard Sutton), Game AI, NLP",
        "students": "~40,000",
        "intl_pct": "~20%",
        "living_cost": "1,500 CAD",
        "strategy": "STRONG CHOICE. Home to Richard Sutton (RL pioneer). Research-focused MSc with funding. Amii AI institute.",
    },
    {
        "country": "Canada",
        "name": "McGill University",
        "location": "Montreal, Quebec, Canada",
        "type": "Public Research",
        "qs_rank": "31",
        "the_rank": "37",
        "program": "MSc Computer Science (AI/ML)",
        "degree": "MSc",
        "field": "CS, AI, ML",
        "language": "English",
        "tuition": "12,000",
        "currency": "CAD",
        "semester_fee": "1,000",
        "app_fee": "125 CAD",
        "deadline_winter": "December 15 (Fall intake)",
        "deadline_summer": "N/A",
        "requirements": "Bachelor's in CS/related; strong academic record; CV; Research statement; 3 LORs",
        "english": "TOEFL 100+ / IELTS 7.5+",
        "gre": "Not required",
        "min_gpa": "3.5+ (highly competitive)",
        "duration": "4",
        "ects": "N/A",
        "scholarships": "McGill Graduate Funding; NSERC; FRQNT; Mila affiliated",
        "portal": "https://www.mcgill.ca/",
        "dept_url": "https://www.cs.mcgill.ca/",
        "research": "ML, AI, Computer Vision, NLP, Computational Neuroscience (Mila collaboration)",
        "students": "~40,000",
        "intl_pct": "~30%",
        "living_cost": "1,500 CAD",
        "strategy": "STRONG CHOICE. Highly respected university. Mila collaboration (Bengio's group in Montreal). Research-focused MSc.",
    },
]

ALL_UNIVERSITIES = GERMAN_UNIVERSITIES + USA_UNIVERSITIES + UK_UNIVERSITIES + SWITZERLAND_UNIVERSITIES + FRANCE_UNIVERSITIES + ITALY_UNIVERSITIES + AUSTRIA_UNIVERSITIES + BELGIUM_UNIVERSITIES + NORWAY_UNIVERSITIES + NETHERLANDS_UNIVERSITIES + SWEDEN_UNIVERSITIES + DENMARK_UNIVERSITIES + FINLAND_UNIVERSITIES + ASIA_UNIVERSITIES + AUSTRALIA_UNIVERSITIES + CANADA_UNIVERSITIES

DISCOVERY_QUERIES = {
    "Germany": [
        "MSc Data Science Germany English 2026 2027 TU9 university deadline",
        "MSc Artificial Intelligence Germany English international students 2026",
        "MSc Statistics Germany English taught 2026 2027",
        "best German universities machine learning English master 2026",
        "Technical University of Munich MSc informatics data science admission 2026",
        "RWTH Aachen MSc data science computer science admission requirements 2026",
    ],
    "USA": [
        "MSc Data Science USA 2026 international students deadline application",
        "MSc Machine Learning USA top universities 2026 apply",
        "MSc Statistics USA 2026 international students funding",
        "Carnegie Mellon University MSc machine learning data science entry requirements 2026",
        "graduate assistantship data science USA 2026 international",
    ],
    "Canada": [
        "MSc Computer Science machine learning Canada top universities 2026",
        "MSc Data Science Canada international students entry requirements 2026",
        "University of Toronto MSc computer science application deadline 2026",
        "University of Montreal MSc computer science machine learning MILA admission 2026",
        "University of Waterloo MSc computer science data science admission requirements 2026",
    ],
    "UK": [
        "MSc Artificial Intelligence UK top universities 2026 admission",
        "MSc Data Science Oxford Cambridge Imperial UCL entry requirements 2026",
        "UK university application deadline international MSc computer science 2026",
    ],
    "Switzerland": [
        "ETH Zurich MSc Computer Science admission requirements international 2026",
        "ETH Zurich master data science statistics application deadline 2026",
        "EPFL master Data Science artificial intelligence admission deadline 2026",
        "EPFL MSc computer science machine learning deadline 2026",
    ],
    "Singapore": [
        "NUS master computer science artificial intelligence requirements 2026",
        "NUS MSc statistics data analytics entry requirements 2026",
        "NTU MSc data science admission requirements international students 2026",
    ],
    "Australia": [
        "MSc machine learning data science Australia top universities 2026",
        "University of Melbourne master computer science entry requirements 2026",
        "University of Melbourne MSc data science statistics admission 2026",
    ]
}


class UniversityAgent(BaseAgent):
    def __init__(self, sheets_client=None, interactive=True):
        super().__init__("UniversityAgent", sheets_client, interactive)

    def run(self, country_filter=None):
        print("\n=== UNIVERSITY RESEARCH AGENT ===")
        print("Target: Global Top CS Universities | English-taught MSc | ML/AI/Data Science/Statistics")

        if not self.ask_user("Start university research? (Will scrape program pages + search)"):
            print("Skipped.")
            return []

        self.log("Loading core university database...")
        all_curated = ALL_UNIVERSITIES
        universities = [u for u in all_curated if not country_filter or u["country"].lower() == country_filter.lower()]

        self.log("Searching live for more programs from university websites...")
        targets = list(DISCOVERY_QUERIES.keys()) if not country_filter else [country_filter]
        for country in targets:
            queries = DISCOVERY_QUERIES.get(country, [])
            if queries:
                queries = random.sample(queries, min(1, len(queries)))
            results = self.multi_search(queries, max_per_query=3)
            self.log(f"  Found {len(results)} new leads for {country}")

            for r in results:
                title = r.get("title", "")
                url = r.get("url", "")
                if not title or not url:
                    continue
                universities.append({
                    "country": country,
                    "name": title,
                    "location": "Check website",
                    "type": "Web Discovery",
                    "qs_rank": "Check",
                    "the_rank": "Check",
                    "program": title[:100],
                    "degree": "MSc/PhD (verify)",
                    "field": "ML, AI, Data Science, Statistics (verify)",
                    "language": "English (verify)",
                    "tuition": "Check website",
                    "currency": "Check",
                    "semester_fee": "Check",
                    "app_fee": "Check",
                    "deadline_winter": "Check website",
                    "deadline_summer": "Check website",
                    "requirements": "Check program page",
                    "english": "Check program page",
                    "gre": "Check program page",
                    "min_gpa": "Check program page",
                    "duration": "Check program page",
                    "ects": "Check",
                    "scholarships": "Check with university",
                    "portal": url,
                    "dept_url": url,
                    "research": "Check department page",
                    "students": "Check",
                    "intl_pct": "Check",
                    "living_cost": "Check city",
                    "strategy": "Auto-discovered. Verify details on program page.",
                })

        headers = HEADERS
        KEY_MAP = {
            "Country": "country",
            "University Name": "name",
            "Location": "location",
            "University Type": "type",
            "QS World Ranking 2025": "qs_rank",
            "THE World Ranking 2025": "the_rank",
            "Program Name": "program",
            "Degree": "degree",
            "Field / Specialization": "field",
            "Teaching Language": "language",
            "Tuition (per semester)": "tuition",
            "Currency": "currency",
            "Semester Fee / Contribution": "semester_fee",
            "Application Fee": "app_fee",
            "Application Deadline (Winter)": "deadline_winter",
            "Application Deadline (Summer)": "deadline_summer",
            "Admission Requirements": "requirements",
            "English Test Requirement": "english",
            "GRE/GMAT Required": "gre",
            "Minimum GPA Required": "min_gpa",
            "Program Duration (semesters)": "duration",
            "ECTS Credits": "ects",
            "Scholarship Availability": "scholarships",
            "Application Portal / Platform": "portal",
            "Department / Faculty URL": "dept_url",
            "Research Strengths": "research",
            "Student Population": "students",
            "International Student %": "intl_pct",
            "Cost of Living (monthly EUR/USD)": "living_cost",
            "Strategy Notes": "strategy",
            "Last Updated": None,
        }
        rows = []
        seen = set()
        for u in universities:
            key = (u["name"].lower()[:50] + u["program"].lower()[:50])
            if key in seen:
                continue
            seen.add(key)
            row = self.make_row(u, headers, KEY_MAP)
            rows.append(row)

        self.log(f"Total programs collected: {len(rows)}")

        if self.ask_user(f"Save {len(rows)} programs to storage?"):
            self.save_to_sheets("Universities", headers, rows)

        print(f"\n  === GERMANY: FREE TUITION ===")
        for u in GERMAN_UNIVERSITIES:
            tuition = "FREE" if u["tuition"] == "0" else f"{u['tuition']} EUR/sem"
            print(f"    {u['name']:35s} | {u['program'][:35]:35s} | {tuition}")

        print(f"\n  === USA: MOST AFFORDABLE (TA/RA potential) ===")
        usa_unis = [u for u in USA_UNIVERSITIES if u["country"] == "USA"]
        for u in sorted(usa_unis, key=lambda x: int(x["tuition"]) if x["tuition"].isdigit() else 999999)[:5]:
            tuition = f"${u['tuition']}/sem" if u["tuition"] else "Check"
            print(f"    {u['name']:35s} | {u['program'][:35]:35s} | {tuition}")

        print(f"\n  === GLOBAL TOP CS UNIVERSITIES (funded / low tuition) ===")
        global_unis = [u for u in all_curated if u["country"] not in ["Germany", "USA"]]
        for u in global_unis:
            tuition = f"{u['tuition']} {u['currency']}/sem"
            print(f"    {u['name']:35s} | {u['program'][:35]:35s} | {tuition} ({u['country']})")

        return universities
