"""Add scholarships for South Asian (Bangladesh, India, Pakistan) students."""
import sys, os, json
_script_root_as = os.path.dirname(os.path.dirname(__file__))
sys.path.insert(0, _script_root_as)
sys.path.insert(0, os.path.join(_script_root_as, 'src'))

DATA_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data")

# Load existing scholarships
with open(os.path.join(DATA_DIR, "core_scholarships.json"), "r", encoding="utf-8") as f:
    existing = json.load(f)

existing_names = {s["name"].lower().strip() for s in existing}

NEW_SCHOLARSHIPS = [
    # === BANGLADESH-SPECIFIC SCHOLARSHIPS ===
    {
        "country": "Bangladesh",
        "name": "Prime Minister's Fellowship for Higher Education (Bangladesh)",
        "provider": "Government of Bangladesh (UGC)",
        "coverage_type": "Full-Ride",
        "coverage": "Full tuition + living expenses + research costs + travel",
        "amount": "Varies",
        "currency": "BDT",
        "degree": "MSc, PhD",
        "fields": "All fields incl. ML, AI, Data Science, Statistics",
        "nationality": "Bangladeshi",
        "academics": "First class/division in all exams; CGPA 3.0+ for MSc, 3.5+ for PhD",
        "experience": "Must be employed in Bangladesh (public/private sector)",
        "documents": "Application form; Research proposal; Academic transcripts; NOCs from employer; Recommendation letters (2); Publication list",
        "fee": "None",
        "lang_app": "English",
        "english_test": "TOEFL/IELTS may be required",
        "gre": "May be required for some fields",
        "deadline_start": "January",
        "deadline_end": "March",
        "duration": "1-3 years",
        "interview": "Yes",
        "competition": "Very competitive",
        "portal": "https://www.ugc.gov.bd/",
        "url": "https://www.ugc.gov.bd/",
        "match": 90,
        "strategy": "Apply through UGC Bangladesh. Strong research proposal needed."
    },
    {
        "country": "Bangladesh",
        "name": "Bangabandhu Sheikh Mujib Fellowship (Bangladesh)",
        "provider": "Government of Bangladesh (ICT Division)",
        "coverage_type": "Full-Ride",
        "coverage": "Full tuition + monthly stipend + research grant + travel",
        "amount": "Varies",
        "currency": "BDT",
        "degree": "MSc, PhD",
        "fields": "ICT, Computer Science, Data Science, AI, ML, Statistics",
        "nationality": "Bangladeshi",
        "academics": "CGPA 3.5+ in relevant field",
        "experience": "Academic/research background preferred",
        "documents": "Application; Research proposal (max 10 pages); Academic transcripts; CV; Publications",
        "fee": "None",
        "lang_app": "English",
        "english_test": "TOEFL/IELTS for foreign university placement",
        "gre": "Preferred",
        "deadline_start": "January",
        "deadline_end": "February",
        "duration": "2-3 years",
        "interview": "Yes",
        "competition": "Very competitive",
        "portal": "https://www.ictd.gov.bd/",
        "url": "https://www.ictd.gov.bd/",
        "match": 92,
        "strategy": "TOP TARGET for ICT graduates. Apply through ICT Division Bangladesh."
    },
    {
        "country": "Bangladesh",
        "name": "National Science and Technology Fellowship (Bangladesh - NST)",
        "provider": "Ministry of Science & Technology, Bangladesh",
        "coverage_type": "Full-Ride",
        "coverage": "Monthly stipend + research contingency + thesis grant",
        "amount": "Varies",
        "currency": "BDT",
        "degree": "MSc, PhD",
        "fields": "Science, Technology, Engineering, Mathematics, Statistics, Data Science",
        "nationality": "Bangladeshi",
        "academics": "CGPA 3.0+ for MSc, 3.5+ for PhD in science/engineering",
        "experience": "Not required",
        "documents": "Application; Academic transcripts; Research proposal; Supervisor consent; NOC",
        "fee": "None",
        "lang_app": "English",
        "english_test": "Not required",
        "gre": "Not required",
        "deadline_start": "July",
        "deadline_end": "September",
        "duration": "1-2 years",
        "interview": "Sometimes",
        "competition": "Competitive",
        "portal": "https://most.gov.bd/",
        "url": "https://most.gov.bd/",
        "match": 85,
        "strategy": "Apply through respective university research cell. Good entry-level option."
    },

    # === INDIA-SPECIFIC SCHOLARSHIPS ===
    {
        "country": "India",
        "name": "National Overseas Scholarship (India - SC/ST)",
        "provider": "Ministry of Social Justice, Government of India",
        "coverage_type": "Full-Ride",
        "coverage": "Full tuition + living allowance (USD 15,400/year) + contingency + travel",
        "amount": "15,400",
        "currency": "USD",
        "degree": "MSc, PhD",
        "fields": "All fields incl. ML, AI, Data Science, Statistics, Computer Science",
        "nationality": "Indian (SC/ST categories)",
        "academics": "First class in relevant degree; 60%+ in 12th; 55%+ in bachelor's",
        "experience": "Not required",
        "documents": "Application; Caste certificate; Academic transcripts; Research statement; Admission proof; Income certificate",
        "fee": "None",
        "lang_app": "English",
        "english_test": "TOEFL/IELTS required",
        "gre": "GRE required for STEM",
        "deadline_start": "January",
        "deadline_end": "March",
        "duration": "Up to 5 years",
        "interview": "Yes",
        "competition": "Very competitive",
        "portal": "https://nosmsje.gov.in/",
        "url": "https://nosmsje.gov.in/",
        "match": 70,
        "strategy": "For SC/ST Indian students. Apply through NOS portal."
    },
    {
        "country": "India",
        "name": "AICTE National Doctoral Fellowship (India)",
        "provider": "AICTE, Government of India",
        "coverage_type": "Full-Ride",
        "coverage": "Monthly stipend INR 35,000-50,000 + research grant INR 2 lakh/year",
        "amount": "7,200",
        "currency": "USD",
        "degree": "PhD",
        "fields": "Engineering, Technology, Sciences incl. ML, AI, Data Science",
        "nationality": "Indian",
        "academics": "Master's degree with 60%+ or CGPA 6.5+; GATE/NET qualified",
        "experience": "Teaching/research experience preferred",
        "documents": "Application; Research proposal; GATE/NET scorecard; Academic transcripts; Publications",
        "fee": "None",
        "lang_app": "English",
        "english_test": "Not required",
        "gre": "GATE required (instead of GRE)",
        "deadline_start": "March",
        "deadline_end": "May",
        "duration": "5 years",
        "interview": "Yes",
        "competition": "Competitive",
        "portal": "https://www.aicte-india.org/",
        "url": "https://www.aicte-india.org/",
        "match": 60,
        "strategy": "For PhD in India. Requires GATE score."
    },
    {
        "country": "India",
        "name": "Kishore Vaigyanik Protsahan Yojana (KVPY) Fellowship",
        "provider": "Department of Science & Technology, India",
        "coverage_type": "Full-Ride",
        "coverage": "Monthly stipend INR 5,000-20,000 + annual contingency INR 20,000",
        "amount": "3,600",
        "currency": "USD",
        "degree": "MSc, Integrated MSc",
        "fields": "Basic Sciences, Mathematics, Statistics",
        "nationality": "Indian",
        "academics": "60%+ in 12th (Science); KVPY exam score",
        "experience": "Not required",
        "documents": "KVPY application; Exam score; Academic transcripts; Interview",
        "fee": "None",
        "lang_app": "English/Hindi",
        "english_test": "Not required",
        "gre": "Not required",
        "deadline_start": "July",
        "deadline_end": "September",
        "duration": "5 years (integrated) or 2 years (MSc)",
        "interview": "Yes",
        "competition": "Competitive",
        "portal": "https://kvpy.iisc.ac.in/",
        "url": "https://kvpy.iisc.ac.in/",
        "match": 55,
        "strategy": "For Indian students pursuing MSc in sciences. Statistics eligible."
    },

    # === PAKISTAN-SPECIFIC SCHOLARSHIPS ===
    {
        "country": "Pakistan",
        "name": "HEC Indigenous PhD Fellowship (Pakistan)",
        "provider": "Higher Education Commission (HEC) Pakistan",
        "coverage_type": "Full-Ride",
        "coverage": "Full tuition + monthly stipend PKR 60,000-100,000 + research grant + contingency",
        "amount": "Varies",
        "currency": "PKR",
        "degree": "PhD",
        "fields": "All fields incl. ML, AI, Data Science, Statistics, Computer Science",
        "nationality": "Pakistani",
        "academics": "MS/MPhil with CGPA 3.0+; 18 years education in relevant field",
        "experience": "Teaching/research experience preferred",
        "documents": "Application; Research proposal (max 20 pages); Academic transcripts; CV; Supervisor consent; Publications",
        "fee": "None",
        "lang_app": "English",
        "english_test": "TOEFL/IELTS may be required",
        "gre": "GRE (subject to field requirements)",
        "deadline_start": "January",
        "deadline_end": "March",
        "duration": "3-5 years",
        "interview": "Yes",
        "competition": "Competitive",
        "portal": "https://www.hec.gov.pk/",
        "url": "https://www.hec.gov.pk/",
        "match": 55,
        "strategy": "For PhD in Pakistan. Strong research proposal required."
    },
    {
        "country": "Pakistan",
        "name": "HEC Overseas Scholarship for MS/MPhil (Pakistan)",
        "provider": "Higher Education Commission (HEC) Pakistan",
        "coverage_type": "Full-Ride",
        "coverage": "Full tuition + living expenses + health insurance + travel + book allowance",
        "amount": "30,000",
        "currency": "USD",
        "degree": "MS, MPhil",
        "fields": "All fields incl. ML, AI, Data Science, Statistics, Engineering",
        "nationality": "Pakistani",
        "academics": "First division in all degrees; 16 years education; CGPA 3.0+",
        "experience": "Must be a regular/permanent faculty member of a Pakistani HEI",
        "documents": "Application; Research proposal; Academic transcripts; NOC from employer; Experience letters",
        "fee": "None",
        "lang_app": "English",
        "english_test": "TOEFL (79+) or IELTS (6.5+)",
        "gre": "GRE required (60th percentile+)",
        "deadline_start": "February",
        "deadline_end": "April",
        "duration": "2-3 years",
        "interview": "Yes",
        "competition": "Very competitive",
        "portal": "https://www.hec.gov.pk/",
        "url": "https://www.hec.gov.pk/",
        "match": 60,
        "strategy": "For Pakistani faculty members. Strong GRE + research proposal needed."
    },
    {
        "country": "Pakistan",
        "name": "Lahore University of Management Sciences (LUMS) Need-Based Scholarship",
        "provider": "LUMS",
        "coverage_type": "Full-Ride",
        "coverage": "Full tuition + stipend (need-based; up to 100%)",
        "amount": "Varies",
        "currency": "PKR",
        "degree": "MS, MSc, MBA",
        "fields": "Computer Science, Data Science, AI, ML, Mathematics, Statistics",
        "nationality": "Pakistani",
        "academics": "CGPA 3.0+; strong academic record",
        "experience": "Not required",
        "documents": "Application; Financial need assessment; Academic transcripts; Personal statement",
        "fee": "Application fee applies",
        "lang_app": "English",
        "english_test": "Required (TOEFL/IELTS or LUMS test)",
        "gre": "GRE/GAT required",
        "deadline_start": "November",
        "deadline_end": "February",
        "duration": "2 years",
        "interview": "Sometimes",
        "competition": "Competitive",
        "portal": "https://lums.edu.pk/",
        "url": "https://lums.edu.pk/",
        "match": 50,
        "strategy": "Apply to LUMS for MS programs. Need-based financial aid."
    },

    # === REGIONAL SOUTH ASIAN SCHOLARSHIPS ===
    {
        "country": "South Asia",
        "name": "SAARC Scholarship Scheme",
        "provider": "SAARC Member Nations",
        "coverage_type": "Full-Ride",
        "coverage": "Full tuition + monthly stipend + accommodation + book allowance",
        "amount": "Varies",
        "currency": "USD",
        "degree": "MSc, PhD",
        "fields": "All fields incl. Science, Technology, Statistics, Economics",
        "nationality": "SAARC countries (Bangladesh, India, Pakistan, Nepal, Sri Lanka, Bhutan, Maldives)",
        "academics": "Bachelor's degree with strong academic record (60%+ or CGPA 3.0+)",
        "experience": "Not required",
        "documents": "Application; Academic transcripts; Research proposal; Recommendation letters; Medical certificate",
        "fee": "None",
        "lang_app": "English",
        "english_test": "Required",
        "gre": "May be required",
        "deadline_start": "January",
        "deadline_end": "March",
        "duration": "1-3 years",
        "interview": "Possible",
        "competition": "Competitive",
        "portal": "Varies by country",
        "url": "https://www.saarc-sec.org/",
        "match": 75,
        "strategy": "Cultural exchange program. Check with respective SAARC national focal point."
    },
    {
        "country": "South Asia",
        "name": "South Asian University (SAU) Scholarships",
        "provider": "SAARC - South Asian University",
        "coverage_type": "Full-Ride",
        "coverage": "Full tuition waiver + monthly stipend INR 15,000-25,000 + hostel",
        "amount": "5,000",
        "currency": "USD",
        "degree": "MSc, PhD",
        "fields": "Computer Science, Mathematics, Statistics, Economics",
        "nationality": "SAARC countries (Bangladesh, India, Pakistan, etc.)",
        "academics": "Bachelor's with 55%+ or CGPA 5.0+",
        "experience": "Not required",
        "documents": "Application; Academic transcripts; Entrance exam; Interview",
        "fee": "None",
        "lang_app": "English",
        "english_test": "Not required (English-medium instruction)",
        "gre": "Not required",
        "deadline_start": "February",
        "deadline_end": "May",
        "duration": "2-5 years",
        "interview": "Yes",
        "competition": "Moderate",
        "portal": "https://www.sau.int/",
        "url": "https://www.sau.int/",
        "match": 70,
        "strategy": "Apply to SAU New Delhi. Entrance exam + interview."
    },
    {
        "country": "Commonwealth",
        "name": "Commonwealth Master's Scholarship (for Developing Countries)",
        "provider": "Commonwealth Scholarship Commission (UK)",
        "coverage_type": "Full-Ride",
        "coverage": "Full tuition + airfare + living allowance + warm clothing allowance + study travel grant",
        "amount": "25,000",
        "currency": "GBP",
        "degree": "MSc",
        "fields": "All fields (development-related preferred), incl. ML, AI, Data Science",
        "nationality": "Commonwealth developing countries including Bangladesh, India, Pakistan",
        "academics": "First class degree (65%+ or CGPA 3.5+); less than 35 years old",
        "experience": "Not required but preferred",
        "documents": "Application; Academic transcripts; Reference letters; Development impact statement; Supporting statement",
        "fee": "None",
        "lang_app": "English",
        "english_test": "IELTS 6.5+ (academic)",
        "gre": "Not required",
        "deadline_start": "October",
        "deadline_end": "December",
        "duration": "12 months",
        "interview": "Possible",
        "competition": "Very competitive (1000+ for 30 slots per country)",
        "portal": "https://cscuk.fcdo.gov.uk/",
        "url": "https://cscuk.fcdo.gov.uk/",
        "match": 85,
        "strategy": "PRIMARY TARGET for Commonwealth citizens. Apply through national nominating agency."
    },
    {
        "country": "Commonwealth",
        "name": "Commonwealth PhD Scholarship (for Developing Countries)",
        "provider": "Commonwealth Scholarship Commission (UK)",
        "coverage_type": "Full-Ride",
        "coverage": "Full tuition + airfare + living allowance + research grant + warm clothing",
        "amount": "30,000",
        "currency": "GBP",
        "degree": "PhD",
        "fields": "All fields, STEM incl. ML, AI, Data Science, Statistics",
        "nationality": "Commonwealth developing countries including Bangladesh, India, Pakistan",
        "academics": "Master's degree with 65%+; less than 40 years old",
        "experience": "Research experience preferred",
        "documents": "Application; Research proposal; Academic transcripts; Publications; Supporting statement",
        "fee": "None",
        "lang_app": "English",
        "english_test": "IELTS 6.5+ (academic)",
        "gre": "Not required",
        "deadline_start": "October",
        "deadline_end": "December",
        "duration": "3 years",
        "interview": "Yes",
        "competition": "Very competitive",
        "portal": "https://cscuk.fcdo.gov.uk/",
        "url": "https://cscuk.fcdo.gov.uk/",
        "match": 80,
        "strategy": "Apply through nominating agency in home country."
    },

    # === MORE FULL-RIDE SCHOLARSHIPS FOR SOUTH ASIANS ===
    {
        "country": "Germany",
        "name": "DAAD Helmut Schmidt Programme (Master's for Public Policy)",
        "provider": "DAAD",
        "coverage_type": "Full-Ride",
        "coverage": "Full tuition + 934 EUR/month + health insurance + travel + rent subsidy + family allowance",
        "amount": "11,208",
        "currency": "EUR",
        "degree": "MA, MSc",
        "fields": "Public Policy, Governance, International Relations, Economics incl. Data Policy",
        "nationality": "Bangladesh, India, Pakistan, and other developing countries",
        "academics": "Bachelor's degree (2.5+ German grade); less than 6 years since graduation",
        "experience": "2+ years professional experience in public policy/administration",
        "documents": "DAAD form; CV; Motivation letter; Research proposal; Letters of recommendation; Work certificates",
        "fee": "None",
        "lang_app": "English",
        "english_test": "TOEFL/IELTS required",
        "gre": "Not required",
        "deadline_start": "June",
        "deadline_end": "August",
        "duration": "18-24 months",
        "interview": "Possible",
        "competition": "Very competitive (selects 70/3000+ applicants)",
        "portal": "https://www.daad.de/helmut-schmidt",
        "url": "https://www.daad.de/helmut-schmidt",
        "match": 70,
        "strategy": "For policy/administration professionals. Strong work experience needed."
    },
    {
        "country": "Japan",
        "name": "MEXT Research Scholarship (Japan - for Bangladesh, India, Pakistan)",
        "provider": "MEXT (Japanese Government)",
        "coverage_type": "Full-Ride",
        "coverage": "Full tuition + monthly stipend ~145,000 JPY + travel + accommodation support + health insurance",
        "amount": "14,000",
        "currency": "USD",
        "degree": "MSc, PhD",
        "fields": "All fields incl. ML, AI, Computer Science, Data Science, Statistics, Engineering",
        "nationality": "All countries including Bangladesh, India, Pakistan",
        "academics": "Strong academic record (CGPA 3.0+); born after April 2, 1989",
        "experience": "Not required",
        "documents": "Application; Research proposal; Academic transcripts; Recommendation letters (2); Letter from Japanese supervisor; Abstract of thesis",
        "fee": "None",
        "lang_app": "English or Japanese",
        "english_test": "TOEFL/IELTS or JLPT",
        "gre": "GRE recommended for some fields",
        "deadline_start": "April",
        "deadline_end": "June",
        "duration": "2-5 years",
        "interview": "Yes",
        "competition": "Very competitive",
        "portal": "https://www.mext.go.jp/en/",
        "url": "https://www.mext.go.jp/en/",
        "match": 75,
        "strategy": "Apply through Japanese Embassy in Dhaka/Delhi/Islamabad. Must contact Japanese professor first."
    },
    {
        "country": "Japan",
        "name": "ADB-JSP Scholarship (Asian Development Bank)",
        "provider": "Asian Development Bank",
        "coverage_type": "Full-Ride",
        "coverage": "Full tuition + monthly stipend + housing + book allowance + health insurance + travel",
        "amount": "20,000",
        "currency": "USD",
        "degree": "MSc, MA",
        "fields": "Economics, Management, Science, Technology, Engineering incl. Data Science",
        "nationality": "ADB developing member countries including Bangladesh, India, Pakistan",
        "academics": "Bachelor's degree with excellent academic record; 2+ years work experience; less than 35 years old",
        "experience": "2+ years professional experience required",
        "documents": "Application; Academic transcripts; Employer endorsement; Recommendation letters; Income statement; Medical report",
        "fee": "None",
        "lang_app": "English",
        "english_test": "TOEFL/IELTS (varies by university)",
        "gre": "GRE/GMAT may be required",
        "deadline_start": "July",
        "deadline_end": "September",
        "duration": "1-2 years",
        "interview": "Possible",
        "competition": "Very competitive",
        "portal": "https://www.adb.org/work/jsp",
        "url": "https://www.adb.org/work/jsp",
        "match": 78,
        "strategy": "For ADB member country citizens. Must return to home country after study."
    },
    {
        "country": "Singapore",
        "name": "Singapore International Graduate Award (SINGA) - for South Asians",
        "provider": "Singapore Government",
        "coverage_type": "Full-Ride",
        "coverage": "Full tuition + monthly stipend SGD 2,200 + one-time airfare grant SGD 1,500 + settling-in allowance SGD 1,000",
        "amount": "23,000",
        "currency": "USD",
        "degree": "PhD",
        "fields": "Science, Engineering, incl. Computer Science, AI, ML, Data Science, Statistics",
        "nationality": "All countries including Bangladesh, India, Pakistan",
        "academics": "Excellent academic record (CGPA 3.5+ preferred); bachelor's or master's degree",
        "experience": "Research experience preferred",
        "documents": "Application; Research proposal; Academic transcripts; Recommendation letters (2); GRE/TOEFL scores; Publications",
        "fee": "None",
        "lang_app": "English",
        "english_test": "TOEFL (92+) or IELTS (6.5+)",
        "gre": "GRE required (315+ preferred)",
        "deadline_start": "June",
        "deadline_end": "December",
        "duration": "4 years",
        "interview": "Yes",
        "competition": "Very competitive",
        "portal": "https://www.singa.a-star.edu.sg/",
        "url": "https://www.singa.a-star.edu.sg/",
        "match": 82,
        "strategy": "EXCELLENT TARGET. Apply to A*STAR Singapore. Strong GRE + research background needed."
    },
    {
        "country": "China",
        "name": "Chinese Government Scholarship (CSC) - for Bangladeshi, Indian, Pakistani Students",
        "provider": "Chinese Scholarship Council (CSC)",
        "coverage_type": "Full-Ride",
        "coverage": "Full tuition + monthly stipend (3,500-4,200 CNY) + accommodation + medical insurance + travel",
        "amount": "8,000",
        "currency": "USD",
        "degree": "MSc, PhD",
        "fields": "All fields incl. AI, ML, Computer Science, Data Science, Statistics",
        "nationality": "All countries including Bangladesh, India, Pakistan",
        "academics": "CGPA 3.0+; bachelor's for MSc, master's for PhD",
        "experience": "Not required",
        "documents": "Application; Academic transcripts; Research proposal; Recommendation letters; Passport copy; Physical exam; HSK (if Chinese-taught)",
        "fee": "None",
        "lang_app": "English or Chinese",
        "english_test": "TOEFL/IELTS (for English-taught programs)",
        "gre": "Not required",
        "deadline_start": "January",
        "deadline_end": "March",
        "duration": "2-5 years",
        "interview": "Possible",
        "competition": "Competitive (500+ for Bangladesh)",
        "portal": "https://www.campuschina.org/",
        "url": "https://www.campuschina.org/",
        "match": 72,
        "strategy": "Apply through Chinese Embassy in Dhaka/Delhi/Islamabad. Good backup option."
    },
    {
        "country": "Turkey",
        "name": "Turkiye Burslari (Türkiye Scholarship) - for South Asians",
        "provider": "Government of Türkiye",
        "coverage_type": "Full-Ride",
        "coverage": "Full tuition + monthly stipend (1,400-2,400 TL) + accommodation + health insurance + travel + Turkish language course",
        "amount": "9,000",
        "currency": "USD",
        "degree": "MSc, PhD",
        "fields": "All fields incl. AI, ML, Computer Science, Data Science, Statistics",
        "nationality": "All countries, priority to Bangladesh, India, Pakistan, and developing countries",
        "academics": "CGPA 3.0+ (70%+); bachelor's for MSc, master's for PhD; max age 30 for MSc, 35 for PhD",
        "experience": "Not required",
        "documents": "Application; Academic transcripts; Diploma; Research proposal; Recommendation letters; International exam scores",
        "fee": "None",
        "lang_app": "English or Turkish",
        "english_test": "Not required (one-year Turkish prep available)",
        "gre": "Not required",
        "deadline_start": "January",
        "deadline_end": "February",
        "duration": "1-3 years",
        "interview": "Yes",
        "competition": "Competitive",
        "portal": "https://www.turkiyeburslari.gov.tr/",
        "url": "https://www.turkiyeburslari.gov.tr/",
        "match": 75,
        "strategy": "Apply through Turkiye Burslari portal. No English test needed - one-year prep included."
    },
    {
        "country": "Hungary",
        "name": "Stipendium Hungaricum (Hungary - for South Asians)",
        "provider": "Government of Hungary (Tempus Public Foundation)",
        "coverage_type": "Full-Ride",
        "coverage": "Full tuition + monthly stipend HUF 40,000-140,000 + accommodation + health insurance + travel contribution",
        "amount": "8,000",
        "currency": "USD",
        "degree": "MSc, PhD",
        "fields": "All fields incl. Computer Science, AI, ML, Data Science, Mathematics, Statistics",
        "nationality": "Bangladesh, India, Pakistan (among 70+ partner countries)",
        "academics": "CGPA 3.5+ preferred (varies by country); max 25 years for MSc",
        "experience": "Not required",
        "documents": "Application; Academic transcripts; Motivation letter; Recommendation letter; Medical certificate",
        "fee": "None",
        "lang_app": "English",
        "english_test": "TOEFL/IELTS recommended (but may be exempted)",
        "gre": "Not required",
        "deadline_start": "November",
        "deadline_end": "January",
        "duration": "2-4 years",
        "interview": "Possible",
        "competition": "Competitive",
        "portal": "https://stipendiumhungaricum.hu/",
        "url": "https://stipendiumhungaricum.hu/",
        "match": 80,
        "strategy": "GOOD TARGET. Apply through Tempus Public Foundation. No GRE required; good option for Statistics students."
    },
    {
        "country": "Switzerland",
        "name": "Swiss Government Excellence Scholarship (for South Asian Students)",
        "provider": "Swiss Government (FCS)",
        "coverage_type": "Full-Ride",
        "coverage": "Monthly stipend CHF 1,920 + tuition + health insurance + housing allowance + travel",
        "amount": "28,000",
        "currency": "USD",
        "degree": "MSc, PhD",
        "fields": "All fields incl. AI, ML, Data Science, Computer Science, Mathematics, Statistics",
        "nationality": "70+ countries including Bangladesh, India, Pakistan",
        "academics": "Master's degree (for PhD research); excellent academic record (CGPA 3.5+)",
        "experience": "Research experience required",
        "documents": "Application; Research proposal; CV; Academic transcripts; Recommendation letters (2); Publications; Host professor confirmation",
        "fee": "None",
        "lang_app": "English",
        "english_test": "TOEFL/IELTS required",
        "gre": "Not required",
        "deadline_start": "August",
        "deadline_end": "November",
        "duration": "1-3 years",
        "interview": "Possible",
        "competition": "Very competitive",
        "portal": "https://www.sbfi.admin.ch/",
        "url": "https://www.sbfi.admin.ch/",
        "match": 68,
        "strategy": "For PhD/Post-doc. Must contact a Swiss professor before applying."
    },
    {
        "country": "Netherlands",
        "name": "Orange Knowledge Programme (OKP) - for South Asians",
        "provider": "Dutch Ministry of Foreign Affairs (Nuffic)",
        "coverage_type": "Full-Ride",
        "coverage": "Full tuition + living expenses + visa + insurance + travel + course fees",
        "amount": "25,000",
        "currency": "EUR",
        "degree": "MSc, MA",
        "fields": "All fields incl. Data Science, AI, Statistics (development-related preferred)",
        "nationality": "Bangladesh, India, Pakistan (among 51 eligible countries)",
        "academics": "Bachelor's degree with strong academic record; 2-5 years work experience",
        "experience": "2+ years professional experience required",
        "documents": "Application; Academic transcripts; Employer statement; Motivation letter; Recommendation letters",
        "fee": "None",
        "lang_app": "English",
        "english_test": "IELTS 6.5+ or TOEFL 90+",
        "gre": "Not required",
        "deadline_start": "February",
        "deadline_end": "May",
        "duration": "12-24 months",
        "interview": "Possible",
        "competition": "Very competitive",
        "portal": "https://www.studyinholland.nl/",
        "url": "https://www.studyinholland.nl/",
        "match": 76,
        "strategy": "For professionals from developing countries. Work experience required."
    },
    {
        "country": "Italy",
        "name": "Italian Government Scholarship for Foreign Students (for South Asians)",
        "provider": "Ministry of Foreign Affairs, Italy (MAECI)",
        "coverage_type": "Full-Ride",
        "coverage": "Full tuition waiver + monthly stipend 900 EUR + health insurance",
        "amount": "12,000",
        "currency": "EUR",
        "degree": "MSc, PhD",
        "fields": "All fields incl. AI, ML, Computer Science, Data Science, Statistics, Engineering",
        "nationality": "All countries including Bangladesh, India, Pakistan",
        "academics": "CGPA 3.0+; bachelor's for MSc; master's for PhD; max age 30 for MSc, 35 for PhD",
        "experience": "Not required (for MSc)",
        "documents": "Application; Academic transcripts; Research proposal (for PhD); Recommendation letters; Portfolio (if applicable)",
        "fee": "None",
        "lang_app": "English or Italian",
        "english_test": "B2 level English (if English-taught)",
        "gre": "Not required",
        "deadline_start": "March",
        "deadline_end": "May",
        "duration": "6-9 months (renewable)",
        "interview": "Possible",
        "competition": "Competitive",
        "portal": "https://studyinitaly.it/",
        "url": "https://studyinitaly.it/",
        "match": 65,
        "strategy": "Apply through Italian Embassy in Dhaka/Delhi/Islamabad."
    },
    {
        "country": "France",
        "name": "Eiffel Excellence Scholarship (France - for South Asians)",
        "provider": "Campus France / Ministry of Foreign Affairs",
        "coverage_type": "Full-Ride",
        "coverage": "Monthly stipend 1,181 EUR + international travel + health insurance + cultural activities (tuition NOT covered - must get waiver)",
        "amount": "16,000",
        "currency": "EUR",
        "degree": "MSc, PhD",
        "fields": "Engineering, Science incl. AI, ML, Data Science, Mathematics (for MSc); all fields (for PhD)",
        "nationality": "All countries including Bangladesh, India, Pakistan (max 25 years for MSc)",
        "academics": "Excellent academic record; must be nominated by a French university",
        "experience": "Not required",
        "documents": "University nomination; Application; Academic transcripts; Research proposal; Recommendation letters",
        "fee": "None (but must secure tuition waiver from host university)",
        "lang_app": "English or French",
        "english_test": "TOEFL/IELTS (varies by program)",
        "gre": "Not required",
        "deadline_start": "October",
        "deadline_end": "January",
        "duration": "12-36 months",
        "interview": "No",
        "competition": "Very competitive (70% rejection)",
        "portal": "https://www.campusfrance.org/en/eiffel",
        "url": "https://www.campusfrance.org/en/eiffel",
        "match": 72,
        "strategy": "Must be nominated by a French university. First get admission, then university nominates you."
    },
    {
        "country": "Australia",
        "name": "Australia Awards Scholarship (for South Asians)",
        "provider": "Australian Government (Department of Foreign Affairs)",
        "coverage_type": "Full-Ride",
        "coverage": "Full tuition + return airfare + living stipend (AUD 30,000/year) + establishment allowance + health cover + academic support",
        "amount": "30,000",
        "currency": "AUD",
        "degree": "MSc, PhD",
        "fields": "All fields incl. AI, ML, Data Science, Computer Science, Statistics",
        "nationality": "Bangladesh, India, Pakistan (among developing country list)",
        "academics": "First class degree (65%+ or CGPA 3.5+); less than 45 years old; IELTS 6.5+",
        "experience": "2+ years professional experience required",
        "documents": "Application; Academic transcripts; Employer endorsement; Development impact statement; Recommendation letters",
        "fee": "None",
        "lang_app": "English",
        "english_test": "IELTS 6.5+ (no band less than 6.0)",
        "gre": "Not required",
        "deadline_start": "January",
        "deadline_end": "April",
        "duration": "2-4 years",
        "interview": "Possible",
        "competition": "Very competitive",
        "portal": "https://www.dfat.gov.au/",
        "url": "https://www.dfat.gov.au/",
        "match": 82,
        "strategy": "PRIMARY TARGET. Apply through DFAT. Return to home country for 2 years after completion."
    },
    {
        "country": "New Zealand",
        "name": "New Zealand Excellence Scholarship (for South Asians)",
        "provider": "New Zealand Government (MFAT)",
        "coverage_type": "Full-Ride",
        "coverage": "Full tuition + living stipend NZD 25,000/year + travel + health insurance + academic support",
        "amount": "28,000",
        "currency": "NZD",
        "degree": "MSc, PhD",
        "fields": "All fields incl. AI, ML, Data Science, Statistics, Computer Science",
        "nationality": "Bangladesh, India, Pakistan (among developing countries)",
        "academics": "CGPA 3.5+; 4-year bachelor's degree or master's",
        "experience": "2+ years professional experience preferred",
        "documents": "Application; Academic transcripts; Employer support; Development impact statement; Recommendation letters",
        "fee": "None",
        "lang_app": "English",
        "english_test": "IELTS 6.5+",
        "gre": "Not required",
        "deadline_start": "January",
        "deadline_end": "March",
        "duration": "2-4 years",
        "interview": "Possible",
        "competition": "Competitive",
        "portal": "https://www.mfat.govt.nz/",
        "url": "https://www.mfat.govt.nz/",
        "match": 72,
        "strategy": "Apply through MFAT. Must return to home country for 2 years."
    },
    {
        "country": "Korea",
        "name": "Global Korea Scholarship (GKS) - for South Asians",
        "provider": "Korean Government (NIIED)",
        "coverage_type": "Full-Ride",
        "coverage": "Full tuition + monthly stipend KRW 1,000,000 + airfare + Korean language training + medical insurance + settlement allowance",
        "amount": "15,000",
        "currency": "USD",
        "degree": "MSc, PhD",
        "fields": "All fields incl. AI, ML, Data Science, Computer Science, Statistics, Engineering",
        "nationality": "All countries including Bangladesh, India, Pakistan",
        "academics": "CGPA 3.0+; bachelor's for MSc (max 25), master's for PhD (max 35); TOPIK preferred",
        "experience": "Not required",
        "documents": "Application; Academic transcripts; Research proposal; Recommendation letters; TOPIK certificate (if available); Portfolio",
        "fee": "None",
        "lang_app": "English or Korean",
        "english_test": "TOEFL/IELTS (preferred but not mandatory)",
        "gre": "Not required",
        "deadline_start": "February",
        "deadline_end": "April",
        "duration": "2-5 years",
        "interview": "Yes",
        "competition": "Very competitive (30:1 ratio)",
        "portal": "https://www.studyinkorea.go.kr/",
        "url": "https://www.studyinkorea.go.kr/",
        "match": 74,
        "strategy": "Apply through Korean Embassy in Dhaka/Delhi/Islamabad or directly to universities."
    },
    {
        "country": "USA",
        "name": "Hubert H. Humphrey Fellowship Program (for South Asian Professionals)",
        "provider": "US Department of State (IIE)",
        "coverage_type": "Full-Ride",
        "coverage": "Full tuition + monthly stipend + travel + health insurance + professional development + book allowance",
        "amount": "35,000",
        "currency": "USD",
        "degree": "Professional Fellowship",
        "fields": "All fields incl. Statistics, Data Science, AI, ML, Economics (applied)",
        "nationality": "Bangladesh, India, Pakistan (among 160+ countries)",
        "academics": "Bachelor's degree; 5+ years professional experience; demonstrated leadership",
        "experience": "5+ years required; leadership experience essential",
        "documents": "Application; Academic transcripts; Recommendation letters (3); Professional resume; Essays (leadership, public service)",
        "fee": "None",
        "lang_app": "English",
        "english_test": "TOEFL (71+) or IELTS (6.0+)",
        "gre": "Not required",
        "deadline_start": "April",
        "deadline_end": "June",
        "duration": "10 months",
        "interview": "Yes",
        "competition": "Very competitive",
        "portal": "https://www.humphreyfellowship.org/",
        "url": "https://www.humphreyfellowship.org/",
        "match": 50,
        "strategy": "For mid-career professionals. Not a degree program - professional enrichment."
    },
    {
        "country": "USA",
        "name": "American University Emerging Global Leader Scholarship (for South Asians)",
        "provider": "American University (Washington DC)",
        "coverage_type": "Full-Ride",
        "coverage": "Full tuition + accommodation + living expenses + health insurance (renewable for 4 years)",
        "amount": "60,000",
        "currency": "USD",
        "degree": "BA, BS",
        "fields": "All fields incl. Computer Science, Data Science, AI, Mathematics, Statistics",
        "nationality": "All countries including Bangladesh, India, Pakistan",
        "academics": "Exceptional academic record (CGPA 3.8+); demonstrated leadership; strong English",
        "experience": "Leadership and community service required",
        "documents": "Application; Academic transcripts; Recommendation letters (2); Essays; Proof of English; Standardized test scores",
        "fee": "Application fee $50",
        "lang_app": "English",
        "english_test": "TOEFL 100+ or IELTS 7.0+",
        "gre": "SAT/ACT required",
        "deadline_start": "November",
        "deadline_end": "January",
        "duration": "4 years",
        "interview": "Yes",
        "competition": "Extremely competitive (1-2 students/year globally)",
        "portal": "https://www.american.edu/",
        "url": "https://www.american.edu/",
        "match": 30,
        "strategy": "For undergraduate only. Extremely competitive but fully covers everything."
    },
    {
        "country": "Canada",
        "name": "Vanier Canada Graduate Scholarship (for South Asians)",
        "provider": "Canadian Government (SSHRC/NSERC/CIHR)",
        "coverage_type": "Full-Ride",
        "coverage": "CAD 50,000/year stipend + tuition support (must secure tuition waiver from university separately)",
        "amount": "50,000",
        "currency": "CAD",
        "degree": "PhD",
        "fields": "All fields incl. AI, ML, Data Science, Statistics, Computer Science",
        "nationality": "All countries including Bangladesh, India, Pakistan",
        "academics": "First class average (A-/80%+); must be nominated by a Canadian university; less than 35 years",
        "experience": "Strong research record; publications preferred",
        "documents": "University nomination; Application; Research proposal; Leadership statement; Academic transcripts; Recommendation letters; Publications",
        "fee": "None (nomination by university)",
        "lang_app": "English or French",
        "english_test": "TOEFL/IELTS (varies by university)",
        "gre": "May be required",
        "deadline_start": "July",
        "deadline_end": "November",
        "duration": "3 years",
        "interview": "No",
        "competition": "Very competitive (166/year out of 1000+ nominees)",
        "portal": "https://vanier.gc.ca/",
        "url": "https://vanier.gc.ca/",
        "match": 60,
        "strategy": "Must be nominated by a Canadian university. First secure admission + supervisor, then get nominated."
    },
    {
        "country": "Austria",
        "name": "Austrian Development Cooperation Scholarship (OEAD) - for South Asians",
        "provider": "Austrian Agency for International Cooperation (OEAD)",
        "coverage_type": "Full-Ride",
        "coverage": "Full tuition + monthly stipend 1,050 EUR + travel + health insurance + rent subsidy",
        "amount": "15,000",
        "currency": "EUR",
        "degree": "MSc",
        "fields": "All fields incl. AI, ML, Data Science, Computer Science, Statistics (development-related)",
        "nationality": "Developing countries including Bangladesh, India, Pakistan",
        "academics": "Bachelor's degree with strong record; limited to specific partner universities",
        "experience": "2+ years professional experience recommended",
        "documents": "Application; Academic transcripts; Motivation letter; Recommendation letters; Work certificates",
        "fee": "None",
        "lang_app": "English or German",
        "english_test": "TOEFL/IELTS or German certificate",
        "gre": "Not required",
        "deadline_start": "October",
        "deadline_end": "February",
        "duration": "2-4 semesters",
        "interview": "Possible",
        "competition": "Competitive",
        "portal": "https://www.oead.at/",
        "url": "https://www.oead.at/",
        "match": 62,
        "strategy": "Apply through OEAD. Good for development-focused studies."
    },
    {
        "country": "Sweden",
        "name": "Swedish Institute Scholarships for Global Professionals (SISGP) - for South Asians",
        "provider": "Swedish Institute",
        "coverage_type": "Full-Ride",
        "coverage": "Full tuition + monthly stipend SEK 11,000 + travel grant SEK 15,000 + insurance",
        "amount": "18,000",
        "currency": "USD",
        "degree": "MSc",
        "fields": "All fields incl. AI, ML, Data Science, Computer Science, Statistics",
        "nationality": "Bangladesh, India, Pakistan (among 42 eligible countries)",
        "academics": "Bachelor's degree with strong record; 3,000+ work hours required; demonstrated leadership",
        "experience": "3,000+ hours work experience required",
        "documents": "Application; Academic transcripts; CV; Motivation letter; Leadership essay; Recommendation letters; Work proof",
        "fee": "None",
        "lang_app": "English",
        "english_test": "IELTS 6.5+ or TOEFL 90+ (required for university admission)",
        "gre": "Not required",
        "deadline_start": "October",
        "deadline_end": "February",
        "duration": "1-2 years",
        "interview": "Possible",
        "competition": "Very competitive (5-8% acceptance rate)",
        "portal": "https://si.se/scholarships/",
        "url": "https://si.se/scholarships/",
        "match": 78,
        "strategy": "For professionals with work experience. Strong leadership profile needed."
    },
    {
        "country": "Denmark",
        "name": "Danish Government Scholarship (for South Asian Students)",
        "provider": "Danish Ministry of Higher Education",
        "coverage_type": "Partial to Full",
        "coverage": "Full or partial tuition waiver + monthly stipend (varies by university; typically DKK 4,000-7,000/month)",
        "amount": "12,000",
        "currency": "EUR",
        "degree": "MSc",
        "fields": "All fields incl. AI, ML, Computer Science, Data Science, Statistics",
        "nationality": "Non-EU/EEA including Bangladesh, India, Pakistan",
        "academics": "CGPA 3.3+ (varies by university); strong academic background",
        "experience": "Not required",
        "documents": "University admission application; Scholarship essay; Academic transcripts; CV; Recommendation letters",
        "fee": "Varies by university",
        "lang_app": "English",
        "english_test": "IELTS 6.5+ or TOEFL 83+ (varies by university)",
        "gre": "Not required",
        "deadline_start": "January",
        "deadline_end": "March",
        "duration": "2 years",
        "interview": "No",
        "competition": "Competitive",
        "portal": "Varies by university (DTU, AU, KU, AAU, SDU, etc.)",
        "url": "https://studyindenmark.dk/",
        "match": 60,
        "strategy": "Apply directly to Danish universities. Each university manages its own scholarships."
    },
    {
        "country": "Finland",
        "name": "Finnish Government Scholarship (for South Asian Students)",
        "provider": "Finnish National Agency for Education (EDUFI)",
        "coverage_type": "Partial",
        "coverage": "Monthly stipend 1,700 EUR + travel grant (tuition NOT covered; must secure tuition waiver from university)",
        "amount": "22,000",
        "currency": "EUR",
        "degree": "MSc, PhD",
        "fields": "All fields incl. AI, ML, Data Science, Computer Science, Statistics",
        "nationality": "All countries including Bangladesh, India, Pakistan",
        "academics": "Excellent academic record; must be admitted to a Finnish university first",
        "experience": "Research background required (for PhD)",
        "documents": "University admission; Research plan; Academic transcripts; Host professor invitation",
        "fee": "None (application through university)",
        "lang_app": "English",
        "english_test": "IELTS 6.5+ or TOEFL 92+",
        "gre": "Not required",
        "deadline_start": "March",
        "deadline_end": "May",
        "duration": "3-12 months",
        "interview": "No",
        "competition": "Competitive",
        "portal": "https://www.edufi.fi/",
        "url": "https://www.edufi.fi/",
        "match": 50,
        "strategy": "First get admitted to a Finnish university, then apply for EDUFI scholarship."
    },

    # === ETH ZURICH / SWISS FEDERAL INSTITUTE ===
    {
        "country": "Switzerland",
        "name": "ETH Zurich Excellence Scholarship (ESOP) - for South Asian Students",
        "provider": "ETH Zurich",
        "coverage_type": "Full-Ride",
        "coverage": "Full tuition + living stipend CHF 12,000/semester + mentoring program + research opportunities",
        "amount": "30,000",
        "currency": "CHF",
        "degree": "MSc",
        "fields": "All fields incl. AI, ML, Computer Science, Data Science, Statistics, Mathematics, Engineering",
        "nationality": "All countries including Bangladesh, India, Pakistan",
        "academics": "Outstanding academic record (top 10% of class); CGPA 3.7+ preferred",
        "experience": "Research experience preferred",
        "documents": "University admission application; Research proposal; Academic transcripts; Recommendation letters (2); Statement of purpose",
        "fee": "CHF 150 application fee",
        "lang_app": "English",
        "english_test": "TOEFL 100+ or IELTS 7.0+",
        "gre": "GRE recommended (Quant 165+)",
        "deadline_start": "November",
        "deadline_end": "December",
        "duration": "2 years",
        "interview": "Possible",
        "competition": "Very competitive (20-30 scholarships/year)",
        "portal": "https://ethz.ch/en/",
        "url": "https://ethz.ch/en/",
        "match": 60,
        "strategy": "Apply to ETH Zurich MSc program. Exceptional academics only."
    },
    {
        "country": "Canada",
        "name": "University of Toronto Lester B. Pearson International Scholarship (for South Asians)",
        "provider": "University of Toronto",
        "coverage_type": "Full-Ride",
        "coverage": "Full tuition + books + incidental fees + residence support (CAD 20,000-40,000/year)",
        "amount": "40,000",
        "currency": "CAD",
        "degree": "BA, BS",
        "fields": "All fields incl. Computer Science, Mathematics, Statistics, AI, ML",
        "nationality": "All countries including Bangladesh, India, Pakistan",
        "academics": "Exceptional academic record; demonstrated leadership; innovative thinking",
        "experience": "Leadership and community involvement expected",
        "documents": "School nomination (must be nominated by high school); Application; Essays; Academic transcripts; Recommendation letters",
        "fee": "CAD 250 application fee",
        "lang_app": "English",
        "english_test": "TOEFL 100+ or IELTS 6.5+",
        "gre": "Not required (undergraduate)",
        "deadline_start": "September",
        "deadline_end": "November",
        "duration": "4 years",
        "interview": "Yes",
        "competition": "Very competitive",
        "portal": "https://future.utoronto.ca/",
        "url": "https://future.utoronto.ca/",
        "match": 25,
        "strategy": "Undergraduate program. Must be nominated by school."
    },
]

# Add only unique scholarships
added = 0
for s in NEW_SCHOLARSHIPS:
    name_lower = s["name"].lower().strip()
    if name_lower not in existing_names:
        existing.append(s)
        existing_names.add(name_lower)
        added += 1
    else:
        print(f"Skipping duplicate: {s['name']}")

# Save
with open(os.path.join(DATA_DIR, "core_scholarships.json"), "w", encoding="utf-8") as f:
    json.dump(existing, f, indent=2, ensure_ascii=False)

print(f"\nAdded {added} new scholarships")
print(f"Total scholarships now: {len(existing)}")

# Show by country
from collections import Counter
countries = Counter(s.get("country", "Unknown") for s in existing)
print("\nScholarships by country:")
for c, n in sorted(countries.items()):
    print(f"  {c}: {n}")
